bitpay/wallet

js/controllers/receive.js
views/receive.html

* Update QR code after click on "Generate new address"
* Optimize Receive section for mobile. (show addresses when clicking on "Show all my addresses" button)

Optimize Receive section for mobile

---

js/controllers/createProfile.js
js/models/Async.js
js/models/Wallet.js

- better sync for incomplete wallets after close / open

better sync for incomplete wallets after close/open

---

views/modals/address-book.html
views/send.html

* Remove unused icons
* Scan QR button aligned to right
fixes #2268

Ux/addressbook icons - Scan QR button

---

views/receive.html

Fix generate address button on receive

---

js/controllers/home.js
views/home.html

* Only for mobile devices (fixes #2284)

Read and agree the terms before continue using Copay

---

views/modals/address-book.html

fix add button from address book

---

js/controllers/receive.js
js/models/Identity.js
js/models/Insight.js
js/models/PublicKeyRing.js
js/models/Wallet.js
test/Identity.js
test/PublicKeyRing.js
test/Wallet.js
test/blockchain.Insight.js

Statements   : 83.06% ( 2918/3513 )
Branches     : 68.44% ( 924/1350 )
Functions    : 80.52% ( 500/621 )
Lines        : 84.2% ( 2888/3430 )

Increase coverage to 83%

---

views/modals/tx-details.html

fix tx details modal

---

js/controllers/receive.js
js/models/Async.js
js/models/Wallet.js
test/network.Async.js
test/unit/controllers/controllersSpec.js

To avoid errors on invalid address

---

js/controllers/receive.js
js/models/Async.js
test/network.Async.js
test/unit/controllers/controllersSpec.js

Statements   : 85.28% ( 2996/3513 )
Branches     : 70.04% ( 947/1352 )
Functions    : 84.03% ( 521/620 )
Lines        : 86.41% ( 2964/3430 )

Increase coverage to 85%

---

js/controllers/createProfile.js

Show errors if occur when creating profile

---

css/src/main.css
views/modals/address-book.html

On Android version prior to 4.2 the popups did not show correctly. This PR solves that error

Fixes error on popups for legacy Android phones

---

views/modals/txp-details.html

Show the broadcast button if txp fails to send

---

cordova/build.sh
js/controllers/receive.js
views/receive.html

Share address button for mobile

---

css/src/main.css
css/src/mobile.css
js/controllers/createProfile.js
js/controllers/home.js
js/services/pinService.js
views/createProfile.html
views/home.html
views/includes/pin-number.html
views/includes/pin.html

New PIN page

---

js/controllers/more.js
js/controllers/profile.js
js/controllers/receive.js
js/init.js

Not pause the device if user share or send the backup by email

---

views/settings.html

Fix external links for mobile

---

js/controllers/send.js
test/unit/controllers/controllersSpec.js

Javascript rounding error. The following operations should be equals:
```
101808500 * 1 / 100000000 = 1.018085
```
But not...
```
101808500 * 0.00000001 = 1.0180850000000001
```

WIP: Fix rounding error in amount field

---

css/src/mobile.css
views/includes/pin-number.html

Skip and Signout with another color
fixes #2370

Added feedback when pressing a number

---

css/src/animation.css
css/src/desktop.css
css/src/main.css
css/src/mobile.css
js/services/notifications.js
package.json
views/create.html
views/createProfile.html
views/home.html
views/import.html
views/importProfile.html
views/includes/notifications.html
views/join.html
views/more.html
views/profile.html
views/settings.html

change styles

---

js/models/Wallet.js
test/HDParams.js
test/Identity.js
test/PrivateKey.js
test/PublicKeyRing.js
test/RateService.js
test/TxProposal.js
test/TxProposals.js
test/Wallet.js
test/blockchain.Insight.js
test/network.Async.js

Statements   : 86.83% ( 3053/3516 )
Branches     : 72.73% ( 984/1353 )
Functions    : 85.48% ( 530/620 )
Lines        : 87.94% ( 3019/3433 )

Increase coverage to 86%

---

css/src/main.css
css/src/mobile.css
js/controllers/sidebar.js
views/copayers.html
views/homeWallet.html
views/includes/copayers.html
views/more.html

New structure

---

views/includes/sidebar-mobile.html

fixes #2358
* Added init() to sidebar-mobile.

Fix mobile: save last focused wallet and update list!

---

index.html
js/controllers/head.js
js/controllers/sidebar.js
views/includes/sidebar-mobile.html
views/profile.html

* Also prevent loading of sidebar controller if "identity" is not initialized.
Fixes part of #2383

Fix gravatar on sidebar

---

js/models/Wallet.js

- fix incomplete wallet's forced sync.

fix incomple fix

---

js/controllers/receive.js

Copy and share address using bip21

---

js/controllers/copayers.js
js/controllers/more.js
views/copayers.html
views/modals/address-book.html
views/modals/paypro.html
views/modals/qr-address.html
views/modals/tx-details.html
views/modals/txp-details.html
views/modals/walletSelection.html
views/more.html
views/receive.html

* Copy and share secret join to complete the ring on mobile devices.
* If Cordova, replace some 'a' elements by 'span' (to avoid active and hover attributes).
* Copy to clipboard Master private key and the secret join string.

More copy and share for mobile

---

css/src/main.css
css/src/mobile.css

Background color for body

---

js/models/Identity.js
js/models/TxProposal.js
test/Identity.js
test/TxProposal.js
test/Wallet.js
test/blockchain.Insight.js
test/network.Async.js

Statements   : 89.33% ( 3139/3514 )
Branches     : 76.79% ( 1039/1353 )
Functions    : 87.88% ( 544/619 )
Lines        : 90.1% ( 3093/3433 )

Increase coverage to 90%

---

js/controllers/homeWallet.js
views/modals/tx-details.html
views/modals/txp-details.html

TXP Modal: Update status when transaction signed/rejected/broadcasted

---

js/models/Wallet.js
views/homeWallet.html

Display unsent transactions on HomeWallet

---

cordova/build.sh
js/controllers/home.js
js/controllers/homeWallet.js
js/controllers/import.js
js/controllers/importProfile.js
js/controllers/send.js
js/models/Wallet.js
views/home.html
views/import.html
views/importProfile.html
views/send.html

* Disable SendForm when sending a transaction.
* Display a native spinner when sending/signing/rejecting a transaction (mobile).
* If transaction could not be broadcasted (1-1) update the balance and show locked funds.

Fixes loading message after press a button

---

js/controllers/more.js

Update tx proposals after change the unit

---

LICENSE
README.md

And also updated copyright year on LICENSE file.

Updated formatting, fixed typos and language flow for README

---

package.json

* New PIN screen.
* AutoUpdate of transaction details if it was signed/rejected or broadcasted.
* Show unsent transactions on Home screen.
* Improves UX responses when pressing a button.
* Minor bug fixes
* Detect device language automatically (only Spanish)

New release v0.9.9

---

po/fr.po

Hi :)
https://github.com/bitpay/copay/issues/2471
Here is the first attempt, I think 90-95% of my translations are fully correct.
The rest may be imprecise, but never wrong.
However, I need the context of 5 strings I didn't translated:
Amount in
Login Required
Scaning for transactions
Skipping fields: {{skipFields}}
Using network:
I will make some corrections in the future if necessary

French Translation

---

public/views/walletHome.html
src/js/controllers/index.js

hide message is onGoing process.

better update order at walletHome

---

bower.json
src/js/controllers/index.js
src/js/services/profileService.js

- use new bwc global paypro verify flag

use new bwc global paypro verify flag

---

src/js/controllers/import.js

Removes unnecessary apply function

---

src/js/controllers/import.js
src/js/controllers/index.js
src/js/services/profileService.js

fix addr at recreate

---

po/ja.po

Added Japanese. Let me know if any new strings.

Added Japanese language strings

---

src/js/controllers/index.js

Set backup flag after import a backup

---

cordova/config.xml

Locking portrait orientation

---

public/views/copayers.html
public/views/create.html
public/views/join.html

fixes https://github.com/bitpay/copay/issues/2561
and fixes https://github.com/bitpay/copay/issues/2553

better wording for wallet invitations

---

public/views/modals/tx-details.html

change view on blockchain button

---

public/views/includes/menu.html
src/js/controllers/index.js
src/js/controllers/send.js
src/js/controllers/walletHome.js

Hiding menu on send.js

---

po/ja.po

Update Japanese strings to match new template.po

---

src/js/controllers/index.js

Update tx history after change unit

---

po/fr.po

Update French strings to match new template.po

---

public/views/walletHome.html
src/css/main.css

Revert "status notifications"

---

Gruntfile.js
bower.json
public/views/includes/menu.html
src/js/controllers/index.js
src/js/init.js
src/js/routes.js

This reverts commit ea7484512f4bca1c91e7b635e5fc11addb49306c.

Revert "rm fastclick"

---

public/index.html
public/views/history.html
public/views/includes/clientError.html
public/views/includes/offline.html
public/views/walletHome.html
src/css/main.css
src/js/controllers/index.js

Revert "WIP: Bug/notif2"

---

public/views/join.html
public/views/walletHome.html
src/js/controllers/join.js
src/js/services/profileService.js

fix error handler for join

---

src/css/mobile.css

Removes background when opening sidebar to optimize the slider animation

---

cordova/build.sh
cordova/config.xml
public/views/includes/version.html
public/views/preferences.html
public/views/preferencesAbout.html
public/views/preferencesLogs.html
src/css/main.css
src/js/controllers/index.js
src/js/controllers/preferencesAbout.js
src/js/controllers/preferencesAltCurrency.js
src/js/controllers/preferencesBwsUrl.js
src/js/controllers/preferencesColor.js
src/js/controllers/preferencesLogs.js
src/js/controllers/preferencesUnit.js
src/js/routes.js
src/js/services/configService.js
src/js/services/fileStorage.js
src/js/services/historicLog.js
src/js/services/isChromeApp.js
src/js/services/localStorage.js
src/js/services/logHeader.js
src/js/services/profileService.js
src/js/services/storageService.js

Replaces localStorage with device's file storage (on Android / iOS mobile devices)

Cordova file api 

---

src/css/main.css
src/css/mobile.css

* Improves animation for mobile

Fix scroll after animation. Removes unused attributes

---

bower.json
public/views/includes/topbar.html
src/css/mobile.css
src/js/app.js
src/js/controllers/index.js
src/js/controllers/walletHome.js
src/js/directives/directives.js
src/js/directives/ngSwipe.js
src/js/init.js
src/js/services/go.js
src/js/services/swipe.js

- removes ngTouch
- use custom swipe gesture
- add touchdown to menu buttom

add custom swipe

---

Gruntfile.js
bower.json
package.json
public/index.html
public/views/importLegacy.html
public/views/includes/topbar.html
public/views/includes/transaction.html
public/views/modals/copayers.html
public/views/modals/paypro.html
public/views/modals/scanner.html
public/views/modals/tx-details.html
public/views/modals/txp-details.html
public/views/walletHome.html
src/css/mobile.css
src/js/app.js
src/js/controllers/index.js
src/js/controllers/walletHome.js
src/js/routes.js
src/js/services/txStatus.js

* Slide up/down animation for modals
* Fix margin bottom
* Increases limit of characters on textarea
* Adds "updating balance" message if updatingStatus is "updating transaction proposal"
* Fixes #2614

Modals animation (slide up/down)

---

public/views/modals/paypro.html

- add missing fields to paypro modal.

fix paypro info

---

public/views/includes/topbar.html
public/views/preferences.html
public/views/preferencesAlias.html
src/js/controllers/backup.js
src/js/controllers/index.js
src/js/controllers/paymentUri.js
src/js/controllers/preferencesAlias.js
src/js/controllers/preferencesDelete.js
src/js/controllers/sidebar.js
src/js/routes.js
src/js/services/backupService.js
src/js/services/notificationsService.js

Support wallet aliases

---

src/js/routes.js

* Disable animation for `cordova` URL. Fixes #2731
* Disable animation for `uri-payment` URL

Update wallet after resume app. Fix payment-intent

---

src/js/services/profileService.js
src/js/services/storageService.js

Fixes https://github.com/bitpay/copay/issues/2735

fix delete wallet in fileStorage

---

src/js/routes.js
src/js/services/go.js

Closes #https://github.com/bitpay/copay/issues/2742

fix setTab after some animations

---

public/views/modals/tx-details.html
public/views/modals/tx-status.html
public/views/modals/txp-details.html
public/views/walletHome.html
src/js/controllers/index.js
src/js/controllers/walletHome.js
src/js/services/notificationsService.js
src/js/services/txStatus.js
util/swipeWallet.js

-  Unifies texts: sign -> approve, spend proposal -> payment proposal,   transaction -> payment.
- Fixes #2733

unify strings to "payment". Add retry on balance update

---

public/views/modals/paypro.html
src/css/main.css

* Common look&feel
* Trying to fix #2748

Fix paypro modal

---

public/views/create.html
public/views/includes/sidebar.html
public/views/walletHome.html
src/css/main.css
src/css/mobile.css
src/js/controllers/create.js

Feat/ux wallets 1-1

---

po/es.po
po/template.pot
public/views/import.html

* Many strings changed
* POT template updated

Updates POT for translation

---

po/es.po
po/fr.po
po/template.pot
public/views/preferencesAlias.html

Also need the context for "Alias for" and "Pay to"

Updated French + typo 

---

public/views/create.html
public/views/import.html
public/views/importLegacy.html
public/views/join.html
src/css/main.css
src/css/mobile.css
src/js/init.js

* Disable button after pressing (on creating, joining and importing)
* Fixes duplicated forms on importLegacy html
* Completed missing buttons style
* Removes unused styles
* Fixes "back button" action for android devices with physical back button
* Disable open/copy link when pressing it for long time (iOS)

Mobile issues

---

bower.json
src/js/controllers/walletHome.js

depends on https://github.com/bitpay/bitcore-wallet-client/pull/79

Show memo in log

---

src/js/controllers/walletHome.js

fixes https://github.com/bitpay/copay/issues/2774

fix refresh on reject

---

public/views/walletHome.html

Fixes https://github.com/bitpay/copay/issues/2795

fix icon letter

---

public/views/walletHome.html
src/js/controllers/index.js
src/js/controllers/walletHome.js

Fixes https://github.com/bitpay/copay/issues/2788

better handling of sign/broadcast fail

---

public/views/add.html

Fixes string add wallet

---

appstore_en

We had to do a full update of the description. Ping @Kirvx @dabura667

Updates description for stores

---

po/fr.po

It is a good simplification that I consider quite interesting for simplicity with faster reading.
Also, note that 'Import legacy wallet' from 
https://github.com/bitpay/copay/blob/master/public/views/importLegacy.html
is nowhere in template.pot

Another french update (sorry (ʘ‿ʘ) )

---

appstore_pt-BR
po/pt_BR.po

The Portuguese Brazilian translation

Portuguese Brazilian translation

---

src/js/controllers/walletHome.js

Copy bitcoin addr without bitcoin:

---

src/js/controllers/index.js
src/js/services/profileService.js
src/js/services/storageService.js

Clean last address and scann all addresses

---

public/views/disclaimer.html
public/views/preferencesAbout.html
public/views/walletHome.html
src/css/main.css
src/css/mobile.css
src/js/controllers/preferencesBwsUrl.js
src/js/routes.js
src/js/services/applicationService.js
src/js/services/profileService.js
src/js/services/storageService.js

Copay: Terms of Use in APP

---

src/js/controllers/walletHome.js
src/js/services/profileService.js

Fixes message error when password incorrect

---

bower.json
public/views/modals/txp-details.html
public/views/preferences.html
public/views/preferencesFee.html
public/views/walletHome.html
src/css/main.css
src/js/controllers/index.js
src/js/controllers/preferences.js
src/js/controllers/preferencesFee.js
src/js/controllers/walletHome.js
src/js/routes.js

- Allows send all available funds, with a single click
- Allows to configure the fee for outgoing transactions (Priority / Normal / Economy), values suggested by @dabura667 
(needs new BWS api)

Feature: send all and fee customization.

---

public/views/modals/wallets.html
public/views/paymentUri.html
public/views/walletHome.html
src/css/mobile.css
src/js/controllers/index.js
src/js/controllers/paymentUri.js
src/js/controllers/walletHome.js
src/js/init.js
src/js/services/addressService.js
src/js/services/profileService.js

Transfer fund between wallets using a popup in `send`

Send wallet

---

public/views/walletHome.html

fix style on tap button

---

src/js/controllers/walletHome.js

Signed-off-by: Matias Alejo Garcia <ematiu@gmail.com>
Fixes: https://github.com/bitpay/copay/issues/2924

skip confirm dialog on chromeapp

---

Gruntfile.js

Signed-off-by: Matias Alejo Garcia <ematiu@gmail.com>
Small fix in `grunt desktop` target.

add -megabytes options to hdiutil

---

public/views/disclaimer.html

fix disclaimer style

---

src/js/controllers/index.js

- fix remoteSave when there are unregistered wallets on the list.

fix save-remote with unregisters wallets

---

public/views/walletHome.html
src/js/controllers/index.js
src/js/controllers/walletHome.js

History: export .csv file (compatibility with LibraTax)

---

src/js/controllers/index.js

fixes https://github.com/bitpay/copay/issues/2905

fix tx history refresh

---

public/views/walletHome.html
src/js/controllers/index.js

* Fixes some differences between ChromeApp and Node-Webkit (Desktop)

Fix saving .csv file in Node-Webkit

---

public/views/walletHome.html
src/js/controllers/index.js

Updates getting history to new bws limit

---

src/js/controllers/index.js

fixes https://github.com/bitpay/copay/issues/2986

fix disabling email

---

src/js/controllers/preferencesDelete.js

Show alias in the notification after delete the wallet

---

public/views/modals/tx-details.html
public/views/walletHome.html

related to https://github.com/bitpay/bitcore-wallet-service/pull/282
handles better `invalid` txs in history.

handles invalid txs in history

---

public/views/disclaimer.html

Fixes copay logo on disclaimer for Android < 4.2

---

src/js/controllers/walletHome.js

fixes https://github.com/bitpay/copay/issues/2766

message on bad qr scanning

---

po/ja.po
po/template.pot
public/views/backup.html
public/views/modals/tx-details.html

Fixed Japanese and English

---

src/js/controllers/preferencesColor.js

Feel free to merge or not. I am not a really a color person :)

Added red as a wallet color option, issue: #3022

---

public/views/modals/customized-amount.html
public/views/walletHome.html
src/js/controllers/walletHome.js
src/js/directives/directives.js

Supports commas on amount input

---

src/js/services/txStatus.js

This way addons may customize tx status view.
[Example](https://github.com/troggy/copay-colored-coins-plugin/commit/a6793b1b262c867e3a66fa63e7e3dd5026ea9cd5)

Allow to provide custom templateUrl to txStatus

---

public/views/modals/tx-details.html
src/js/controllers/index.js

receiver seeing change address output of sender, and outputs to other recipients

txhistory of received payments show non-receiver outputs

---

bower.json
i18n/po/template.pot
public/views/backup.html
public/views/create.html
public/views/includes/output.html
public/views/join.html
public/views/modals/txp-details.html
public/views/preferences.html
public/views/preferencesFee.html
public/views/walletHome.html
src/js/controllers/index.js
src/js/controllers/preferences.js
src/js/controllers/walletHome.js
src/js/services/feeService.js

Advanced send options

---

i18n/docs/updateinfo_en.txt
i18n/po/template.pot

If there are any other bullet point you would like, please let me know.
Once it is merged I will push to crowdin.

Update appstore text for next release

---

bower.json
public/views/modals/txp-details.html
src/js/controllers/walletHome.js

Display if has unconfirmed inputs

---

public/views/includes/output.html
public/views/includes/transaction.html
public/views/modals/tx-details.html
public/views/modals/txp-details.html
public/views/walletHome.html
src/js/controllers/index.js
src/js/controllers/walletHome.js
src/js/services/utilService.js

Fixes txp modals for single outputs

---

public/views/disclaimer.html
public/views/includes/sidebar.html
public/views/preferencesAbout.html
public/views/unsupported.html
src/css/main.css
src/js/directives/directives.js

.. so that logo can be overriden in addon.
[Example](https://github.com/Colored-Coins/Colored-coins-add-on-for-Copay/commit/b30c70a4488b41d8410959855f166bf51d7eccf8#diff-ce1d47e10e38c9c3cede9d6c803b88d3R96)

Add logo directive

---

public/views/includes/available-balance.html
public/views/walletHome.html
src/js/directives/directives.js

..so it can be decorated by addon.
[Example showing funds locked by colored utxos](https://github.com/Colored-Coins/Colored-coins-add-on-for-Copay/commit/4c28b113a5b0c1161d96622112d9d02096774f98#diff-ce1d47e10e38c9c3cede9d6c803b88d3R50)

Create availableBalance directive for Send screen

---

public/views/includes/menu-item.html
public/views/includes/menu.html
src/js/controllers/index.js

Fix empty space in menu bar with one addon

---

bower.json
src/js/controllers/walletHome.js

* Also updates animated.css
* fixes #3138

Disables animation on chromeapp

---

public/views/includes/menu-item.html
src/js/controllers/index.js

This will allow viewless addons or addons having separate view, not only tab view in home contoller.
[Example](https://github.com/troggy/copay-colored-coins-plugin/commit/179cc7b4f0365743ad97a5f6e66c092d91a9e018#diff-ce1d47e10e38c9c3cede9d6c803b88d3R24)

Allow addon menu items to run arbitrary code on click

---

public/views/buyGlidera.html
public/views/glidera.html
public/views/includes/sidebar.html
public/views/preferences.html
public/views/sellGlidera.html
public/views/walletHome.html
src/js/controllers/buyGlidera.js
src/js/controllers/glidera.js
src/js/controllers/glideraUri.js
src/js/controllers/index.js
src/js/controllers/preferences.js
src/js/controllers/sellGlidera.js
src/js/services/configService.js

* Switch for enable/disable Glidera link in preferences
* Switch for testnet/livenet in preferences

Moves Glidera link to sidebar

---

public/views/preferencesAdvanced.html
public/views/preferencesInformation.html
src/js/controllers/preferencesInformation.js
src/js/routes.js

Adds Advanced -> Wallet Information
shows general Wallet information, xPubKeys, Balance by Address, and wallet main addresses.
fixes https://github.com/bitpay/copay/issues/3122
fixes https://github.com/bitpay/copay/issues/3119
related to: https://github.com/bitpay/copay/issues/3109

add "advanced > wallet information"

---

public/views/disclaimer.html
src/js/controllers/disclaimer.js

Before: http://imgur.com/BBQgg1I
After: http://imgur.com/DXZT3Wv
And first screen OK: http://imgur.com/ThSYTCo
Tell me if it's not correct, I'm a noob.

[Bug] Display problem of topbar.html in disclaimer.html

---

public/views/backup.html
public/views/modals/paypro.html
public/views/preferences.html
public/views/walletHome.html
src/css/main.css
src/js/controllers/backup.js
src/js/controllers/import.js
src/js/services/profileService.js

- adds normalization of seeds,
- better JA support (displaying the seed)
- removes preDerivation, since it is not longer used.

add normalization of seeds, better JA support

---

public/views/importLegacy.html
public/views/preferencesInformation.html
src/js/controllers/preferencesLanguage.js
src/js/services/profileService.js

Translate default wallet name

---

i18n/po/template.pot
public/views/disclaimer.html
src/js/controllers/disclaimer.js

This should make it so that the TM will save, and we won't have to try to dig up old po files to copy.

Fix disclaimer

---

i18n/docs/appstore_en.txt
i18n/docs/updateinfo_en.txt

Copay release information

---

public/views/modals/tx-details.html
src/js/controllers/index.js

refresh tx history on new blocks only if there are tx with less that 6 confirmations

better history refresh logic

---

public/views/backup.html

This is not secure. I believe we should encourage writing the phrase down by hand onto a physical medium.
Therefore I think we should leave the phrase as not copyable.

Disable Copying BIP39 phrase + facilitate copying on testnet

---

src/js/services/glideraService.js

Glidera: update credentials

---

public/views/includes/password.html

adding autofocus to password input in Resquest Password for Spending Funds modal

---

cordova/build.sh
src/js/services/profileService.js

Fixes https://github.com/bitpay/copay/issues/3114

use specific version of email-composer to prevent Identity permisions

---

public/views/export.html

fixes https://github.com/bitpay/copay/pull/3229

fix export text

---

src/js/controllers/index.js

fix time message in proposal transaction

---

public/views/backup.html
src/js/controllers/backup.js
src/js/services/bwsError.js

ask for password when private key is encrypted when showing mnemonics.

fix mnemonics with priv key is encrypted

---

public/views/includes/menu.html
public/views/walletHome.html

This reverts commit afe6c1039c88fa6b6b42f861b11add23432bd7f6.

Revert "Hide menu if wallet is not authorized"

---

src/js/controllers/walletHome.js

Adds non-backwards compatibility uri for payment protocol

---

public/views/backup.html

Fixing the wording on the backup page

---

public/views/includes/password.html
src/js/controllers/password.js

autofocus changes

---

src/js/controllers/walletHome.js
src/js/init.js
src/js/routes.js

Handle back-button on Android devices

---

src/css/mobile.css
src/js/controllers/buyGlidera.js
src/js/controllers/copayers.js
src/js/controllers/preferencesDelete.js
src/js/controllers/preferencesGlidera.js
src/js/controllers/sellGlidera.js
src/js/controllers/topbar.js
src/js/controllers/walletHome.js
src/js/routes.js
src/js/services/animationService.js
src/js/services/txStatus.js

* Refactory animationService for all animation elements
* Disables animation for chromeApp and desktop versions
* Speed up closing modals (fixes #3265)

Ref animations. Disabled for desktop

---

Gruntfile.js
public/views/create.html
public/views/import.html
public/views/join.html
src/js/controllers/create.js
src/js/controllers/import.js
src/js/controllers/join.js
src/js/controllers/walletHome.js
src/js/services/bwsError.js
src/js/services/profileService.js
src/js/services/trezor.js
src/js/trezor.js

Trezor Support

---

public/views/glidera.html
public/views/includes/sidebar.html
public/views/modals/glidera-tx-details.html
public/views/modals/glidera-wallets.html
public/views/preferences.html
public/views/sellGlidera.html
src/js/controllers/buyGlidera.js
src/js/controllers/glidera.js
src/js/controllers/index.js
src/js/controllers/sellGlidera.js

Adds btc values. Adds disclosure. Fix modals. Removes sandbox

---

public/views/create.html
public/views/export.html
public/views/import.html
public/views/join.html
public/views/preferencesLogs.html
src/js/controllers/export.js
src/js/controllers/import.js
src/js/controllers/index.js
src/js/controllers/preferencesBwsUrl.js
src/js/controllers/preferencesLogs.js

Disables TREZOR integration until a workaround to make TREZOR Connect API with Chrome Apps is found.

disables TREZOR

---

public/views/includes/menu.html

Just hide menu if wallet is not authorized

---

src/js/controllers/paperWallet.js

Revert "improve transaction method"

---

bower.json

Needs: https://github.com/bitpay/angular-bitcore-wallet-client/pull/51

bitcore -> bitcore-lib

---

src/js/directives/directives.js

change png for svg

---

cordova/android/project.properties
cordova/build.sh

Note: please, upgrade to the latest version of Cordova

Support Cordova 5.3.3

---

public/views/modals/txp-details.html

fix text centered

---

public/views/create.html
public/views/import.html
public/views/join.html

Manage wallet

---

src/js/services/profileService.js

fixes https://github.com/bitpay/copay/issues/3333

fixes callback

---

public/views/create.html
public/views/import.html
src/css/mobile.css

fix tabs on manage wallet

---

bower.json
src/js/services/profileService.js

Requires https://github.com/bitpay/bitcore-wallet-client/pull/160

All seed* and import* methods working with account 0

---

public/views/modals/destination-address.html
public/views/walletHome.html

* Disables text selection (for addresses) on the history
* Differentiate address/contacts and notes
* Fix styling "Cancel" button

Minor address book issues

---

src/js/directives/qrScanner.js

Fix: Close/stop camera on linux

---

public/views/walletHome.html
src/js/controllers/index.js

initial transaction message in history page

---

public/views/modals/tx-details.html

change tx-details time format

---

src/js/init.js

Fixes the "resume" event on mobile

---

src/js/controllers/index.js
src/js/controllers/walletHome.js

* Optimize the reading from filesystem.

Addressbook variable is updated only if it is modified

---

public/views/preferencesBwsUrl.html
src/js/controllers/preferencesBwsUrl.js

adding reset to default url button

---

src/js/init.js

Fix resume event on mobile

---

src/js/controllers/glidera.js
src/js/controllers/glideraUri.js
src/js/controllers/index.js
src/js/services/configService.js

* Improves implementation to use only "Livenet"

Fix Glidera OAuth if any wallet "testnet" is active

---

src/js/controllers/preferencesDelete.js
src/js/services/profileService.js
src/js/services/storageService.js

* Also removes the lastAddress and backupFlag.

Ref delete wallet

---

src/js/services/profileService.js

Reverts bitpay/copay#3413
Already fixed on #3408

Revert 95f3adf505a7774286c7fc7596cb2367e1db343a

---

bower.json
src/js/services/addressService.js
src/js/services/bwsError.js

Note: Require latest version of BWS

Adds limit to create addresses

---

public/index.html
public/views/create.html
public/views/join.html
src/js/controllers/index.js
src/js/controllers/join.js

- fixes refresh of status bar on mobile devices
- better 'connecting to trezor' message in create/join
- use text input in join (as in create)

fix join message

---

public/views/export.html
src/js/controllers/export.js
src/js/services/backupService.js
src/js/services/profileService.js

Incluiding address book and transaction history cache in export file

---

public/views/import.html

fix autocapitalize on import wallet seed backup

---

src/js/controllers/create.js
src/js/controllers/index.js
src/js/controllers/join.js
src/js/services/profileService.js

Fixes: https://github.com/bitpay/copay/issues/3460

refactor scan after importing a wallet

---

public/views/modals/destination-address.html

fix design on addressbook add page

---

public/views/walletHome.html
src/css/main.css

Revert "fix style on history sync"

---

public/views/walletHome.html
src/css/main.css

fix style on history sync

---

src/js/controllers/index.js

CSV: Adds creator and copayers for multisig

---

public/views/import.html

"Word" is a bit confusing and redundant here. "Phrase" or "Mnemonic" might be better choices.

Clarify language

---

src/js/controllers/index.js

Fixes alert popup duplicated

---

src/js/services/profileService.js

Fix avatar default background color

---

public/views/create.html
public/views/join.html
public/views/termOfUse.html
src/css/main.css
src/js/controllers/termOfUse.js

changes in global settings terms view and taking out auto capitalize in join and create view when writting wallet seeds and passphrase

Global settings terms of use

---

src/js/controllers/paymentUri.js
src/js/controllers/walletHome.js

* Go to `send` after select a wallet

Fix payment URI

---

src/js/init.js
src/js/routes.js

Second back button press to exit

---

Gruntfile.js
src/js/controllers/index.js

also 
fixes: https://github.com/bitpay/copay/issues/3115

fix backup flag from server

---

cordova/config.xml
cordova/ios/Copay-Info.plist
cordova/wp/Package.appxmanifest
cordova/wp/Properties/WMAppManifest.xml
package.json
webkitbuilds/.desktop
webkitbuilds/setup-win.iss

Fixes handling multiple outputs

New release v1.6.3

---

public/views/disclaimer.html
src/css/main.css

fix button on small device

---

public/views/translators.html
src/js/services/uxLanguage.js

* Also removes uncompleted languages

Set only available languages

---

cordova/build.sh

* Get the latest release on NPM (not `master`). Fixes #3763

Fix url-scheme plugin

---

src/js/routes.js
src/js/services/fileStorage.js

fixes https://github.com/bitpay/copay/issues/3726

do not print read values from storage in mobile

---

public/views/modals/txp-details.html

Removes unsent TX from personal wallets

---

src/js/services/txSignService.js

Show popup before the spinner on mobile

---

src/js/controllers/index.js
src/js/controllers/preferencesGlobal.js
src/js/services/profileService.js
src/js/services/pushNotificationsService.js

use detect language in push notifications, update remote preferences when creating new profile

Use device language in push notifications and service refactor 

---

public/views/walletHome.html

fix wording

---

public/views/copayers.html
public/views/modals/confirmation.html
public/views/walletHome.html
src/css/main.css
src/css/mobile.css
src/js/controllers/copayers.js

* Show wallet type
* Fix share button for mobile
* Styling button

Ref. Waiting for Copayers

---

src/js/controllers/paperWallet.js

fix prefix check

---

public/views/walletHome.html

UI refactor

---

public/views/modals/destination-address.html
public/views/walletHome.html
src/css/main.css
src/css/mobile.css
src/js/controllers/walletHome.js

Use cordova-plugin to paste from clipboard on mobile

---

src/js/controllers/create.js

Replaces form values by the scope

---

Gruntfile.js
bower.json
public/views/preferencesHistory.html
public/views/walletHome.html
src/js/app.js
src/js/controllers/index.js

Generate CSV using a new plugin

---

Gruntfile.js
bower.json
public/index.html
public/views/includes/sidebar.html
public/views/includes/topbar.html
public/views/includes/transaction.html
public/views/includes/tx-details.html
public/views/modals/destination-address.html
public/views/walletHome.html
src/css/main.css
src/css/mobile.css
src/js/controllers/index.js
src/js/controllers/tx.js
src/js/controllers/walletHome.js
src/js/directives/directives.js
src/js/routes.js

Also removes the `fastClick` angular-plugin

Improvement open TX modal

---

public/views/includes/password.html
src/js/controllers/password.js

Enhanced  response time when pressing Set/Ok with password enabled

---

src/js/controllers/index.js

Increment history downloading page size

increment history page size

---

public/views/preferencesHistory.html

remove blank space without export to file link on mobile

---

public/views/modals/txp-details.html
public/views/walletHome.html
src/js/controllers/walletHome.js

Expiry time - paypro

---

bower.json
public/views/includes/walletInfo.html
public/views/walletHome.html
src/js/controllers/index.js
src/js/controllers/walletHome.js
src/js/services/go.js
src/js/services/txFormatService.js

- Completely delete index and walletHome scopes when a new wallet is focused
- Show tx history while syncing

Ref: History update and walletHome/Index reset when chaning wallet

---

public/views/disclaimer.html
public/views/includes/sidebar.html
src/js/controllers/create.js
src/js/controllers/disclaimer.js
src/js/controllers/import.js
src/js/controllers/index.js
src/js/controllers/join.js
src/js/controllers/sidebar.js
src/js/services/profileService.js
src/js/services/pushNotificationsService.js

- refactor disclaimer handling
- fix CRITICAL timing issue when creating a new wallet, that makes that the new wallet is not inmediately save in certain devices (this only happends in MASTER not in the deployed versions)

refactor disclaimer handling

---

public/views/backup.html
src/js/controllers/backup.js

Fix display wallet name on backup page

---

public/views/walletHome.html
src/js/controllers/index.js
src/js/controllers/walletHome.js
src/js/services/profileService.js

fix send payments to destination address without backup

---

public/views/walletHome.html
src/js/controllers/index.js

- highlight new downloaded TXs and soft confirmed TXs.

highlight recent TXs

---

src/js/controllers/walletHome.js

Do not use paste to clipboard if there is a new address in the input

---

src/js/services/feeService.js
src/js/services/txService.js

Fail if fee level cannot be get from BWS (do not use Copay's default)

fail if fee level cannot be get

---

src/js/controllers/paymentUri.js

Fixes select wallet using URI payment

---

src/js/controllers/walletHome.js

Fix prevent submit

---

src/js/controllers/copayers.js
src/js/controllers/disclaimer.js
src/js/controllers/index.js
src/js/controllers/walletHome.js
src/js/routes.js
src/js/services/go.js
src/js/services/profileService.js

Fixes https://github.com/bitpay/copay/issues/3973
and fixe refresh until it change for payment proposals.

fixes SHARED Wallet status, and refresh until it changes

---

src/js/services/trezor.js

fixes https://github.com/bitpay/copay/issues/3976

fix trezor

---

public/views/copayers.html

Fix scrolling in shared secret page

---

public/views/walletHome.html
src/js/controllers/walletHome.js

Revert "fix remaining time paypro"

---

public/views/modals/destination-address.html
public/views/walletHome.html
src/css/main.css
src/js/controllers/index.js
src/js/controllers/walletHome.js
src/js/services/profileService.js

Display backup message in addressbook

---

cordova/config.xml
cordova/ios/Copay-Info.plist
cordova/wp/Package.appxmanifest
cordova/wp/Properties/WMAppManifest.xml
package.json
webkitbuilds/.desktop
webkitbuilds/setup-win.iss

* updates provisioning profile  (IOS)

New release v1.9.6

---

src/js/services/storageService.js

Revert "changing name of localstorage push notifications token value"

---

cordova/config.xml
cordova/ios/Copay-Info.plist
cordova/wp/Package.appxmanifest
cordova/wp/Properties/WMAppManifest.xml
package.json
webkitbuilds/.desktop
webkitbuilds/setup-win.iss

* More storage for big wallet's history

New release v1.9.7

---

public/views/includes/confirm-tx.html
src/css/main.css
src/js/controllers/confirmTx.js
src/js/controllers/tx.js

Adds more fee data to the confirmation popup

---

public/views/includes/menu.html
src/js/controllers/index.js

Menu always has 3 items, so no need in complex markup

Cleanup bottom menu html

---

cordova/build.sh
public/views/preferencesGlobal.html
src/js/controllers/preferencesGlobal.js

If pn was not enabled by user, do not show pn switch in IOS

---

public/views/walletHome.html
src/js/controllers/index.js
src/js/controllers/preferencesDelete.js

Fix delete last wallet

---

package.json
public/views/includes/sidebar.html
public/views/preferencesFee.html
public/views/preferencesGlobal.html
src/js/controllers/index.js
src/js/controllers/preferencesGlobal.js
src/js/routes.js
src/js/services/feeService.js

Fix fee levels when there is no wallet and hide Glidera if wallet is not complete

---

package.json
public/views/walletHome.html
src/css/main.css
src/js/controllers/walletHome.js

This work with:
https://github.com/bitpay/bitcore-wallet-client/pull/226
https://github.com/bitpay/bitcore-wallet-service/pull/483

replace send all to send max

---

i18n/po/fr.po

Confirmations en attente -> Confirmation en attente
Sorry

Tiny french correction from Crowdin

---

Makefile

add OSX sign target

---

src/js/controllers/preferences.js

fix scan fingerprint value

---

public/views/includes/password.html

Tested on IOs, Android, Desktop, ChromeApp, Browser.

remove fastclick from cancel password popup

---

src/js/controllers/walletHome.js

Fixes https://github.com/bitpay/copay/issues/4096

Fix float point

---

cordova/build.sh
src/js/directives/qrScanner.js

Fix camera permissions for Android 6

---

public/views/modals/destination-address.html
src/js/controllers/walletHome.js

fix empty contact list in addressbook

---

Gruntfile.js
webkitbuilds/build-osx.sh

Fix OSX Code signing
(following https://github.com/nwjs/nw.js/wiki/MAS:-Signing-the-app )

Fix osx signing in script

---

src/js/controllers/index.js
src/js/controllers/walletHome.js

WIP : vanillaScope is filtering out falsey properties 

---

package.json
src/js/controllers/walletHome.js
src/js/services/txService.js

Fixes https://github.com/bitpay/copay/issues/4150

Fix send max opts

---

Makefile
config-templates/config.xml
cordova/android/project.properties
cordova/build.sh
cordova/config.xml
cordova/wp/Package.appxmanifest
cordova/wp/Properties/WMAppManifest.xml
package.json
public/views/preferencesInformation.html
src/js/controllers/import.js
src/js/controllers/index.js
src/js/controllers/preferencesInformation.js
src/js/controllers/walletHome.js
src/js/services/profileService.js
src/js/services/txService.js
webkitbuilds/.desktop
webkitbuilds/setup-win.iss

- Bump to version 1.12.3
- show source error after signature fail.

fix logs in txservice, add logs to bwc

---

public/views/includes/sidebar.html

[Idea] Shorten sentence from sidebar: buy & sell

---

cordova/build.sh

fix : Tap on notification IOS

---

package.json
src/js/services/profileService.js

Reverts bitpay/copay#4184

---

src/js/controllers/import.js
src/js/services/derivationPathHelper.js
src/js/services/profileService.js

Fixes import a xPriv directly
(typing xprivxxxxxx ) at mnemonic input
Only supports livenet.

fix import from xPriv

---

public/views/backup.html
public/views/create.html
public/views/export.html
public/views/import.html
public/views/importLegacy.html
public/views/includes/password.html
public/views/join.html
public/views/paperWallet.html
public/views/preferences.html
public/views/preferencesDeleteWords.html
src/js/controllers/create.js
src/js/controllers/import.js
src/js/controllers/join.js
src/js/controllers/password.js
src/js/services/bwsError.js
src/js/services/profileService.js

@matiu :+1: 
"Password for the recovery phrase" can be replaced with just "Password" in all cases given that Password is now Spending Password.

Change Seed to Recovery Phrase, and more.

---

public/views/export.html
public/views/import.html
public/views/importLegacy.html

Fix incorrect use of 'spending password' in import/export views

---

angular-bitcore-wallet-client/index.js
package.json
src/js/controllers/backup.js
src/js/controllers/create.js
src/js/controllers/index.js
src/js/controllers/join.js
src/js/services/go.js
src/js/services/profileService.js
test/controllers/backup.test.js
test/controllers/copayers.test.js
test/controllers/create.test.js
test/controllers/import.test.js
test/controllers/index.test.js
test/controllers/join.test.js
test/controllers/walletHome.test.js
test/fixtures.js
test/helpers.js
test/karma.conf.js
test/profiles.js
test/walletService.test.js

add Controller test templates.

Add controller tests

---

src/js/services/profileService.js

Fixes https://github.com/bitpay/copay/issues/4262

Fix deleting wallet

---

public/views/backup.html
src/js/controllers/backup.js

* Remove $document
* Addapt to angular

Fix backup controller

---

src/js/services/notifications.js

mobile should be exclude

---

src/js/services/feeService.js

adding super economy fee option

---

cordova/build.sh
src/js/init.js
src/js/services/fingerprintService.js

fixes https://github.com/bitpay/copay/issues/3867

fingerprint for Android 6.0+

---

public/views/create.html
public/views/includes/walletInfo.html
public/views/walletHome.html
src/js/controllers/create.js
src/js/controllers/index.js
src/js/controllers/sidebar.js
src/js/services/profileService.js
test/controllers/create.test.js

allow single address wallet for auditable reasons

---

public/views/create.html
public/views/includes/note.html
src/css/ionic-migration.css
src/js/controllers/create.js

Fixes https://github.com/bitpay/copay/issues/4304
No translations files updated

Fix ionic UI bugs

---

public/views/glidera.html

Adds new states on description to buy/sell throught Glidera

---

public/views/copayers.html

Fixes https://github.com/bitpay/copay/issues/2633

Hide secret on mobile

---

public/views/preferencesFee.html
src/css/ionic-migration.css
src/js/controllers/preferencesFee.js

Fixes https://github.com/bitpay/copay/issues/4317 
Fixes https://github.com/bitpay/copay/issues/4318

Bug fee selection on mobile

---

src/js/controllers/backup.js

Improves performance for wallets without a passphrase. Related to #4325.

Optimize backup verification

---

public/views/walletHome.html
src/js/controllers/walletHome.js

Revert "Click scrolls to focused inputs"

---

public/views/backup.html
src/js/controllers/backup.js

- Add spinner
- Prevent tapping to remove selected words
Fixes https://github.com/bitpay/copay/issues/4325

Add spinner - backup flow

---

src/js/controllers/disclaimer.js
src/js/services/platformInfo.js
src/js/services/profileService.js

Removes the last (xxx) number on the user agent.

fix key derivation cache in IOS

---

cordova/build.sh

update cordova file plugin

---

public/views/preferencesAltCurrency.html
src/js/controllers/preferencesAltCurrency.js

Improve speed currency list

---

public/views/preferencesDeleteWords.html

Add margins

---

i18n/po/fr.po
i18n/po/template.pot

https://github.com/bitpay/copay/pull/4360
For french:
Enregistrer -> Valider **(shorter)**
certain -> certain(e) -> **(female gender in brackets)**

Update template.pot and fr.po

---

src/js/controllers/modals/txpDetails.js

fix proposal update

---

public/views/export.html
public/views/preferences.html
public/views/preferencesAlias.html
public/views/preferencesHistory.html
public/views/termOfUse.html
src/js/controllers/index.js

fix untranslated titles

---

public/views/create.html
public/views/import.html
public/views/join.html
src/js/controllers/create.js
src/js/controllers/import.js
src/js/controllers/join.js

Fixes https://github.com/bitpay/copay/issues/4336
Fixes https://github.com/bitpay/copay/issues/4328

Fix IOs white page

---

public/views/preferencesLanguage.html
public/views/translators.html

https://github.com/bitpay/copay/issues/4362
https://github.com/bitpay/copay/issues/4287

Update transalators credits

---

public/views/modals/addressbook.html
src/js/controllers/modals/addressbook.js

Fixes https://github.com/bitpay/copay/issues/4363

Edit button - Addressbook

---

src/js/controllers/preferences.js
src/js/models/profile.js
src/js/services/profileService.js
src/js/services/storageService.js

- fix saving the profile, when encryption settings changed.

fixes credentials storage

---

src/js/services/onGoingProcess.js

add spinner to ongoing notifications on desktop /  chrome

add spinner to ongoing notifications

---

src/js/services/fingerprintService.js

Fixes https://github.com/bitpay/copay/issues/4388

fixes Android fingerprint detection

---

public/views/import.html
src/js/controllers/import.js
src/js/services/derivationPathHelper.js

add a testnet switch when importing mnemonics

---

public/views/modals/addressbook.html
public/views/modals/coinbase-tx-details.html
public/views/modals/customized-amount.html
public/views/modals/glidera-tx-details.html
public/views/modals/paypro.html
public/views/modals/search.html
public/views/modals/tx-details.html
public/views/modals/txp-details.html
public/views/modals/wallets.html
src/css/ionic-migration.css
src/sass/main.scss

change all modals nav header with ionic header to fix ios delay

---

src/js/controllers/preferencesFee.js

Fixes https://github.com/bitpay/copay/issues/4318#issuecomment-226260557
* Tested on mobile

Fix display average time and rate fee/kiB

---

public/views/includes/sidebar.html

fix side bar scroll - iphone5s issue

---

public/views/backup.html
public/views/export.html
src/js/controllers/backup.js
src/js/controllers/export.js
src/js/controllers/preferencesDeleteWords.js
test/controllers/backup.test.js

Fixes https://github.com/bitpay/copay/issues/4423
Fixes https://github.com/bitpay/copay/issues/4427

Fingerprint request in export and backup

---

src/js/services/notificationsService.js

internal notification should use default wallet color

---

public/views/includes/password.html
src/js/controllers/index.js

enter key on the keyboard submit the spending password popup

---

Gruntfile.js
bower.json
public/views/modals/scanner.html
public/views/modals/tx-status.html
src/js/app.js
src/js/controllers/buyCoinbase.js
src/js/controllers/buyGlidera.js
src/js/controllers/coinbase.js
src/js/controllers/copayers.js
src/js/controllers/glidera.js
src/js/controllers/join.js
src/js/controllers/modals/scanner.js
src/js/controllers/modals/txStatus.js
src/js/controllers/modals/txpDetails.js
src/js/controllers/paperWallet.js
src/js/controllers/preferencesCoinbase.js
src/js/controllers/preferencesDelete.js
src/js/controllers/preferencesGlidera.js
src/js/controllers/sellCoinbase.js
src/js/controllers/sellGlidera.js
src/js/controllers/walletHome.js
src/js/directives/qrScanner.js
src/js/services/txStatus.js
test/karma.conf.js

remove angular foundation and use only ionic modals

---

public/views/modals/addressbook.html
src/js/controllers/modals/addressbook.js

fix edit/remove button in address book

---

public/views/includes/confirm-tx.html

focus confirm button

---

public/views/paperWallet.html

check if backup has been completed

---

package.json
src/js/controllers/index.js
src/js/controllers/modals/txDetails.js
src/js/controllers/walletHome.js
src/js/services/profileService.js

Fixes #3125 
Requires bitpay/bitcore-wallet-client#293

Show amount & fees with full precision on tx details modal

---

src/js/controllers/sidebar.js
src/js/controllers/walletHome.js

Fix js error when selecting an incomplete wallet

---

Gruntfile.js
public/views/create.html
public/views/import.html
public/views/join.html
public/views/preferences.html
public/views/preferencesGlobal.html
src/css/ionic-migration.css
src/js/controllers/import.js
src/js/routes.js
src/sass/main.scss

Fix horizontal scroll and layout in Android 4.4.2

---

public/views/backup.html

Fixes https://github.com/bitpay/copay/issues/4504

Fix scrolling backup page

---

cordova/build.sh
public/views/walletHome.html
src/css/mobile.css
src/js/controllers/walletHome.js
src/js/routes.js

fix scaling issue in wp8 and show menu bar when backbutton is pressed on send view

---

public/views/receive.html
src/css/mobile.css
src/js/routes.js

Fix scroll over input on iOS

---

src/js/controllers/modals/txpDetails.js
src/js/controllers/paperWallet.js
src/js/controllers/walletHome.js

allow creating transaction proposal without a private key

---

src/js/services/bwsError.js

fixes  #4371 
Copay FAQ https://github.com/bitpay/copay/wiki/COPAY---FAQ#it-shows-amount-below-minimum-allowed-error

Improve error message when user tries to send small amount

---

cordova/build.sh
public/views/export.html
public/views/import.html
src/js/controllers/backup.js
src/js/controllers/export.js
src/js/controllers/import.js
src/js/services/onGoingProcess.js
src/sass/main.scss

* Add tabs in export view (File - QR)
* Add advanced options to display the priv key inclusion
* Add QR scan button at import view (mnemonics)
* Prevent to show scanned data (lock icon)
* Improve error messages
* Warning message if has passphrase
Closes #4320

Export-Import Wallet using QR code

---

public/index.html
public/views/includes/topbar.html
src/js/controllers/disclaimer.js
src/js/controllers/index.js

Fixes https://github.com/bitpay/copay/issues/4529

Do not show the menu in disclaimer view

---

src/js/services/configService.js

Closes https://github.com/bitpay/copay/issues/4510

Set spend unconfirmed funds off by default

---

public/views/modals/addressbook.html
public/views/modals/coinbase-tx-details.html
public/views/modals/customized-amount.html
public/views/modals/glidera-tx-details.html
public/views/modals/paypro.html
public/views/modals/search.html
public/views/modals/tx-details.html
public/views/modals/txp-details.html
public/views/modals/wallets.html
public/views/walletHome.html

removing overflow scrolling from ionic contents

---

i18n/po/template.pot
public/views/buyAndSell.html
public/views/includes/sidebar.html

translate Buy & Sell Bitcoin and update pot template file

---

public/index.html
public/views/includes/topbar.html
src/js/controllers/disclaimer.js
src/js/controllers/index.js

Revert "Do not show the menu in disclaimer view"

---

src/js/controllers/backup.js
src/js/controllers/create.js

enable button when all words are selected

---

i18n/po/template.pot
src/js/controllers/backup.js
src/js/controllers/buyCoinbase.js
src/js/controllers/buyGlidera.js
src/js/controllers/index.js
src/js/controllers/modals/addressbook.js
src/js/controllers/modals/txpDetails.js
src/js/controllers/modals/wallets.js
src/js/controllers/sellCoinbase.js
src/js/controllers/sellGlidera.js
src/js/controllers/walletHome.js
src/js/services/addressService.js
src/js/services/bwcError.js
src/js/services/profileService.js

fix wallet encrypted handler and rename BwsError service to BwcError

---

public/views/export.html

Hide advanced options on export QR tab

---

public/views/create.html

fix hide single address toggle

---

public/views/preferencesInformation.html
src/js/controllers/preferencesInformation.js

Wallet information: enables copy to clipboard on mobile

---

src/js/routes.js

enable keyboard scroll when is show

---

public/views/buyCoinbase.html
public/views/buyGlidera.html
public/views/create.html
public/views/import.html
public/views/join.html
public/views/modals/customized-amount.html
public/views/sellCoinbase.html
public/views/sellGlidera.html
public/views/walletHome.html
src/js/directives/directives.js

Fixes https://github.com/bitpay/copay/issues/4567

Disable mousewheel on numeric input fields

---

cordova/build.sh
public/views/includes/transaction.html
public/views/walletHome.html
src/css/mobile.css
src/js/services/fingerprintService.js
src/sass/main.scss

Fix scrolling when there are many txp s on OSX

---

src/js/controllers/index.js
src/js/controllers/modals/customAmount.js
src/js/controllers/modals/txDetails.js
src/js/filters/filters.js

Fixes https://github.com/bitpay/copay/issues/4533

Fix filter decimals

---

public/views/import.html
src/js/controllers/import.js

* Tap to hide error
* Do not show error if there is no data after scan

Fix error message

---

public/views/paymentUri.html
src/js/controllers/paymentUri.js

 hide incomplete wallets after click on a bitcoin uri

---

src/js/controllers/import.js

Fixes https://github.com/bitpay/copay/issues/4642

Fix import hw

---

public/views/import.html
src/js/controllers/import.js
src/sass/main.scss

Related in https://github.com/bitpay/copay/issues/4638

Shows scanned data - Import from QR

---

src/js/controllers/modals/txpDetails.js
src/js/controllers/walletHome.js

Problems (mobile): 
1.- Pressing the sign button, it isn't blocked by a few seconds. 
2.- Doing double tap on `Send Max` makes two call to the function.
Solution: 
Only adds a `$timeout` to block the button and the screen as soon as it was pressed in these cases:
* Sign a transaction
* Send Max

Prevent double tap (on mobile)

---

public/views/modals/txp-details.html
src/js/controllers/modals/txpDetails.js
src/js/services/onGoingProcess.js

Fixes https://github.com/bitpay/copay/issues/4557

Fix displaying errors in transaction proposal details

---

public/views/includes/confirm-tx.html
public/views/includes/copyToClipboard.html
public/views/includes/output.html
public/views/modals/tx-details.html
public/views/modals/txp-details.html
public/views/walletHome.html
src/css/ionic-migration.css
src/js/controllers/modals/txDetails.js
src/js/controllers/modals/txpDetails.js
src/js/controllers/walletHome.js

Notify when click on clickable element

---

public/views/walletHome.html

Fixes https://github.com/bitpay/copay/issues/4598

Prevent display share options twice

---

app-template/package.json

Ref: https://www.npmjs.com/package/fs
Fixes #4714

Remove 'fs' dependency

---

src/js/services/rateService.js

clean unused rateService code

---

src/js/controllers/paymentUri.js

Fix uri handler

---

src/js/controllers/confirm.js

Fixes https://github.com/bitpay/copay/issues/4896

Fix warning message on confirm view

---

src/js/controllers/activity.js
src/js/controllers/addressbook.js
src/js/controllers/addressbookAdd.js
src/js/controllers/amazon.js
src/js/controllers/bitpayCard.js
src/js/controllers/bitpayCardIntro.js
src/js/controllers/confirm.js
src/js/controllers/import.js
src/js/controllers/tab-home.js
src/js/controllers/tabsController.js
src/js/services/walletService.js

fix alert messages

---

src/sass/views/walletDetails.scss
www/views/includes/txp.html
www/views/walletDetails.html

formatted locked amounts and addressbook backward compatibility

---

www/views/modals/txp-details.html

remove created by and add complete date format to timeline

---

src/sass/views/integrations/glidera.scss
www/views/glidera.html

Changes settings icon. Buy and Sell options as home view

---

src/js/controllers/tab-home.js

fix next steps

---

www/views/modals/tx-details.html
www/views/modals/txp-details.html

change complete date format to time ago

---

src/js/controllers/paperWallet.js
www/views/paperWallet.html

fix sweep paper wallet backup message

---

src/js/routes.js
src/sass/shame.scss
src/sass/views/address-book.scss
src/sass/views/import.scss
src/sass/views/join.scss
src/sass/views/tab-send.scss
src/sass/views/views.scss
www/views/addressbook.add.html
www/views/join.html
www/views/paperWallet.html
www/views/tab-import-phrase.html
www/views/tab-send.html

fixes #4856
Also fix extra-padding on Android keyboard

fix : Scanner and keyboard at same time

---

src/js/controllers/amount.js

Fixes https://github.com/bitpay/copay/issues/4961

Fix amount

---

src/js/services/walletService.js
www/views/tab-home.html
www/views/walletDetails.html

A small fix for #4881, we should re-examine in another pass.

Make available/confirm balance concept less scary

---

Gruntfile.js
src/js/controllers/confirm.js
src/js/routes.js
src/js/services/incomingData.js
src/js/services/openURL.js
www/views/confirm.html

* Fix slide to pay for desktop after click on registered uri
* Adds uri handler for macOS (Info.plist)
* Fix hidden back button
Note: could fix some cases when the back button disappears.

URI handler support for macOS

---

src/js/controllers/tx-details.js
src/js/controllers/walletDetails.js
src/js/routes.js
www/views/modals/search.html
www/views/tx-details.html

* Updates tx-detail (cached)
* Fix search: open tx
fixes #4983

Fix tx-detail

---

src/js/controllers/copayers.js
src/js/controllers/modals/txpDetails.js

fixes #4975
* Fix error if backView does not exist when joining to a wallet
* Updates information (timeline) when copayers accept/reject a transaction
* Adds alert before delete transaction
* Fix delete transaction

Fixes modal of transaction proposals

---

app-template/package-template.json

chore(scripts): add placeholder start:desktop package script

---

src/js/controllers/feedback/rateAppStore.js
src/js/controllers/feedback/rateCard.js
src/js/controllers/feedback/sendFeedback.js
src/js/controllers/feedback/thanks.js
src/js/controllers/onboarding/welcomeController.js
src/js/controllers/tab-home.js
src/js/controllers/tab-settings.js
src/js/routes.js
src/js/services/configService.js
src/js/services/feedbackService.js
src/js/services/onGoingProcess.js
src/js/services/storageService.js
src/sass/views/feedback/rateAppStore.scss
src/sass/views/feedback/rateCard.scss
src/sass/views/feedback/sendFeedBack.scss
src/sass/views/feedback/thanks.scss
src/sass/views/tab-home.scss
src/sass/views/views.scss
www/views/feedback/rateAppStore.html
www/views/feedback/rateCard.html
www/views/feedback/sendFeedback.html
www/views/feedback/thanks.html
www/views/tab-home.html
www/views/tab-settings.html

Feedback feature

---

src/js/controllers/tab-home.js

Fixes https://github.com/bitpay/copay/issues/5014

Show Next Step

---

src/js/controllers/bitpayCard.js
src/js/controllers/preferencesBitpayCard.js
src/js/controllers/tab-home.js
src/js/routes.js
src/js/services/bitpayCardService.js
src/js/services/storageService.js
src/sass/views/bitpayCardPreferences.scss
src/sass/views/views.scss
www/views/bitpayCard.html
www/views/preferencesBitpayCard.html
www/views/tab-home.html

Manages multiple cards per account and multiple cards across multiple bitpay accounts.
Implements a simple framework for upgrading storage data (upgrades attached debit card storage).

Implement multiple cards.

---

src/js/controllers/tab-home.js
src/js/controllers/walletDetails.js
src/js/services/walletService.js
www/views/tab-home.html
www/views/walletDetails.html

better error handler

---

src/js/controllers/walletDetails.js
src/sass/views/walletDetails.scss

A quick fix to ensure the pull to refresh icon is still visible on android after recent changes.

Fix android pull to refresh icon

---

src/sass/views/includes/wallets.scss
src/sass/views/tab-receive.scss

https://github.com/bitpay/copay/issues/5034

receive tab visual issue fixes

---

src/js/controllers/feedback/send.js

* Show alert, click ok and return to tab-settings automatically

After send feedback from settings-tab, go back and clear history

---

src/js/controllers/feedback/complete.js
src/js/controllers/feedback/rateApp.js
src/js/controllers/tab-home.js
src/js/routes.js

Hides the status bar in the feedback flow via a flag on the state declaration in routes.js

Status bar routing

---

src/sass/buttons.scss
src/sass/views/includes/clickToAccept.scss
src/sass/views/includes/txp-details.scss
www/views/confirm.html
www/views/modals/txp-details.html

fix click to pay button to bottom of screen

---

src/js/services/profileService.js

Fix importing wallet from file

---

src/js/controllers/walletDetails.js

context-specific status bar color for wallet details view on android

---

src/js/services/localStorage.js

Change guarantees that localStorage always writes a string.

Detect and convert localStorage values to string.

---

src/js/controllers/onboarding/disclaimer.js
src/js/routes.js
src/sass/views/onboarding/onboard-disclaimer.scss
src/sass/views/onboarding/onboarding.scss
www/views/onboarding/disclaimer.html

https://github.com/bitpay/copay/issues/4869

terms of use disclaimer view animation

---

www/views/walletDetails.html

fix balance hidden

---

src/js/controllers/paperWallet.js
src/js/services/feeService.js

Calculate fee level when sweeping paper wallet

---

www/views/addressbook.html

Address book: + button

---

src/sass/views/wallet-backup-phrase.scss
www/views/backup.html

Fixes https://github.com/bitpay/copay/issues/5137

Backup flow - style

---

src/js/controllers/export.js
src/js/controllers/preferencesHistory.js
src/js/services/backupService.js
www/views/preferencesHistory.html

Closes https://github.com/bitpay/copay/issues/5142

Fix app name

---

src/js/controllers/preferences.js
www/views/preferences.html

Closes https://github.com/bitpay/copay/issues/5128

Add hide balance toggle

---

www/views/amount.html

Fixes icon resize when popover menu is displayed

Fix icon size - amount view

---

src/js/services/popupService.js

Fixes https://github.com/bitpay/copay/issues/4954

Fix autofocus

---

src/sass/views/tab-send.scss

center buy bitcoin on send screen

---

src/js/controllers/preferencesAltCurrency.js

Closes https://github.com/bitpay/copay/issues/4288

Remove dead/unused currencies

---

src/js/controllers/confirm.js
www/views/modals/txp-details.html

Also fix disabled buttons on txp details view

 allow amazon gift card for multisig wallets

---

src/js/controllers/amount.js
src/js/controllers/confirm.js
src/js/services/bitpayCardService.js
www/views/amount.html
www/views/confirm.html

Adds exchange rates during the top-up of the BitPay card

---

www/views/includes/wallets.html

hide balance on wallet selector

---

src/js/controllers/preferencesLanguage.js
src/js/controllers/translators.js
src/js/services/uxLanguage.js
www/views/preferencesAbout.html
www/views/preferencesLanguage.html
www/views/tab-settings.html
www/views/translators.html

Needs progress on https://crowdin.com/project/copay before merge

adding language detection and language preferences

---

i18n/po/template.pot
src/js/controllers/backup.js
src/js/controllers/confirm.js
src/js/controllers/create.js
src/js/controllers/join.js
src/js/controllers/modals/txpDetails.js
src/js/controllers/walletDetails.js
src/js/services/feeService.js
src/js/services/trezor.js
src/js/services/walletService.js
www/views/addressbook.add.html
www/views/confirm.html
www/views/feedback/send.html
www/views/onboarding/tour.html

Add translations and some fixes

---

src/js/controllers/preferencesAbout.js

Fix commit hash

---

src/js/controllers/onboarding/backupWarning.js

Fixes https://github.com/bitpay/copay/issues/4947

Close modal

---

src/js/controllers/create.js
src/js/controllers/import.js
src/js/controllers/join.js
www/views/import.html

Related https://github.com/bitpay/copay/issues/4909
Closes https://github.com/bitpay/copay/issues/4943
Disable hardware options for **BitPay distribution**:
* Create single/shared wallet
* Join wallet
* Import wallet

Disable hardware wallets

---

src/js/controllers/preferencesAltCurrency.js
src/js/services/storageService.js
www/views/preferencesAltCurrency.html

Preferences Alt Currency improves

---

src/js/controllers/confirm.js
src/js/services/walletService.js
www/views/confirm.html

Fix creating transaction with no priv key

---

src/js/controllers/addresses.js
src/js/controllers/advancedSettings.js
src/js/controllers/create.js
src/js/controllers/export.js
src/js/controllers/import.js
src/js/controllers/join.js
src/js/controllers/tab-home.js
src/js/controllers/tab-send.js

fix scroll resize send view and adding timeout to ionicScrollDelegate.resize

---

src/js/controllers/proposals.js
src/js/controllers/tab-home.js

Closes https://github.com/bitpay/copay/issues/5223

Use contact name in proposal card

---

src/js/controllers/preferencesAltCurrency.js
src/js/services/rateService.js

fix repeated currencies

---

src/js/controllers/preferencesLanguage.js

fixing contribute to translations button

---

i18n/po/fr.po

"C'est **pour le bon moment** [...] Aucune caméra cachée ?"
"C'est **un bon moment** [...] Aucune caméra cachée ?"
Sorry, corrected on Crowdin.

French wording

---

src/js/controllers/tab-home.js

increase time of feedback card to one week

---

www/views/addresses.html

adding space to descriptions

---

src/js/controllers/confirm.js

fix confirm popup on confirm view

---

www/views/join.html
www/views/tab-create-personal.html
www/views/tab-create-shared.html
www/views/tab-import-phrase.html

Fix input types

---

src/sass/shame.scss

Fix overflow text

---

src/js/controllers/tab-send.js

fix empty send view

---

src/js/controllers/preferencesBwsUrl.js
www/views/preferencesBwsUrl.html

Closes https://github.com/bitpay/copay/issues/4841

add bws url info

---

src/js/services/popupService.js
src/js/services/walletService.js
src/sass/shame.scss

add warning text on spending password prompt request

---

src/js/controllers/confirm.js

fix fee calculation issue

---

src/js/controllers/feedback/send.js
www/views/feedback/send.html

fix send feedback repeated buttons

---

src/js/controllers/addresses.js
src/js/controllers/customAmount.js
src/js/controllers/tab-receive.js
src/js/routes.js
src/sass/views/addresses.scss
www/views/addresses.html
www/views/tab-receive.html

fix design issue on specific amount feature

---

src/js/controllers/amount.js

Fix Amount view if the back arrow disappears

---

src/js/services/profileService.js

Fix network selection at startup for wallet creation

Fix network at wallet creation

---

src/js/controllers/amazon.js
src/js/controllers/confirm.js
src/js/controllers/modals/amazonCardDetails.js
src/js/services/amazonService.js
src/js/services/onGoingProcess.js
src/js/services/walletService.js

manual loading and some details fixes

---

src/js/controllers/tab-send.js

check balance refactor

---

src/js/services/txFormatService.js

fix format amount

---

src/sass/shame.scss
src/sass/views/address-book.scss
src/sass/views/join.scss
www/views/addressbook.add.html
www/views/join.html

fix icon position

---

src/js/controllers/amount.js
src/js/controllers/confirm.js
src/js/routes.js

BitPay card: Fix value in USD on confirm view

---

Gruntfile.js
app-template/index.html
src/sass/ionic.scss

fixes #5082 
* Also Gruntfile refactor.
https://github.com/driftyco/ionic/issues/5899

Fixes when swipe back, the nav bar become blank

---

www/views/walletDetails.html

fix hidden amount not fully displayed

---

src/js/controllers/confirm.js
src/js/controllers/modals/paypro.js
src/sass/views/includes/txp-details.scss
www/views/modals/paypro.html

improve design on payment protocol view

---

www/views/walletDetails.html

Fix date format on walletDetails list

---

src/js/controllers/onboarding/disclaimer.js
src/sass/views/onboarding/onboard-disclaimer.scss
www/views/onboarding/disclaimer.html

fix UI on disclaimer view

---

i18n/po/es.po

Reverts bitpay/copay#5370
Bad format

Revert "Update translation files"

---

i18n/po/de.po
i18n/po/es.po
i18n/po/fr.po
i18n/po/template.pot
src/js/services/uxLanguage.js
www/views/onboarding/tour.html

Fixes https://github.com/bitpay/copay/issues/5381
Available languages:
* Spanish
* French
* German

Update po/pot files - fix button translation

---

src/js/routes.js
src/sass/views/includes/modals/modals.scss
src/sass/views/onboarding/onboard-backup-request.scss
src/sass/views/onboarding/onboard-disclaimer.scss
src/sass/views/onboarding/onboard-tour.scss
src/sass/views/onboarding/onboarding.scss
src/sass/views/wallet-backup-phrase.scss

Fixes https://github.com/bitpay/copay/issues/5251
Waiting for https://github.com/bitpay/copay/pull/5393

Fix onboarding layout errors

---

src/js/controllers/import.js
src/js/directives/qrScanner.js
src/js/routes.js
www/views/import.html

Fix QR scanner from directive

---

www/views/translators.html

Closes https://github.com/bitpay/copay/issues/5418

Update translation list

---

src/js/controllers/import.js
www/views/import.html

Fix advanced button after change tab

---

www/views/tab-settings.html

Fix item-list for tab-settings

---

src/js/controllers/modals/txpDetails.js
src/js/controllers/tx-details.js
www/views/modals/txp-details.html
www/views/tx-details.html

Fixes https://github.com/bitpay/copay/issues/5297

Fix timeline item order

---

src/js/controllers/addresses.js

Fixes https://github.com/bitpay/copay/issues/5447

Fix wallet name

---

www/views/tab-create-shared.html

Fix empty content

---

src/js/controllers/modals/search.js
www/views/modals/search.html

Search transaction by txid

---

README.md

Related https://github.com/bitpay/copay/issues/5443#issuecomment-272191870

Update chrome-app build - README

---

src/js/controllers/tab-home.js

Revert "Fix release url"

---

src/sass/views/onboarding/onboard-backup-request.scss

Fix text/icon positioning for some languages and dimensions

Fix backup-request view dimensions - onboarding

---

i18n/po/template.pot

Waiting for https://github.com/bitpay/copay/pull/5437

Update pot file

---

app-template/bitpay/appConfig.json

* Enable Coinbase integration to buy/sell bitcoin
* Adds Chinese Simplified to list of supported languages (Spanish, French and German) 
* Many UI bug fixes

New release BitPay v1.3.0

---

src/sass/views/amount.scss

Related https://github.com/bitpay/copay/issues/5474

UI bug - amount view

---

src/js/controllers/coinbase.js
src/js/services/coinbaseService.js
src/js/services/incomingData.js
src/sass/views/integrations/coinbase.scss
www/views/coinbase.html

* Logout function also removes txs

Fix first link to your account. Removes unused variables. Fix spinner

---

src/js/controllers/export.js
src/js/controllers/preferencesAdvancedController.js
src/js/controllers/preferencesBwsUrl.js
src/js/controllers/preferencesDelete.js
src/js/controllers/preferencesHistory.js
src/js/controllers/preferencesInformation.js
src/js/services/walletService.js
src/sass/icons.scss
www/views/export.html
www/views/includes/walletItem.html
www/views/preferences.html
www/views/preferencesAdvanced.html
www/views/preferencesBwsUrl.html
www/views/preferencesDeleteWallet.html
www/views/preferencesHistory.html
www/views/preferencesInformation.html

- fixes Delete Tx History
- Add wallet indicator in preferences inner views.

fix delete tx history

---

src/js/controllers/advancedSettings.js
src/js/controllers/buyandsellController.js
src/js/routes.js
www/views/buyandsell.html

Fixes https://github.com/bitpay/copay/issues/5483

Fix enabled services list

---

src/js/controllers/preferencesDelete.js
www/views/preferencesDeleteWallet.html

* After delete wallet, the view "deleteWallet" remain in cache, getting error in console log.

Fix delete wallet view cache and transition. Fix UI details

---

src/js/controllers/bitpayCardIntro.js
src/js/controllers/tab-home.js
src/js/services/storageService.js

Fixes disappearance of debit cards from UI.  Users may have to pair again.
This needs to be tested on a release prior to 1.3 and a "broken" 1.3 release.

Synchronize all storage upgrade.

---

src/js/controllers/tab-scan.js
src/js/services/scannerService.js

Fixes: #4935, #4967, #5172, #4946, and #4831

Improve scanner handling on all platforms

---

www/views/tx-details.html

Fixes https://github.com/bitpay/copay/issues/5507

Add translate - Transaction details

---

src/js/services/txFormatService.js

Fixes https://github.com/bitpay/copay/issues/5454

Fix format

---

src/sass/views/includes/slideToAccept.scss
www/views/includes/slideToAccept.html

Fixes https://github.com/bitpay/copay/issues/5509

Fix text overflow - confirm button

---

app-template/bitpay/appConfig.json

New release bitpay-v1.3.1

---

src/js/controllers/feedback/complete.js
src/sass/views/feedback/complete.scss
www/views/feedback/complete.html

remove backbutton and adding finish button on complete view

---

Gruntfile.js

* Fixes connection to Coinbase account.

Updates NW SDK v0.19.5

---

src/js/controllers/export.js
src/sass/views/export.scss
www/views/tab-export-file.html

Fixes https://github.com/bitpay/copay/issues/4848
Border and text color:

Export wallet - password hinting

---

src/js/controllers/backup.js
src/sass/shame.scss
www/views/backup.html
www/views/includes/terms.html
www/views/preferencesLogs.html
www/views/termsOfUse.html

Fixes https://github.com/bitpay/copay/issues/4854
Backup phrase > only testnet wallets
Tested on:
* Android
* Desktop
* iOS

Select text
