package.json
- There was bug in squaring that in rare situations would produce an incorrect value, see: https://github.com/indutny/bn.js/commit/3557d780b07ed0ed301e128f326f83c2226fb679
- The incorrect squaring would lead to calculating a bitcoin address where it would be possible to receive funds that would not be spendable.
- For more details about the bug, see: https://github.com/bitpay/bitcore/pull/894
- Fixes issue #2281
Relevant bitcore commit: https://github.com/bitpay/bitcore/commit/e20df2144926dbc20bd468d671e73f8e52bb70c1
=> Upgraded bitcore to version that includes elliptic 1.0.0 and bn.js 1.0.0

css/src/mobile.css
The previous CSS code disables text selection on all screen but not allowed paste text on input and textareas. This fix enable the copy to inputs and textareas.
=> Important fix: paste into input and textareas

views/includes/head.html
onbeforeunload doesn't work on chrome app, so we removed the attribute href to the signout link.
Fixes #2392
=> Fix notification of needing backup on chromeapp

bower.json, src/js/controllers/index.js, src/js/controllers/send.js, src/js/controllers/walletHome.js, src/js/services/isChromeApp.js
- ignorePayPro verification in chrome, so chrome users can sign PayPros generated from other devices.
=> ignorePayPro verification in chrome

po/ja.po, po/template.pot, public/views/create.html, public/views/join.html
Running through the app and also running through the po file.
There are a loooot of strings in the po file where I can't figure out how to confirm them on the app. So spacing and word usage in order to make the length/spacing aesthetically pleasing etc. s very difficult.
But anywho, 2 major changes in terminology that a lot of friends were asking me about.
Because there are no tutorials, terminology for "Payment Proposal" and "Your Nickname" etc. must be chosen carefully.
(one guy said he used his real name thinking it wouldn't be shown to copayers etc.)
Anywho, my ramblings of things I noticed when running over the translations are not too important.
Here are the translations, please merge
BTW when will you upload the Japanese appstore description? I still get "Is this app OK?" when they …
=> Japanese fixes

src/js/services/configService.js
The first time I ran Copay as a server and opened localhost:3000 in Chrome on Mac OSX, the page did not render. The configService had an error, configCache.wallet is undefined, when looking for settings.unitCode. This change solves that error for me.
=> When running from browser for first time configCache.wallet is not found

po/ja.po, po/template.pot, public/views/paymentUri.html, public/views/preferencesFee.html, public/views/walletHome.html
Especially paymentUri.html was including the span tag and the empty spaces in front of the file, as well as \r which should not be translated around [testnet] in it. This must be fixed.
Also, I worried whether to include [testnet] as a translation or not. I leave it up to you.
Also I added Japanese translations.
=> Fix Japanese and English

public/index.html, src/css/mobile.css
* When dragging to left (iOS). Fixes #2934
* Also removes `shadow`
* Transition to open modals (WP8). Partially resolved
=> Fixed modals

src/js/controllers/index.js, src/js/controllers/preferencesEmail.js, src/js/controllers/preferencesLanguage.js, src/js/controllers/preferencesUnit.js, src/js/routes.js, src/js/services/profileService.js, src/js/services/storageService.js
Saves `lang` and `unit` setting on BWS for better emails.
This is triggered on changing the language or unit setting, or when setting the email.
On the first 2 cases, all wallet settings will be updated.
When changing the email only the focused wallet will be updated.
=> save lang and unit in BWS (for notifications)

public/views/walletHome.html
* Removes `oh` attribute that broken the animation on WP and Android (old versions).
* Normalize some links styles.
=> Fix history layout (and modal animation for WP and Android)

src/js/controllers/index.js
We can't add extra columns to maintain compatibility with LibraTax. The transaction id was included as a note.
Fixes #2989
=> Adds txid to Note column

src/css/mobile.css
Opening a modal on Android < 4.3 (that use a native in-app browser, not chrome) doesn't work. This PR fix that.
=> Fixes open modal for android < 4.3

public/views/backup.html, public/views/modals/txp-details.html, public/views/walletHome.html, src/js/controllers/backup.js, src/js/controllers/index.js, src/js/controllers/walletHome.js, src/js/services/backupService.js, src/js/services/txStatus.js
- this add 'no private key' advanced option to backup.
It is then possible to export a backup without the wallet's private key.
A wallet with a imported backup without private key can: see wallet balance, see tx history, create spend proposal, reject spend proposals, BUT CANNOT SIGN (approve) proposals.
=> export backup without signing capabilities

src/js/controllers/walletHome.js
Make Copay to call ``setOngoingProcess`` when ``Addon/OngoingProcess`` event received.
Addons may emit this event to display relevant process indication to user.
Example: https://github.com/troggy/copay-colored-coins-plugin/blob/41df7c7d90e203e39245e5a574204fd53a884112/js/controllers/assets.js#L11
=> Addons can use OngoingProcess indicator

public/views/preferencesLanguage.html, src/js/controllers/index.js
This PR removes the names of languages in order to use always the name in the original language.
=> Removes translation for languages name

src/js/controllers/index.js, src/js/services/addonManager.js
Addons now may register ``formatPendingTxp`` function which will be called on every pending tx proposal. This allows to add addon-specific information to proposal (e.g. custom amountStr)
Example which adds color information (if any):
https://github.com/troggy/copay-colored-coins-plugin/blob/b56c0f0d2b6f8e8186f712da980b3d33ed91423b/dist/copayColoredCoins.js#L17
=> Allow addons to customize pending proposals

public/index.html, public/views/includes/alert.html, public/views/walletHome.html, src/css/main.css, src/js/controllers/create.js, src/js/controllers/index.js, src/js/controllers/join.js, src/js/controllers/walletHome.js, src/js/services/addressService.js, src/js/services/bwsError.js, src/js/services/profileService.js
- fixes https://github.com/bitpay/copay/issues/2812
- Better error handling for error coming from BWC/BWS (matching new BWS's error codes)
- Handles and upgrades with the new 'newBlock' notification (when using the new `useUnconfirmedSpend` flag)
- Displays balance differentiated for confirmed/unconfirmed  (when using the new `useUnconfirmedSpend` flag)
- add a universal error popup (to replace alert() that does not work on ChromeApp)
=> Handling errors / multiple join / differenciated balance

src/js/services/txStatus.js
Favour overriding instead of options introduced in #3065.
[Example](https://github.com/Colored-Coins/Colored-coins-add-on-for-Copay/commit/d052572ee72e6cfe211696eb1a68d4bf3bf542d1#diff-ce1d47e10e38c9c3cede9d6c803b88d3R147)
=> Refactor txStatus to ease overriding in addons.

src/js/routes.js
Possible fix for #3140
By default Angular will prefix such image URLs with ``unsafe:`` thus stopping images to appear
Related reading: http://stackoverflow.com/questions/15606751/angular-changes-urls-to-unsafe-in-extension-page?lq=1
=> Whitelist chrome-extension URL schema for images

public/views/includes/menu-item.html, src/js/controllers/index.js
Another iteration of [this](https://github.com/bitpay/copay/pull/3069) PR
Now addresses this issue: https://github.com/bitpay/copay/pull/3069#issuecomment-138290326
Function ``setTab`` now accepts optional flag specifying whether to switch to ``walletHome`` state or not. This flag is set only for click handlers in bottom menu. This is not the proper fix, but rather a workaround. Proper fix would be to prevent ``setTab`` calling for states different from ``walletHome``
=> Allow addon menu items to run arbitrary code on click

public/views/backup.html
This fixes the following bug:
1. Generate wallet in Japanese setting.
2. Switch device language to English.
3. view phrase for wallet
4. notice the ideographic space is missing. (words look very close together)
the [\u3041-\u308f] block was taken from here:
https://en.wikipedia.org/wiki/Hiragana_(Unicode_block)
All words in the list contain at least one of the characters in the block I set, and also, other languages should not have Japanese in them I think :-P
=> fix Japanese phrase spacing for non ja language

public/views/includes/menu.html, public/views/walletHome.html
* Also hide `receive`, `send` and `history`.
* Fix menu-toggle element
fixes #3077
=> Hide menu if wallet is not authorized

public/views/includes/menu.html
@troggy there was an error with the touchdown event binding (`menu-walletHome` ID was repeated) so we had to change a `ng-show` with a `ng-if`. Please check you code still works.
=> fix menu-item

bower.json
* The update to version 1.0.0 requires more test and modifications in some functions. So, in order to release a new version soon, we decided to use the previous (and stable) version of angular-bitcore-wallet-client.
=> Fix abwc version

src/js/services/storageService.js
Disables UUID encryption on mobile devices, due to random problems detected on some Android devices, getting the UUID at startup.  
Encryption on mobile devices using UUID does not add significant protection anyways, and the user can still encrypt the xprivkey using it own password.
Manually tested on iOS simulators and iPhone 6.
=> do not encrypt profiles in mobile

public/views/modals/txp-details.html, src/js/controllers/walletHome.js
Fixes: #3461
(hide 'delete' if n=1); show error, when error is not an object (ie: from a hardware wallet app)
=> hide delete is n=1, show err if sign failed

.gitignore, Gruntfile.js, angular-bitcore-wallet-client/index.js, package.json, src/js/controllers/index.js, src/js/controllers/sidebar.js
* Fix empty wallets at the sidebar
This happen when incomplete wallet are recovered from seed (fixed in BWC bitpay/bitcore-wallet-client#192), will be added in BWC in Copay 1.6.
If the wallet completes, it will appear (with its name) at the list
* Updates BWC with the mentioned fix
* Removes `angular-bitcore-wallet-client` dependency, and adds `bitcore-wallet-client`. Adds browserify to grunt.
=> sanitize wallet list

src/js/services/configService.js
Call to ``configService.getDefaults()`` after ``configService.set(...)`` returned current config from storage, not the default config.
=> Fix: configService.set() pollutes default config

src/js/services/profileService.js
The profileService.unlockFC() method automatically locks the fc after 2 seconds but it doesn't work.
Before calling lockFC() it checks fc.isPrivKeyEncrypted(), but it is false after unlocked the fc, and if it is true it is not necessary to call lockFC(). In my opinion the ritght test should be on fc.hasPrivKeyEncrypted().
=> Fix automatic lock of focused client on timeout

src/js/services/ledger.js
Referred to this error:
Requesting Ledger Chrome app to sign the transaction
bwcService.buildTx is not a function
=> Fix build transaction method in ledger service

browser-extensions/chrome/manifest.json, package.json
fixes storage for big wallets.
Windows PHone is still not support it for this (we use localStorage there, and the limitation is still 5MB)
=> more storage for big wallet's history

src/js/services/fileStorage.js
There is a missing error callback in dir.getFile() call and a duplicated parameter in the fileEntry.remove() call
=> Add error callback  to getFile() call

Gruntfile.js
* Moves mobie.css to the end of the concatenated file (in order to prioritise mobile fixes).
=> Fix mobile css

src/sass/forms.scss
=> Deactivate the auto-capitalize for the small tag

src/js/controllers/index.js, src/js/services/profileService.js
After import a wallet -> start scan, backup flag and address flag events are triggered more than once.
=> Remove handle imported client method

public/views/export.html, src/js/controllers/export.js, src/js/services/backupService.js, src/js/services/profileService.js
- Remove including history cache option from export (long transactions histories are imposible to copy) fixes:  #4189
- Remove "backup done" flag from export (the user should always get through 12 words flow)
- Include always address book when exporting file.
=> Export refactor

src/js/controllers/backup.js, src/js/controllers/tab-receive.js, src/js/services/profileService.js, src/js/services/storageService.js, src/sass/views/includes/modals/modals.scss, www/views/includes/backupNeededPopup.html, www/views/tab-receive.html
I think we should keep it simple. There are so much issues with this feature. 
-  Clicking on Receive tab and immediately on other shows the modal, but sometimes no.  Sometimes the 'Wallet/Changed' event fires when we are out that view.
-  Sometimes the 'Wallet/Changed' is not fired and the modal do not show at all.
- When the modal is not shown the top label is also not shown.
Maybe we could create a an issue to add this feature again later.
=> remove to show backup needed modal automatically when clicking on receive view

src/js/controllers/preferencesNotifications.js, src/js/controllers/tab-settings.js, src/js/services/configService.js, src/js/services/emailService.js, www/views/preferencesNotifications.html, www/views/tab-settings.html
Closes #4844
* Add enable email notifications toggle in settings, notifications option
* Hide push notification toggle if it isn't mobile
> Enable it to save remote preferences with the current email settings (if exist) on storage
> Disable it to save remote preferences with empty salues on email settings
=> Add toggle for email notifications

src/sass/mixins/layout.scss, src/sass/views/includes/actionSheet.scss, src/sass/views/includes/clickToAccept.scss, src/sass/views/includes/modals/modals.scss, src/sass/views/includes/slideToAccept.scss, src/sass/views/includes/slideToAcceptSuccess.scss, src/sass/views/includes/txp-details.scss, src/sass/views/includes/wallets.scss, src/sass/views/tab-receive.scss
This adds missing webkit prefixes for the css property `transform`. These are required by Android 4.x
=> Add webkit prefixed transforms (android 4)

src/js/services/feeService.js
Bitcore-Wallet-Service allows for a minimum fee of `0`, however if this is the case it will currently cause Copay errors. These problems are caused by the `!feeLevelBalue.feePerKb` checks that return true on a case of `0`.
This PR only solves half of the problem as there is a similar check in Bitcore-Wallet-Client which I have also created a [pull request](https://github.com/bitpay/bitcore-wallet-client/pull/320) for.
=> Use more explicit logic in fee level check

www/views/tab-settings.html
This updates the Help Center link in the wallet's settings view to point toward the BitPay app category on help.bitpay.com.
=> Update Help Center Link

src/sass/views/tab-receive.scss
=> fix address text

app-template/config-template.xml
fixes #5299 
Device: iPhone 6 plus. (iOS 10.2)
=> Fix missing setting icon on iOS

src/js/services/profileService.js
Fix a BWS crash when deleting a wallet with push disabled. No need of push unsubscribe when push is disabled. Else this leads to a full crash and stop of BWS server incase it doesn't support push.
=> Fix wallet deletion without push

src/js/controllers/confirm.js
* Sometimes if the wallet can't get rates (on top-up process), give a javascript error.
=> Check if have rates

src/js/controllers/tx-details.js
Updated memo isn't displayed to the user on save on same view. User has to perform some other action such as re-edit or go back, to see the changes reflect. To fix this, added $scope.$apply() to make sure changes are displayed to the user on save.
=> Display updated memo on save

src/js/services/onGoingProcess.js
User doesn't have ability to cancel on going progress, thus spinner dialog runs forever. Otherwise, during no network connection, if user goes to view their transaction the spinner dialog will run forever and requires app restart to get back. Set root.clear as callback, so user are able to cancel the progress and hide the spinner dialog.
=> Allow user to cancel on going progress and hide spinner dialog

src/sass/views/includes/txp-details.scss
=> Fix message overflow

app-template/config-template.xml
Tested on iOS and Android.
Works really well on iOS The Android implementation is a bit strange (just leaves the app preview blank), but in testing other apps, it doesn't seem like there's a better way to do it. So this is probably good for now.
=> feat(cordova): add screen privacy for iOS and Android

www/views/walletDetails.html
This is a temporary fix to avoid the users to copy a wrong address when they enter to the wallet details of a wallet and then enter to the receive tab.
Confusion: 
```
So I click on the wallet in the home screen
Then I click on "Receive" at the bottom
It shows me an address. But this is the address for a TOTALLY DIFFERENT WALLET.
```
=> temporary fix for the tabs confusion

src/js/directives/directives.js
When you change the slider to fast the slideChangeEnd event is not fired, so, you get a wrong address.
=> fix bug when changing selector too fast

src/js/controllers/bitpayCard.js, www/views/bitpayCard.html
- Ensure no floating comma in tx history (wavecrest does not provide merchant location).
=> Wavecrest card compatibility

app-template/config-template.xml
Hello,
We've noticed a problem opening Copay on Android from another Cordova app 
when using bitpay/cordova-sdk. Copay is opened within the same window as the calling app, 
making hard to switch back to the calling app. The similar problem is described at
https://stackoverflow.com/questions/28058633/deep-linking-into-a-cordova-app-from-a-web-browser-on-android-opens-app-within-t
Regards, Egor
=> Problem opening Copay on Android from another Cordova app

src/js/controllers/bitpayCard.js, src/js/controllers/proposals.js, src/js/controllers/tab-home.js, src/js/controllers/walletDetails.js, src/js/directives/svg.js, src/js/services/bitpayCardService.js, src/js/services/timeService.js, src/sass/views/bitpayCard.scss, www/views/bitpayCard.html, www/views/includes/cardActivity.html, www/views/includes/txp.html, www/views/includes/walletHistory.html
- Makes the card history view look the same (similar) to the wallet history view.
- Relative or absolute tx time (less than a day = relative).
- Removes the running balance presentation (UI change only, logic still in place).
- Introduces timeService to share common functions between wallet and card views.
- Enhances svg directive to work with images using ngSrc.
- Adds card `country` to the cards collection (not used at the moment, will need for future policy statements in the app).
=> Unifies card history view with wallet view

www/views/onboarding/welcome.html
Oh god, I did not know that it was possible to do it so easily :blush:
I just tested it, and it works, there is a new "Get started" strings in the PO file after the grunt translate command :raised_hands:
I want this because there is another "Get started" string (for the bitpay card) that it not a button, and I want to apply a specific translation for each one.
=> [i18n] Add context

app-template/package-template.json, src/js/controllers/advancedSettings.js, src/js/controllers/confirm.js, src/js/controllers/customAmount.js, src/js/controllers/tab-receive.js, src/js/directives/incomingDataMenu.js, src/js/services/incomingData.js, src/js/services/walletService.js, www/views/advancedSettings.html, www/views/confirm.html, www/views/customAmount.html, www/views/includes/incomingDataMenu.html, www/views/tab-receive.html
already working in receive and  send.
ToDo:
=> cashaddr support

src/js/controllers/shapeshiftConfirm.js
Could happen that the new transaction doesn't appear in the main view of ShapeShift.
=> Shift: save data almost immediately after send transaction

src/pages/wallet-details/wallet-details.scss
Reverts bitpay/copay#7865
This breaks the walletDetail view
=> Revert "[V4] homogenized styles for labels and icons in wallet details page"

src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-addresses/wallet-addresses.ts
When you generate a new address by pressing "+" in "Wallet Addresses", the path of the address is prefixed by `m/` instead of `xpub/`, which is used for existing addresses in UI.
This pull request will fix the issue.
=> Fix path format of new addresses in UI

src/theme/variables.scss
This fix is for titles with long translations on small devices with meterial design, to prevent collapse between text and back arrow on secondary pages
=> Fix: Titles with long translations on small devices

src/providers/wallet/wallet.ts
This causes an unexpected call to a promise and could be store incorrect information. Only return an error in console.log.
=> Fix: removes async function when creating new address

src/app/app.scss, src/pages/home/home.scss, src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.scss
Not sure why this line was removed here https://github.com/bitpay/copay/pull/8453/files#diff-3c303face59d40ba5031ed6c51449334L52, but this line is necessary to ensure no ugly gaps appear on iOS when the user over-scrolls.
Spoke with @Gamboster, and it turns out those lines were removed to prevent issue #8420. I've updated my PR to fix both issues.
=> Fix css iOS scroll styling regression

src/pages/home/home.spec.ts, src/pages/send/confirm/confirm.spec.ts, src/pages/wallet-details/search-tx-modal/search-tx-modal.ts, src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.spec.ts, src/pages/wallet-details/wallet-details.ts, src/providers/time/time.spec.ts, src/providers/time/time.ts
Now that https://github.com/bitpay/copay/pull/8485 has been merged, we can now greatly simplify page tests by using the providers module rather than having to import each provider dependency manually.
This PR also fixes a bug with the `getMonthYear` method in `TimeProvider`.
=> Simplify page tests, and fix TimeProvider bug

src/pages/send/confirm/confirm.html
=> [Punctuation] "Bitcoin miner fee</span>:" → "Bitcoin miner fee:</span>"

src/pages/tx-details/tx-details.html, src/pages/tx-details/tx-details.scss
I think is really useful for users that need support to have this information (that is usually asked) no so hidden.
=> FEAT: show transaction id in transactions details ( copy to clipboard added )

src/pages/integrations/amazon/buy-amazon/buy-amazon.ts, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts, src/pages/integrations/coinbase/buy-coinbase/buy-coinbase.ts, src/pages/integrations/coinbase/sell-coinbase/sell-coinbase.ts, src/pages/integrations/glidera/buy-glidera/buy-glidera.ts, src/pages/integrations/glidera/sell-glidera/sell-glidera.ts, src/pages/integrations/mercado-libre/buy-mercado-libre/buy-mercado-libre.ts, src/pages/integrations/shapeshift/shapeshift-confirm/shapeshift-confirm.ts, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-addresses/wallet-addresses.ts, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-transaction-history/wallet-transaction-history.ts
Currently, any time `this.navCtrl.parent.select(0)` is used in the codebase, a `setTimeout` wraps the subsequent `this.navCtrl.push(NewPage)` call to ensure the page `push` only occurs after the tab select has completed. However, `this.navCtrl.parent.select(0)` returns a promise that can be awaited to improve performance, reliability, and code maintainability. This refactor replaces such instances of `setTimeout` with promises.
=> Refactor: Use Promises instead of setTimeouts

src/providers/wallet/wallet.spec.ts, src/providers/wallet/wallet.ts
*Waiting for the bitcore-lib-cash fix to complete the flow with the prefix of BCH testnet
=> Fix: bchtest prefix for BCH testnet wallets

src/pages/wallet-details/wallet-details.html
Currently the "moved" icon is not being shown in transaction history (just an empty spot). This PR ensures the moved icon is properly displayed.
=> Fix: Ensure moved icon displays properly

src/pages/home/home.scss
This ensures proper padding is applied to the iPhone scan button (fixes a minor regression that improved padding on iPhone X)
=> Fix scan button positioning

src/pages/send/amount/amount.ts
Currently, the BTC rate is always used in the send max calculation and results in an incorrect dollar value displayed when send max is used inside of a BCH wallet. 
Thanks to @cronos-polis for reporting this bug here: https://github.com/bitpay/copay/pull/8851#issuecomment-404924934
=> Fix send max USD value when sending from BCH wallet

package.json, src/pages/pin/pin-pad/pin-pad.component.ts, src/pages/send/amount/amount.html, src/pages/send/amount/amount.spec.ts, test/karma.conf.js
A follow up PR that adds tests to ensure the USD send max bug that was fixed in this PR does not reoccur: 
https://github.com/bitpay/copay/pull/8873
=> add tests for sendMax method

src/pages/send/confirm/confirm.ts
Bypasses the `setCurrencySelector` method in `confirm.ts` if the payment was initiated from within a wallet, since the wallet is  already implicitly set.
=> Ignore currency selector if within wallet

src/pages/send/amount/amount.spec.ts, src/pages/send/amount/amount.ts, src/pages/send/send.spec.ts, src/pages/send/send.ts, src/pages/wallet-tabs/wallet-tabs.provider.ts, src/providers/incoming-data/incoming-data.spec.ts, src/providers/incoming-data/incoming-data.ts
Currently, scanning a bitcoin address either from the home view or from within a wallet breaks if the user chooses the send max option. This PR fixes this issue.
=> Fix send max bugs when scanning a qr code

src/pages/receive/receive.html, src/pages/send/amount/amount.html, src/pages/send/amount/amount.spec.ts, src/pages/send/amount/amount.ts, src/pages/send/confirm/confirm.ts, src/pages/send/send.html, src/pages/send/send.ts, src/pages/wallet-details/wallet-details.scss
This PR fixes:
- Send maximum amount of a wallet with locked funds
- Receive view and Amount view now show the clock icon when the total balance is not spendable
- In Amount page, by clicking the "Send Max" button, redirect to the Send view directly
- Send Max is correctly calculated when trying to send to an address pasted in the input of the Send Page
- Miner fee now is set regardless of whether you click on "GOT IT" of the modal
=> Fix: Send Max behavior for wallets with locked balance

src/pages/send/amount/amount.html, src/pages/send/amount/amount.ts, src/pages/send/send.html, src/pages/send/send.spec.ts, src/pages/send/send.ts, src/pages/wallet-tabs/wallet-tabs.provider.ts, src/pages/wallet-tabs/wallet-tabs.ts, src/providers/address/address.ts, src/providers/incoming-data/incoming-data.spec.ts, src/providers/incoming-data/incoming-data.ts
Is really common that the user enters to a wallet when he wants to do payments, it happens that is no scanner inside the wallet modal. This way we avoid that issue and also we improve the experience when the user has an element in the clipboard that wants to paste.
=> refactor send flow 

src/pages/send/confirm/confirm.ts
. Avoid user to change or use send max amount if the previous view is not Amount page
. Fix transition when the user wants to change the amount
. If user click outside infosheet go to change amount
=> Avoid user to change or use send max amount if paypro

src/app/app.scss, src/pages/home/home.html, src/pages/home/home.scss, src/pages/settings/addressbook/addressbook.html, src/pages/settings/addressbook/addressbook.scss, src/pages/settings/settings.scss
=> Fix: styles for long strings when use different languages

src/pages/add/import-wallet/import-wallet.ts, src/providers/profile/profile.ts, src/providers/wallet/wallet.ts
Fixes in this PR:
- Go to recently imported wallet even if we got the error: "could not update Remote Preferences"
- Prevents repetitive errors of "Error: Uncaught (in promise)" for wallets that can not download the tx history
- Prevents get stuck on loading "importing wallet..." message, If there is an error while importing a wallet
=> Fix: importing wallet with errors in bws url

src/providers/profile/profile.ts, src/providers/wallet/wallet.ts
=> Fix: prevent logs from repeating unnecessarily

src/pages/integrations/gift-cards/card-details/card-details.html, src/pages/integrations/gift-cards/card-details/card-details.scss, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/integrations/gift-cards/home-gift-cards/home-gift-cards.ts, src/providers/gift-card/gift-card.ts
This PR gracefully handles the case when a user attempts to purchase a gift card and then closes the app before the gift card purchase completes (users might do this when experiencing slow api calls or shoddy network connections), and ensures that the user is able to fetch their claim code when they relaunch the app.
Here's the approach:
1. When the user confirms the purchase, before broadcasting the payment, store the gift card and its `accessKey` with status `UNREDEEMED`. If the user does not close the app during the broadcast step, and the purchase succeeds like usual, then update the `UNREDEEMED` status to `SUCCESS`.
3. If the user does close the app mid-purchase, then on app launch, check for any `UNREDEEMED` gift cards and attempt to redeem them. If the redemption attempt succeeds, …
=> Handle gift card purchase interruptions

src/pages/pin/pin-modal/pin-modal.ts
This PR:
- Avoids to block the app when stay open in the background without having failed 3 times in the unlock code.
- Avoids to get garbage characters, and  place multiple errors in the code entry unintentionally when type more than 4 numbers
=> Fix: pin modal to prevent malfunction of the lock method

package-lock.json, package.json
Adds https://github.com/zyra/ionic-image-loader
This package will boost the loading speed of gift card images (or any images initially fetched remotely) by storing them locally on the device after the initial fetch. This package also ensures that users are able to properly view (and redeem) previously purchased gift cards even when experiencing poor or nonexistent network connectivity.
=> Add ionic-image-loader

src/pages/wallet-details/wallet-details.html, src/providers/gift-card/gift-card.ts
1. Fixes TS error related to using spread operator on `Set`.
2. Adds a generic gift card fallback image that will be displayed in wallet transaction history if the brand specific icon cannot be fetched for any reason.
=> Remote gift card catalog fixes

src/components/amount-picker/amount-picker.html, src/pages/integrations/gift-cards/card-details/card-details.html, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.html, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/providers/gift-card/gift-card.ts, src/providers/persistence/persistence.ts
1. Ensures only confirmed inputs can be used for gift card purchases to prevent payment issues
2. Skips the 2nd confirm step (the confirmation alert) for gift card purchases for a faster checkout experience 
3. Splits `cardConfigCache` into testnet and livenet storage keys to prevent overriding the production cache during development
4. Hides the `Purchase Amounts: ` list if only one purchase amount is available
5. Uses the gift card `displayName` as the title on the confirm page
=> Gift Card Improvements

src/pages/backup/backup-game/backup-game.html, src/pages/backup/backup-game/backup-game.scss, src/pages/backup/backup-key/backup-key.scss
Tappable words are now in grey container with no shadow hex color #F6F6F6
Large words are in a blue background container hex color #F6F7FC
Increase the height and width of large words container.
Page background to white.
Make words more of a carousel showing the edge of the previous and next card up.
Old:
New
=> [FEAT] UI improvements for backup game

app-template/config-template.xml, package-lock.json, package.json, src/app/app.scss, src/pages/add/create-wallet/create-wallet.html, src/pages/add/create-wallet/create-wallet.ts, src/pages/add/import-wallet/import-wallet.html, src/pages/add/import-wallet/import-wallet.scss, src/pages/add/import-wallet/import-wallet.ts, src/pages/add/join-wallet/join-wallet.html, src/pages/add/join-wallet/join-wallet.ts, src/pages/integrations/coinbase/coinbase-settings/coinbase-settings.ts, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/integrations/shapeshift/shapeshift-settings/shapeshift-settings.ts, src/pages/integrations/shapeshift/shapeshift.ts, src/pages/paper-wallet/paper-wallet.ts, src/pages/send/confirm/confirm.ts
* Fix import that could freeze the app after 2 or 3 wallets imported.
* Remove buttons from create/join/import views due to incompatibility with virtual keyboard on iOS. Moved to top-right.
=> fix(iOS): show virtual keyboard without padding and move buttons to top-right

src/providers/gift-card/gift-card.ts
Ensure brands that start with numbers are always listed last.
=> Order card brands starting with numbers last

src/app/app.scss
replaced by `-webkit-mask-box-image`
=> fix(icon-plus): mask-image doesn't work on iOS

src/providers/profile/profile.ts
same logic of "create wallet" but for "join wallet": Test until a free account number is found.
=> test accounts when joinning a new wallet

src/app/app.component.ts, src/pages/add-wallet/add-wallet.ts, src/pages/add/add.ts, src/pages/add/create-wallet/create-wallet.ts, src/pages/add/join-wallet/join-wallet.ts, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-duplicate/wallet-duplicate.ts, src/providers/incoming-data/incoming-data.spec.ts, src/providers/incoming-data/incoming-data.ts
This PR fixes different cases when scan an invitation from general scanner:
1) If you have enabled `allowMultiplePrimaryWallets`, redirects to "add wallet page" before "join page", so you can choose between your different seeds or create a new one.
2) If you have disabled `allowMultiplePrimaryWallets`, redirects to "join page" directly and uses the same (and the only) seed that you have
=> Fix: go to "add wallet" before "join page" using the general scan

.gitignore, app-template/apply.js, app-template/build-electron-template.js, package.json
New versions of `electron-builder` uses JS API instead yards in package.json.
=> fix(electron-builder): Upgrade deprecated method to build the app

src/pages/send/choose-fee-level/choose-fee-level.ts
To prevent the switch from always going to default case
=> Fix: switch in choose fee level page

src/pages/home/home.html, src/pages/home/home.scss, src/pages/home/home.ts, src/providers/profile/profile.ts
Wallets groups renamed from "Group n" to "Key n" (This will be done in another PR: https://github.com/bitpay/copay/pull/10197)
Key labels in home page
Collapsibility of wallets groups
Legacy tag added for groups that don't allow adding new accounts
Remove unnecessary code
=> Feat: key labels and collapsibility

src/pages/home/home.ts, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/integrations/invoice/confirm-invoice/confirm-invoice.ts, src/providers/incoming-data/incoming-data.ts
Payment Codes for ETH does not have BIP73 property, instead EIP681.
```
paymentCodes": {
"BTC": {
"BIP72b": "bitcoin:?r=https://test.bitpay.com/i/5d2KQ8rFWCHUnv6tQjmvcQ",
"BIP73": "https://test.bitpay.com/i/5d2KQ8rFWCHUnv6tQjmvcQ"
},
"BCH": {
"BIP72b": "bitcoincash:?r=https://test.bitpay.com/i/5d2KQ8rFWCHUnv6tQjmvcQ",
"BIP73": "https://test.bitpay.com/i/5d2KQ8rFWCHUnv6tQjmvcQ"
},
"ETH": {
"EIP681": "ethereum:?r=https://test.bitpay.com/i/5d2KQ8rFWCHUnv6tQjmvcQ"
}
},
```
=> Use correct PayProUrl for ETH on invoice

src/pages/home/home.ts, src/pages/integrations/invoice/confirm-invoice/confirm-invoice.html, src/pages/integrations/invoice/confirm-invoice/confirm-invoice.scss, src/pages/integrations/invoice/confirm-invoice/confirm-invoice.ts, src/providers/incoming-data/incoming-data.ts, src/providers/invoice/invoice.ts
- Deprecated`/invoiceData/` api route, does not provide `CORS` headers anymore, so we cannot use this route in Copay. Uses alternative `/invoices/` route.
The difference is `{ org, buyer }` is not returned from so we do not know if an email is set and we cannot set the `buyerProvidedEmail`. 
Also the merchant name is not known since `org` is not returned.
`confirm-invoice.ts`
- Removed `invoiceName`, anything related to `email`, `merchantEmail`, `buyerProvidedEmail`.
- Removed email field (will be replaced with BitPay ID soon).
=> Update BitPay Invoice URI flow

src/pages/add-wallet/add-wallet.html, src/pages/add-wallet/add-wallet.ts, src/pages/home/home.html, src/pages/home/home.ts, src/pages/includes/eth-live-card/eth-live-card.html, src/pages/includes/eth-live-card/eth-live-card.scss
Improvements to the "Add eth wallet" flow:
- the user has only 1 single seed key now. In which case it can go ahead and add the eth wallet to that group.
- if the user has multiple single seed keys, it goes to the “select which key to add to” page, and creates an eth wallet there.
Correction in card texts
Fix to center the icon
=> Fix: "eth live card" improvements

app-template/config-template.xml, build-extras.gradle, package.json
Part of code has been commented to support Android 9 after 1st November.
=> chore(cordova-android): adds compatibility for android 6 or higher

src/pages/add/import-wallet/import-wallet.ts, src/pages/pages.ts, src/pages/settings/wallet-group-settings/wallet-group-qr-export/wallet-group-qr-export.html, src/pages/settings/wallet-group-settings/wallet-group-qr-export/wallet-group-qr-export.scss, src/pages/settings/wallet-group-settings/wallet-group-qr-export/wallet-group-qr-export.ts, src/pages/settings/wallet-group-settings/wallet-group-settings.html, src/pages/settings/wallet-group-settings/wallet-group-settings.ts
1) The option to export the key as a QR code will appear in:
`Settings -> Key Settings -> Advanced -> Export Key with QR`
2) This option will only be seen if:
- The key backup is done
- The key has mnemonics
3) When scanning the QR, from the general scanner of the app -> It takes you to import and autocomplete the words
4) When scanning the QR from the import scanner -> that autocompletes the words
=> Feat: QR code Key export

src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts, src/providers/paypro/paypro.spec.ts
The tests were obsolete causing many warnings
=> Fix: PayPro Provider unit tests

src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.html, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts
- PayProV2 - selectPaymentOptions sets the `buyerSelectedTransactionCurrency` now.
- Change UI to match `confirm-card-purchase.html`:
- Hides `Network cost` if `0`
- Total is now: ~~1 USD (0.12345 ETH)~~ => `0.12345 ETH ~ 1 USD`
=> Fix(card) - UI changes and remove buyerSelectedTransactionCurrency

src/pages/includes/txp/txp.html, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/send/confirm/confirm.ts, src/pages/tx-details/tx-details.ts, src/pages/txp-details/txp-details.html, src/pages/txp-details/txp-details.ts, src/providers/tx-format/tx-format.ts
All miner fees will be based on `chain` so:
- any ERC20 token will have fees in ETH.
- any SLP tokens will have fees in BCH.
Only if utxo based coin:
- `tx.feeRatePerStr`
Also fixes `txp-details.html` & `txp.html`
- Token txp.amount is `0` USDC. Uses `tx.amountStr` instead of `tx.amount` so it displays:
~~0.00 USDC~~ => `0.00 ETH`
=> Fix(fee) - Use chain for tx.feeStr and feeRatePerStr if Utxo

src/app/app.scss, src/components/label-tip/label-tip.scss, src/pages/add-wallet/add-wallet.html, src/pages/home/home.scss, src/pages/integrations/bitpay-card/bitpay-settings/bitpay-settings.html, src/pages/integrations/coinbase/coinbase-settings/coinbase-settings.html, src/pages/integrations/coinbase/coinbase-settings/coinbase-settings.scss, src/pages/integrations/coinbase/coinbase.html, src/pages/integrations/coinbase/coinbase.scss, src/pages/integrations/gift-cards/home-gift-cards/home-gift-cards.scss, src/pages/integrations/shapeshift/shapeshift-settings/shapeshift-settings.html, src/pages/integrations/shapeshift/shapeshift.scss, src/pages/settings/advanced/advanced.html, src/pages/settings/settings.html, src/pages/settings/wallet-group-settings/wallet-group-settings.html, src/pages/settings/wallet-group-settings/wallet-group-settings.scss, src/pages/templates/wide-header-page/wide-header-page.html, src/pages/tx-details/tx-details.html
* Fix kind of shakes if you scroll to the top on some screens
* Set a common `.activated` styling action when tap button-list
* Fix label-tip that cross over the item
* Homogenise UI settings for shapeshift, coinbase and BitPay card
* Hide Encrypt Password label-tip afte setting your own
* Fix Warning javascript: (blur) is deprecated in ion-input, use (ionBlur) instead
=> ref(UI): small bug fixes

src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.html, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts
For consistency between `bitpay-card-topup` page and `confirm-card-purchase` page
=> Hide token amount and only show USD total

src/providers/incoming-data/incoming-data.spec.ts, src/providers/incoming-data/incoming-data.ts
How to test:
Scan a bitpay invoice QR code and check how long it takes to read the qr code on `master` vs `fix/disableLoader`
=> Fix responsiveness on camera scan detection for paypro

app-template/build-electron-template.js
Needed for build macOS for MAS.
=> fix(electron-builder): adds identity to main package

src/components/info-sheet/info-sheet.html, src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.ts
relies on:
https://github.com/bitpay/bitcore/pull/2665
Changes:
Can click on balance to show total balance, available, confirming, and locked:
New Wallet State:
Activated Wallet with total balance of 20 XRP:
=> Implement activation fee 20 XRP ghost town UI

src/pages/wallet-details/wallet-details.html
- wallet-details shows total balance instead of spendable/available balance
- add info icon to open breakdown of balance details.
- changed wording and help text on XRP Minimum Balance flow:
=> Updated UI for XRP minimum balance design

src/providers/incoming-data/incoming-data.ts
Required for p2p wallet selector invoice redesign.
Main feature is for iOS to open up specifically Bitpay/Copay wallet.
Bitpay Wallet:
`bitpay://invoice?url=`
Copay Wallet:
`copay://invoice?url=`
=> P2P: Understand bitpay://invoice?url=

src/providers/currency/coin.ts
Not urgent, but a refactor to clean up paymentCodes from bitpay invoice response
```
"paymentCodes": {
"XRP": {
"BIP72b": "ripple:?r=https://staging.bitpay.com/i/5bYo33pPKhKPZb8uf1xKLU",
"BIP73": "https://staging.bitpay.com/i/5bYo33pPKhKPZb8uf1xKLU",
"RIP681": "https://staging.bitpay.com/i/5bYo33pPKhKPZb8uf1xKLU"
}
```
~~"RIP681": "https://staging.bitpay.com/i/5bYo33pPKhKPZb8uf1xKLU"~~
=> Refactor XRP paymentCode to BIP73

src/components/gift-card-discount-text/gift-card-discount-text.ts
Don't round down in concise mode for discounts under 1%
=> Fix discount formatting in card catalog

src/models/in-app-browser/in-app-browser-ref.model.ts, src/providers/external-link/external-link.ts, src/providers/in-app-browser/in-app-browser.ts
This PR is a workaround for a known cordova inappbrowser plugin issue where events are not sent to the correct window.
=> forwarding events back to ref with subject

src/models/user/user.model.ts, src/providers/bitpay-id/bitpay-id.ts, src/providers/in-app-browser/card.ts
This PR adds an optional 2fa code if present and also handles failed pairings more gracefully by closing the IAB and showing an error-default bottom sheet.
=> added optional code; added error handling if failed pairing

src/components/exchange-rates/exchange-rates.ts, src/pages/home/home.ts, src/providers/exchange-rates/exchange-rates.ts
https://github.com/bitpay/bitcore/pull/2747
1. getLastDayRates() `home.ts`
2. getPrices() `exchange-rates.ts`
=> getHistoricalRates returns CoinsMap<ApiPrice[]>

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, package-lock.json, package.json
* [FEAT] choose inputs for transaction (#10755)
* Fix: balance to show undefined in wallet details (#10763)
* [FEAT] add consolidated cards (#10762)
* added new logos
* consolidating galileo cards
* updated card fetch to use graph
* caching card data in iab session storage
* added ability to designate network when enabling card experiment
* tied updateBalance back from iab to wallet
* added slight animation to help smooth out tile/card updates
=> Bump v9.3.1-beta

src/providers/currency/coin.ts
```
"paymentCodes": {
"BUSD": {
"EIP681b": "ethereum:?r=https://test.bitpay.com/i/KZnEvLXtaL9e5yQpL5APRx"
},
```
**confirm-card-purchase.ts** LN349:
```
const paymentCode = this.currencyProvider.getPaymentCode(wallet.coin);
const protocolUrl = invoice.paymentCodes[COIN][paymentCode];
const payProUrl = this.incomingDataProvider.getPayProUrl(protocolUrl);
```
**incoming-data.ts** LN1034
```
public getPayProUrl(data: string): string {
return decodeURIComponent(
data.replace(/(bitcoin|bitcoincash|ethereum|ripple)?:\?r=/, '')
);
}
```
data is undefined as protocolUrl is undefined.
Error:
=> fix wrong payment code for BUSD

src/pages/integrations/simplex/simplex-buy/simplex-buy.ts
Bug fixed: If you go to Simplex through charts and then change the selected currency, default values are not updated
=> Fix: default values when comes from charts

src/pages/settings/about/session-log/session-log.scss, src/theme/variables.scss
This PR adds safe-bottom-area for iPhoneX in some views that contains `ion-footer` like shapeshift, buy-gift-card, session-log, etc.
=> fix(safe-area): adds padding bottom for iPhoneX

src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/send/confirm/confirm.ts, src/pages/txp-details/txp-details.ts, src/providers/incoming-data/incoming-data.spec.ts, src/providers/incoming-data/incoming-data.ts, src/providers/paypro/paypro.spec.ts, src/providers/paypro/paypro.ts
Add address param to `getPaymentDetails` for ERC20 allowance check in paypro.
Change parameters to object for easy destructuring and adding more optional params in the future.
```
getPayProDetails(params: {
paymentUrl: string;
coin: Coin;
disableLoader?: boolean;
address?: string;
attempt: number = 1
})
```
Related MR:
https://git.b-pay.net/bitpay/bitpay/-/merge_requests/5982
Bitcore:
https://github.com/bitpay/bitcore/pull/2940
=> Feat(PayPro) - Add address param to getPaymentDetails

package-lock.json, package.json
* Updates papaparse.
* npm update minimist --depth 7  to resolve 28 vulnerabilities
* npm update mkdirp --depth 9  to resolve 43 vulnerabilities
* npm update portfinder --depth 3  to resolve 1 vulnerability
* npm update terser-webpack-plugin --depth 3  to resolve 3 vulnerabilities
* npm update handlebars --depth 4  to resolve 1 vulnerability
* npm update dot-prop --depth 4  to resolve 4 vulnerabilities
* npm update http-proxy --depth 4  to resolve 2 vulnerabilities
* npm update acorn --depth 4  to resolve 4 vulnerabilities
* npm update elliptic --depth 14  to resolve 335 vulnerabilities
* npm update null --depth 3  to resolve 1 vulnerability
=> chore(npm): audit fix

src/providers/in-app-browser/in-app-browser.ts
removing event listener after IAB init to ensure one time execution
=> [FIX] IAB_INIT_CLEAR_LISTENER

utils/iab-patch.js
We should remove this patch since it could affect loading the app on first installations. 
It doesn't show the splash screen.
=> fix(android): splash screen doesn't work if App is asking camera permission

src/providers/buy-crypto/buy-crypto.ts
This feature will be disabled until Simplex ensures a stable version from its website
=> Disable SEPA bank transfer payment method

src/pages/integrations/bitpay-card/bitpay-card-intro/bitpay-card-intro.ts
This PR pauses the scanner preview after initializing it from the card intro. The purpose of calling the scanner initialization is solely to invoke a camera permission request, so it should be safe to pause it immediately after. On Android, the selfie camera was not available in the InAppBrowser until the scanner is paused. 
Tested against Pixel 3 XL / Android 11.
=> fix(bp-card-intro): release camera resources after initializing scanner

src/components/info-sheet/info-sheet.html, src/pages/buy-crypto/crypto-offers/crypto-offers.ts, src/pages/integrations/wyre/wyre.html, src/pages/send/amount/amount.ts, src/providers/incoming-data/incoming-data.ts, src/providers/wyre/wyre.ts
- Adds DAI and WBTC support to Wyre
I also tested USDC, DAI (crypto) and IDR, SAR (Fiat) that are listed as supported on the Simplex website. But they don't seem to work. That's why I didn't add them.
- Wyre's support url updated. At their request, I have removed their contact email.
- This PR also fixes an error that disable continue button in amount page when select an uncommon fiat currency
- Adds a log for certain errors in requests to Simplex
=> Feat: add DAI and WBTC support to Wyre

src/components/wallet-item-content/wallet-item-content.html, src/components/wallet-item-content/wallet-item-content.ts, src/pages/tabs/tabs.ts
Issues
* If wallet has been created recently, balance 0. After received funds, I had to restart the app to see new balance in the list of wallets.
* `hasZeroBalance` lock the value in zero, due to cached info is empty (for recently created wallet).
=> fix(wallets-tab): update balance for new wallets when receiving funds

src/pages/integrations/gift-cards/card-details/card-details.ts, src/providers/gift-card/gift-card.ts
Currently NewBlock bws events trigger a redeem request, but sometimes a whole bunch of blocks come in at the same time, each triggering a redeem request. This PR ensures redeem requests are properly debounced in such a scenario.
=> Debounce redeem calls

src/pages/buy-crypto/crypto-offers/crypto-offers.html, src/pages/buy-crypto/crypto-offers/crypto-offers.scss, src/pages/buy-crypto/crypto-offers/crypto-offers.ts, src/pages/buy-crypto/crypto-order-summary/crypto-order-summary.ts, src/pages/buy-crypto/crypto-payment-method/crypto-payment-method.html, src/pages/buy-crypto/crypto-payment-method/crypto-payment-method.ts, src/pages/exchange-crypto/exchange-checkout/exchange-checkout.ts, src/pages/home/home.ts, src/pages/home/price-page/price-page.html, src/pages/home/price-page/price-page.ts, src/pages/integrations/simplex/simplex.ts, src/pages/integrations/wyre/wyre-details/wyre-details.html, src/pages/integrations/wyre/wyre-details/wyre-details.ts, src/pages/integrations/wyre/wyre.ts, src/pages/onboarding/add-funds/add-funds.ts, src/pages/send/amount/amount.html, src/pages/wallet-details/wallet-details.ts, src/providers/incoming-data/incoming-data.ts, src/providers/wyre/wyre.ts
This PR needs: https://github.com/bitpay/bitcore/pull/3064/files
Anyway, it can be tested by sending the amount parameter with null
Fixes:
- Remove "Buy XRP" from charts page
- Wyre's redirectUrl has been fixed to return to the app after a purchase
- Crypto purchases not supported by Wyre will no longer set Apple pay by default. It will set debit card
- Now you can select the same payment method that was previously selected
- Error messages in buy crypto are now red
- The amount page button now says "Continue" (instead of "Select payment method")
Improvements:
- New analytics events to Buy / Exchange crypto with more data
- Refactored Wyre integration to work with the latest changes to its documentation.
- Consistency between the offer shown by Wyre and Simplex => Refactor in Wyre's …
=> Fixes and improvements for buy crypto

src/app/app.component.ts
- removed unused
- prevents the in app browser from pausing when lockMethod is disabled
=> [FIX] iab pause lock disabled

src/pages/integrations/gift-cards/purchased-cards/purchased-cards.ts, src/providers/gift-card/gift-card.ts
A few users have reported a bug that results in a perpetual spinner being shown when they attempt to purchase a specific gift card brand in the BitPay app which makes it impossible for them to purchase any gift cards for that particular brand. This PR fixes that issue.
=> Fix perpetual spinner when buying a gift card in some cases

package.json, src/providers/wallet/wallet.ts
Add call to clearCache endpoint from WalletTransactionHistory to clear cache from server
Need to deploy: [bitpay/bitcore#3066](https://github.com/bitpay/bitcore/pull/3066)
Have to wait to update of bitcore-wallet-client with the clearCache API function.
=> APP-72 [Feat] Call clearCache endpoint

src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/providers/wallet/wallet.ts
Fix for the perpetual spinner issue that occurs when some users try to buy a gift card but enter their encrypt password incorrectly.
Also simplifies the `publishAndSign` method in wallet provider.
=> Catch removeTx errors during gift card purchases

src/pages/send/amount/amount.html, src/pages/send/amount/amount.ts
Hiding the switcher during card tops to prevent non-USD currency rate issues.
=> [FIX] hiding switcher if cardTop

src/assets/img/default-erc20.svg, src/components/coin-icon/coin-icon.html, src/components/wallet-receive/wallet-receive.html, src/pages/add/custom-token/custom-token.ts, src/pages/add/select-currency/select-currency.html, src/pages/buy-crypto/crypto-offers/crypto-offers.html, src/pages/buy-crypto/crypto-order-summary/crypto-order-summary.html, src/pages/coin-and-wallet-selector/coin-and-wallet-selector.html, src/pages/coin-and-wallet-selector/coin-and-wallet-selector.ts, src/pages/exchange-crypto/exchange-crypto.html, src/pages/includes/multiple-outputs/multiple-outputs.html, src/pages/send/confirm/confirm.html, src/pages/token-swap/token-swap-checkout/token-swap-checkout.ts, src/providers/currency/coin.ts, src/providers/currency/currency.ts
```
address: "0xc581b735a1688071a1746c968e0798d642ede491"
decimals: 6
logoURI: "https://tokens.1inch.exchange/0xdac17f958d2ee523a2206206994597c13d831ec7.png"
name: "Euro Tether"
symbol: "EURT"
```
Sometimes contract address is not the same from the logo uri
=> [FIX] save logo uri instead of using the contract address

package-lock.json, package.json, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/send/confirm/confirm.ts, src/providers/index.ts, src/providers/providers.module.ts, src/providers/wallet/mocks/wallet.mock.ts, src/providers/wallet/wallet.ts, src/providers/zce/zce.ts
This PR enables BitPay Wallet to make ZCE-secured payments to [JSON Payment Protocol](https://github.com/bitpay/jsonPaymentProtocol/blob/master/v2/specification.md) accepting merchants and requires `Bitcore Wallet Service` to be running the following Bitcore PR: https://github.com/bitpay/bitcore/pull/3240. `Bitcore Wallet Client` and `Bitcore Lib Cash` must also be upgraded to the commit in the aforementioned Bitcore PR, which can be done by pulling the Bitcore PR and using `npm link`.
**ZCEs enable instant, incentive-secure payments on Bitcoin Cash.** ZCE-secured payments can be accepted by merchants immediately upon receipt (without the need for a 5-10 second delay to monitor the network for double-spends) and with the same finality as a 1-confirmation transaction.
1. Clone the …
=> Zero-Confirmation Escrows

src/pages/tabs/tabs.ts
Incoming blocks are currently triggering an "update home balance" calculation, but this calculation only includes wallets that match the currency of the incoming block (resulting in an incorrect total balance shown on the home tab). This PR prevents incorrect home balance calculations by ensuring that the home balance only updates when all wallets (of all currencies) are included in the total balance calculation.
=> Fix fluctuating home balance

src/pages/add/custom-token/custom-token.ts, src/pages/coin-and-wallet-selector/coin-and-wallet-selector.ts, src/pages/exchange-crypto/exchange-crypto.ts, src/pages/send/amount/amount.ts, src/pages/token-swap/token-swap-checkout/token-swap-checkout.ts, src/providers/currency/currency.ts
The error is given by the following:
We were allowing to create tokens already supported by bitpay as "Custom tokens". (USDC, DAI, ...)
There was an error in the creation of tokens when selecting a previously supported one (such as USDC) from the crypto swap feature. A confusion between the attribute ''decimal" and "decimals".
It is something rare, so there were few users reporting the error.
As a consequence, a "USDC Custom token" was saved with undefined decimals, so unitToSatoshi was undefined and when wanting to make calculations it resulted in infinite amounts.
Solution:
I have removed the tokens already supported by Bitpay from the list of custom tokens. Since they can be added on previous pages.
The data of the tokens already supported will have priority over those of the custom …
=> Fix: Prevent undefined decimals or infinite amounts for Tokens

src/providers/in-app-browser/in-app-browser.ts
Usually when the IAB emits a loaderror, we disable the IAB. Certain devices occasionally receive untrusted CA loaderrors for non-essential analytics URLs like this:  
```
{
"type": "loaderror",
"url": "https://px.ads.linkedin.com/collect/?time=12345&pid=12345&url=https%3A%2F%2Fbitpay.com%2Fwallet-card%2Fget-started&pageUrl=https%3A%2F%2Fbitpay.com%2Fwallet-card%2Fget-started&ref=&fmt=js&s=1",
"code": 0,
"sslerror": 3,
"message": "The certificate authority is not trusted"
}
```
As a workaround I've added a whitelist to prevent the IAB from being disabled for known problematic URLs so those users can still access the card feature:
`['https://www.googletagmanager.com/gtag/js', 'https://px.ads.linkedin.com/collect/']`
=> [FIX] keep card IAB alive if analytics fails

src/components/encrypt-password/encrypt-password.html, src/components/encrypt-password/encrypt-password.scss, src/components/encrypt-password/encrypt-password.ts, src/pages/add/select-currency/select-currency.ts, src/pages/onboarding/recovery-key/recovery-key.html, src/pages/onboarding/recovery-key/recovery-key.ts, src/pages/settings/key-settings/key-settings.html
- warning when setting encrypt password
- mandatory backup game if key is encrypted
- change info icon for warning icon for encrypt option on settings
=> [REF] better messaging and mandatory backup if key is encrypted

src/pages/exchange-crypto/exchange-crypto.ts
This PR solves the case in which tokens with the same currency abbreviation, but from a different chain than ERC20 are marked as supported, giving an error when obtaining the Changelly's rates for a certain pair, for example USDT
=> Fix: Changelly supported chains for swaps
