bitpay/wallet

src/js/controllers/tab-home.js, src/sass/views/tab-home.scss, www/img/icon-update.svg, www/views/tab-home.html
Fixes https://github.com/bitpay/copay/issues/4857
=> Update available - Desktop

src/js/controllers/coinbase.js, src/js/controllers/glidera.js, src/js/services/amazonService.js, src/js/services/bitpayCardService.js, src/js/services/buyAndSellService.js, src/js/services/coinbaseService.js, src/js/services/glideraService.js, src/sass/variables.scss, src/sass/views/buyandsell.scss, src/sass/views/integrations/coinbase.scss, src/sass/views/integrations/integrations.scss, src/sass/views/views.scss, www/views/amazon.html, www/views/buyandsell.html, www/views/coinbase.html, www/views/glidera.html
This PR provides a clearer Buy & Sell Bitcoin onboarding experience, and sets proper expectations earlier in the process. Also improves the onboarding for the Amazon.com gift cards integration.
=> Improve Integrations UX (Buy & Sell, Amazon)

src/js/controllers/walletDetails.js
Fixes https://github.com/bitpay/copay/issues/5411
=> Balance button hide

src/js/controllers/walletDetails.js
Wallet Details view. Related https://github.com/bitpay/copay/issues/5543
=> Load data after transition

src/sass/icons.scss, www/views/export.html, www/views/preferences.html, www/views/preferencesAdvanced.html, www/views/preferencesBwsUrl.html, www/views/preferencesDeleteWallet.html, www/views/preferencesHistory.html, www/views/preferencesInformation.html
=> Removes class duplicated and the top line from wallet icon

src/js/services/openURL.js
=> Fix URL handler for desktop

src/js/controllers/tab-receive.js
Fixes https://github.com/bitpay/copay/issues/5549
=> Update scope after delete wallet - receive tab

src/js/controllers/addresses.js, src/js/services/onGoingProcess.js, src/sass/shame.scss, www/views/activity.html, www/views/addresses.html, www/views/allAddresses.html, www/views/proposals.html, www/views/walletDetails.html
Fixes https://github.com/bitpay/copay/issues/5602
TODO: Fix the spinner freeze
* Do not block the view while sync addresses
* Isolated scan address functionality
* Add addresses cache
* Add reload button on header bar
* Smoother transition
* Fix app name if share by email (mobile)
=> Addresses view refactor

src/sass/views/wallet-backup-phrase.scss
Fixes https://github.com/bitpay/copay/issues/5609
=> Fix text overlay - passphrase

app-template/config-template.xml
Reverts bitpay/copay#5560
See #5603
=> Revert "feat(cordova): add screen privacy for iOS and Android"

src/js/controllers/backup.js, src/js/directives/copyToClipboard.js, src/js/routes.js, www/views/backup.html, www/views/preferencesLogs.html, www/views/termsOfUse.html
* Improve the performance on windows phone platform
* Remove unnecessaries directives
* Testnet > add copy to clipboard directive and avoid messages for null data
=> Scrolling and clipboard refactor

www/views/tab-receive.html
=> fix receive view flicker

src/js/controllers/tx-details.js, src/sass/views/includes/txp-details.scss
Fixes https://github.com/bitpay/copay/issues/5621
Also fix an apply error at memo update
=> Fix word-break on memo

www/views/coinbase.html
=> Coinbase: Adds exchange rate, better position

src/js/controllers/amount.js, src/js/controllers/confirm.js, src/js/controllers/tab-send.js, src/js/directives/gravatar.js, src/js/routes.js, src/sass/views/confirm.scss, www/views/amount.html, www/views/confirm.html, www/views/tab-send.html
Fixes https://github.com/bitpay/copay/issues/4846
=> Use icon properly - confirm view

src/js/services/storageService.js
Related https://github.com/bitpay/copay/issues/5620
=> Fix storage name log

src/js/controllers/tab-home.js
=> fix No wallets/card/anything in tab-home when resume app

src/js/services/incomingData.js
=> fix coinbase payment protocol

src/sass/views/addresses.scss, src/sass/views/buyandsell.scss, src/sass/views/tab-settings.scss, src/sass/views/zero-state.scss
=> use the same font size comments

www/views/preferencesHistory.html
=> Removes horizontal line for mobile

www/views/preferencesNotifications.html
Fixes https://github.com/bitpay/copay/issues/5654
=> Fix duplicated tittle - Notifications view

src/js/controllers/confirm.js, www/views/confirm.html
Closes https://github.com/bitpay/copay/issues/5575
* Toggle unit/fiat fee value
=> Show fee in fiat - Confirm view

src/sass/shame.scss, www/views/preferencesBwsUrl.html
=> style refresh icon in wallet service url view

src/js/controllers/confirm.js, src/sass/views/confirm.scss, www/views/confirm.html
Related [here](https://github.com/bitpay/copay/issues/5627). I think it's not a complete solution or upgrade for this case but definitely helps.
=> Toggle contact name/address - Confirm view

src/js/controllers/tab-home.js
Reverts bitpay/copay#5644
Not solve the problem. See #5635
=> Revert "fix No wallets/card/anything in tab-home when resume app"

src/js/controllers/addresses.js
this fix an undefined console error
=> remove unused variable

src/js/controllers/preferencesLogs.js, www/views/preferencesLogs.html
this shows share by email button if is mobile. Also remove the icons from the buttons.
=> adding missing isCordova variable

www/views/tab-send.html
Fixes https://github.com/bitpay/copay/issues/5688
=> Fix typo '/'

app-template/copay/sass/overrides.scss, src/sass/variables.scss, src/sass/views/includes/slideToAcceptSuccess.scss
#5697
* `v-button-primary-color` should be the default. (color white for button text)
=> Fix sass variables

src/js/controllers/confirm.js, src/js/controllers/feedback/complete.js, src/js/controllers/feedback/send.js, src/js/controllers/onboarding/backupRequest.js, src/js/controllers/onboarding/collectEmail.js, src/js/controllers/onboarding/disclaimer.js, src/js/controllers/onboarding/notifications.js, src/js/controllers/onboarding/welcomeController.js, src/js/routes.js, www/views/backupWarning.html, www/views/onboarding/backupRequest.html, www/views/onboarding/collectEmail.html, www/views/onboarding/disclaimer.html, www/views/onboarding/notifications.html, www/views/onboarding/tour.html
When swipe back is set false it stays that way. Way to reproduce the issue: 
Go to confirm view ( swipe back is set to false ) 
Try to use the swipe back in another view
=> Fix swipe back on ios

www/views/tab-send.html
=> fix "Transfer To Wallet" header size

src/js/controllers/tx-details.js
=> update alternative amount on tx-details view

i18n/po/ja.po, src/js/services/uxLanguage.js
I have not kept up with the codebase since switch to Bitpay style, so if there are other areas needed to be modified please let me know.
Thanks
=> Make Japanese Great Again (MJGA)

src/js/controllers/tab-send.js
Happens when you got an addressbook entry.
=> fix flash when entering send tab view

src/js/controllers/glidera.js, src/js/services/glideraService.js
* If token expired, remove it.
=> Handle Glidera errors

src/js/controllers/bitpayCardIntro.js, src/js/services/storageService.js
=> Removes old _NextStep code

src/js/controllers/tx-details.js, www/views/tx-details.html
* Transition smoother
* Show date on receive tx
* Hide creator if not shared wallet
* Pre-load exchange rate (click on alternative amount)
* Click on confirmation row to refresh tx
=> Ref tx-details

src/js/routes.js, src/js/services/incomingData.js
Fixes https://github.com/bitpay/copay/issues/5738
Tested on Android and Browser (devel)
=> Fix import QR code from main scan button

i18n/po/de.po, i18n/po/es.po, i18n/po/fr.po, i18n/po/it.po, i18n/po/ja.po, i18n/po/pl.po, i18n/po/ru.po, i18n/po/zh.po
=> Updates translation

www/views/tab-export-qrCode.html
=> fix export qr code for long strings

src/sass/views/tab-settings.scss, www/views/preferences.html
=> improve UI for pass switch when is disabled

src/js/services/popupService.js
Fixes https://github.com/bitpay/copay/issues/5611
=> Auto complete field off

src/js/controllers/preferencesFee.js, src/js/services/feeService.js
Fixes #5681.
Waiting for: https://github.com/bitpay/bitcore-wallet-service/pull/631
=> New fee level

src/js/services/onGoingProcess.js, src/js/services/profileService.js
=> remove validation for ios and wp

src/js/controllers/amount.js, src/js/controllers/buyAmazon.js, src/js/controllers/buyCoinbase.js, src/js/controllers/buyGlidera.js, src/js/controllers/sellCoinbase.js, src/js/controllers/sellGlidera.js, src/js/controllers/topup.js, src/js/routes.js, src/js/services/bitpayCardService.js, src/js/services/coinbaseService.js, src/js/services/glideraService.js, src/js/services/txFormatService.js, www/views/topup.html
=> Enable input in bits/BTC to reload the debit card

Gruntfile.js, bower.json
Old version of connect is not correctly signing transactions with version v2.
=> Using new version of connect

src/js/controllers/amount.js
Fixes #5113
Add the ability to paste with ctrl/cmd + v
=> Paste amount - Desktop

src/js/controllers/buyAmazon.js
enhanced Gift Card error, if buying fails.
=> better gift-card-err

src/js/services/incomingData.js, src/js/services/payproService.js
Fixes https://github.com/bitpay/copay/issues/5459
=> Use BIP21 params if paypro info is not complete

app-template/package-template.json, src/js/controllers/create.js, src/js/controllers/import.js, src/js/controllers/join.js, src/js/controllers/preferences.js, src/js/controllers/preferencesExternal.js, src/js/controllers/preferencesInformation.js, src/js/controllers/tab-receive.js, src/js/routes.js, src/js/services/hwWallet.js, src/js/services/intelTEE.js, src/js/services/ledger.js, src/js/services/platformInfo.js, src/js/services/profileService.js, src/js/services/trezor.js, src/js/services/walletService.js, src/sass/views/tab-receive.scss, src/sass/views/tab-settings.scss, www/img/icon-inteltee-white.svg, www/views/import.html, www/views/includes/walletInfo.html, www/views/preferences.html, www/views/preferencesExternal.html, www/views/preferencesInformation.html, www/views/tab-create-personal.html, www/views/tab-create-shared.html, www/views/tab-import-hardware.html, www/views/tab-receive.html
Relies on a simple BWC change and Intel software to drive TEE chipset.
=> Baseline Intel TEE support

src/js/controllers/tab-receive.js
=> set wallet properly when side wallets screen is activated

src/js/controllers/amount.js, src/js/controllers/topup.js, src/js/routes.js, src/js/services/sendMax.js, src/js/services/txFormatService.js
=> Feat/Enable SendMax

src/js/services/fingerprintService.js
=> Friendly error message if touch id failed

src/js/controllers/lockSetup.js, src/js/controllers/pin.js, src/js/controllers/tab-settings.js, src/js/routes.js, src/js/services/configService.js, www/views/lockSetup.html, www/views/pin.html
Fixes https://github.com/bitpay/copay/issues/5905
* Disable unselected option
* Remove popup confirmation
=> Request PIN to disable it

src/js/controllers/tab-home.js, src/sass/views/tab-home.scss, www/views/includes/wallets.html, www/views/tab-home.html, www/views/tab-receive.html, www/views/tab-settings.html
=> Revert "adding loading placeholders to avoid the screen resize in tab-home view"

src/sass/views/amount.scss, src/sass/views/feedback/complete.scss, src/sass/views/includes/walletActivity.scss, src/sass/views/onboarding/onboard-disclaimer.scss, src/sass/views/tab-receive.scss, src/sass/views/walletDetails.scss
This set of changes is intended to make copay usable for old android (4.4.2) and small devices.
=> Fix styles for old webview (android 4.4.2) and small devices

src/js/controllers/onboarding/backupWarning.js
=> Fix backup view if spending password active

src/js/controllers/amount.js, src/js/controllers/customAmount.js, src/js/controllers/tab-receive.js, src/js/routes.js, src/sass/views/custom-amount.scss, www/views/customAmount.html
=> Ref custom amount. Also fixes small screen issue

src/js/controllers/addresses.js, src/sass/views/addresses.scss, www/views/addresses.html, www/views/allAddresses.html
=> Fix view allAddresses

src/js/controllers/addresses.js, src/js/controllers/tab-receive.js, www/views/addresses.html
=> Fix addresses view. Also show adddress cached if error occurs

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json
=> New release v3.2.1

src/sass/views/includes/txp-details.scss
=> add border top to low fee warning

www/views/tab-import-phrase.html
Fix for #5947 possible recovery seed leak
=> Turn off autocomplete and autocorrect on recovery phrase input field

app-template/config-template.xml
https://github.com/fechanique/cordova-plugin-fcm/issues/306
=> Fix Android build

src/js/controllers/tx-details.js, src/js/services/walletService.js
=> Fix getTx info if it is not in cache

src/js/controllers/create.js, src/js/controllers/join.js, src/js/routes.js, src/sass/views/tab-settings.scss, www/views/join.html, www/views/tab-create-personal.html, www/views/tab-create-shared.html
=> adding verification option to passphrase and general refactor

src/js/controllers/addressbook.js, src/js/controllers/addressbookView.js, www/views/addressbook.html, www/views/addressbook.view.html
=> remove slide to delete and adding that option to addr entry view

app-template/package-template.json, src/js/controllers/tx-details.js, src/js/services/storageService.js, src/js/services/txConfirmNotification.js, src/sass/views/includes/txp-details.scss, www/views/tx-details.html
=> Notify when a tx has been confirmed

src/js/controllers/bitpayCard.js, src/js/services/bitpayCardService.js, src/sass/views/bitpayCard.scss, www/views/bitpayCard.html, www/views/includes/cardActivity.html, www/views/modals/bitpay-card-confirmation.html, www/views/topup.html
Still missing "View Confirmation Status" label. The transaction id is not coming on the invoice request.
=> improvements on the card UI

www/img/address-book-add.svg
=> fix address book icon disappearance after the scanner is used

app-template/config-template.xml
=> Revert "Problem opening Copay on Android from another Cordova app"

src/js/controllers/buyCoinbase.js, src/js/services/coinbaseService.js
See:
https://github.com/bitpay/copay/issues/6157
=> get updated buy order if it does not initally include a transaction

src/js/services/applicationService.js, www/views/modals/fingerprintCheck.html
=> dummy view/state if the fingerprint check fails

src/js/controllers/import.js, src/js/services/trezor.js
Fix Trezor / Ledger signing on multisig wallet, when account > 1 and after the wallet was imported.
=> fix account setting in Trezor/Ledger

i18n/po/template.pot, src/js/controllers/topup.js, src/js/directives/countdown.js, src/js/services/onGoingProcess.js, src/sass/views/bitpayCard.scss, www/views/topup.html
* Invoice details (fee and total to send)
* Countdown for expiring invoice
* Show popup warning with transaction fee before confirm.
* Add strings to translate
* Refactor Topup controller
Bitcoin Transaction
=> Debit card: topup improvements

src/js/controllers/confirm.js, src/js/controllers/paperWallet.js, src/js/controllers/preferencesFee.js, src/js/directives/clickToAccept.js, src/js/directives/noLowFee.js, src/js/directives/slideToAccept.js, src/js/services/bwcError.js, src/js/services/feeService.js, src/js/services/sendMax.js, www/views/buyAmazon.html, www/views/buyCoinbase.html, www/views/buyGlidera.html, www/views/confirm.html, www/views/includes/clickToAccept.html, www/views/modals/chooseFeeLevel.html, www/views/modals/paypro.html, www/views/sellCoinbase.html, www/views/sellGlidera.html, www/views/topup.html
=> Confirm controller refactor

src/js/controllers/join.js
=> fix 'account invalid number' error  when join by using ledger source

Gruntfile.js
`grunt watch` watches *.po files for changes and runs `nggettext_compile`
=> Watch i18n files

src/js/controllers/buyCoinbase.js, src/js/services/coinbaseService.js
* Check if amount is enough to cover the bitcoin fee
* Reduce amount to pay bitcoin fee
Note: After buy bitcoin through Copay integration, in Coinbase side, it tries to create a transaction to transfer the bitcoins bought to your Copay wallet. As all bitcoin transactions, these have a network fee that must be paid with your funds.
=> Coinbase (purchase flow): adds bitcoin fee to create transaction

www/views/modals/chooseFeeLevel.html
fixes https://github.com/bitpay/copay/issues/6309
=> fix "save" button

src/js/controllers/modals/txpDetails.js, www/views/modals/txp-details.html
=> fix copayers actions list update and message when success view is shown

src/js/routes.js, src/sass/views/starting.scss
=> changing starting label for spinner

www/views/includes/bitpayCardsCard.html, www/views/includes/buyAndSellCard.html, www/views/includes/homeIntegrations.html, www/views/includes/nextSteps.html, www/views/tab-home.html
=> fix padding between cards

src/js/services/popupService.js
=> 	avoid default title and fixes for buttons translations

src/js/controllers/paperWallet.js
=> fix sweep paper wallet

src/js/services/popupService.js
=> fix button order

src/js/controllers/confirm.js, src/js/controllers/preferencesFee.js, src/js/services/feeService.js, src/sass/views/tab-settings.scss, www/views/modals/chooseFeeLevel.html, www/views/preferencesFee.html
=> custom fee feature

app-template/bitpay/appConfig.json, app-template/config-template.xml, app-template/copay/appConfig.json, src/js/controllers/walletDetails.js, src/sass/variables.scss
=> fix status bar color for android devices

src/js/controllers/confirm.js, src/js/controllers/preferencesNotifications.js, src/js/controllers/tx-details.js, src/js/services/configService.js, www/views/preferencesNotifications.html, www/views/tx-details.html
=> Confirmed transactions notifications as global settings

src/sass/views/tab-settings.scss, www/views/preferences.html
=> remove color note and align slider buttons

src/js/controllers/preferencesDelete.js, www/views/preferencesDeleteWallet.html
=> hide wallet name if alias exists

www/views/preferences.html
=> fix wallet name on settings

src/js/services/profileService.js
=> use app name for err message

src/js/services/coinbaseService.js
=> Coinbase: adds 2fa without user interaction

src/js/controllers/preferencesAltCurrency.js, src/sass/views/tab-settings.scss, www/views/preferencesAltCurrency.html
=> Feat: support ISO_4217 currency codes when searching

src/js/controllers/walletDetails.js, src/sass/views/walletDetails.scss, www/views/includes/walletInfo.html, www/views/walletDetails.html
* Removes unused HTML code
* Fix CSS style for error messages
=> Bug fixes UI from walletDetails

src/js/controllers/confirm.js
Fixes https://github.com/bitpay/copay/issues/6704
=> Fix send max changing fee level on desktop

www/views/includes/walletInfo.html, www/views/walletDetails.html
=> Fix Android compatibility: walletDetails view

src/js/controllers/cashScan.js, src/sass/views/cashScan.scss, src/sass/views/wallet-backup-phrase.scss, www/views/backup.html, www/views/cashScan.html
=> Fix bch view and bch backup message

www/views/tab-settings.html
=> Fix icon and wallet color from settings view

src/sass/views/tab-settings.scss, www/views/preferencesCash.html
=> add scan option and remove button

www/views/walletDetails.html
=> Fix walletDetails view when error occurs

Gruntfile.js
To prevent https://github.com/bitpay/copay/issues/6796#issuecomment-334748320
Fixes https://github.com/bitpay/copay/issues/6796
=> add default to chrome target

src/assets/icon/icon-wallet.svg, src/pages/home/home.html, src/pages/home/home.scss
=> ref home style

src/js/services/walletService.js
Fixes: https://github.com/bitpay/copay/commit/40ff5364f727a9c57d9e40e269124463d60ae643#diff-97c822aa8528c5c90cd7afe5c34c69a5L194
=> Fix: missing variable in wallet service

app-template/package-template.json, bower.json
=> Bower: fix ionic resolution. Also updates bower package

src/theme/variables.scss
=> fix item arrow

app-template/package-template.json
Reverts bitpay/copay#6995
There are tons of changes. We need to test a little more before merge on `master`.
=> Revert "Updates bitcore-wallet-client"

src/app/app.component.html, src/app/app.component.ts, src/app/services/data-services.service.ts, src/styles.scss
Needs https://github.com/bitpay/bitcore-wallet-service/pull/717
=> Add bch stats - clean code

src/pages/home/home.html, src/pages/home/home.scss, src/pages/home/home.ts, src/theme/variables.scss
* Use app color for active tab
* Use app color for wallet icons
* Display [m-n] for shared wallets
* Show status string properly
=> Refactor home view

src/app/app.module.ts, src/assets/img/icon-tx-sent-outline.svg, src/pages/choose-fee-level/choose-fee-level.html, src/pages/choose-fee-level/choose-fee-level.ts, src/pages/paypro/paypro.html, src/pages/paypro/paypro.ts, src/pages/receive/custom-amount/custom-amount.ts, src/pages/receive/receive.ts, src/pages/send/amount/amount.html, src/pages/send/amount/amount.ts, src/pages/send/confirm/confirm.html, src/pages/send/confirm/confirm.ts, src/pages/send/send.html, src/pages/send/send.scss, src/pages/send/send.ts, src/providers/config/config.ts, src/providers/external-link/external-link.ts, src/providers/fee/fee.ts, src/providers/incoming-data/incoming-data.ts, src/providers/node-webkit/node-webkit.ts, src/providers/on-going-process/on-going-process.ts, src/providers/paypro/paypro.ts, src/providers/popup/popup.ts, src/providers/rate/rate.ts, src/providers/tx-confirm-notification/tx-confirm-notification.ts, src/providers/tx-format/tx-format.ts, src/providers/wallet/wallet.spec.ts, src/providers/wallet/wallet.ts
Component implemented:
- Confirm
- Amount
Providers implemented: 
- External-link provider
- Fee provider
- Tx-confirm-notification provider
- Node-webkit provider
types for:
- tx-format provider
fixes for:
- popup provider
- incoming data
- Send: 'Transfer to wallet' list
=> Feat: Confirm

package.json, src/app/app.module.ts, src/assets/img/address-book-add.svg, src/pages/addressbook/add/add.html, src/pages/addressbook/add/add.scss, src/pages/addressbook/add/add.ts, src/pages/addressbook/addressbook.html, src/pages/addressbook/addressbook.scss, src/pages/addressbook/addressbook.ts, src/pages/addressbook/view/view.html, src/pages/addressbook/view/view.scss, src/pages/addressbook/view/view.ts, src/pages/send/send.html, src/pages/send/send.scss, src/pages/settings/settings.ts, src/providers/address-book/address-book.ts, src/validators/address.ts
* Address book main page (add, view, remove, search)
* Adds bitcoin address **validator**
* Fix addressbookProvider
=> V4-11: Addressbook

i18n/po/fr.po
> "Si cet appareil est remplacé ou si cette appli est supprimée, ni vous ni BitPay ne **peuvent** récupérer vos fonds sans une sauvegarde."
"Si cet appareil est remplacé ou si cette appli est supprimée, ni vous ni BitPay ne **pouvez** récupérer vos fonds sans une sauvegarde."
> "Bitcoin est différent &ndash; il ne peut pas être conservé en toute sécurité avec un service internet ou bancaire."
> "Les bitcoins sont particuliers &ndash; ils ne peuvent pas être stockés en toute sécurité sur un service internet ou bancaire."
> "Verrouiller l'appli"
> "Verrouillage de l'application"
> "**ajoutez** vos cartes BitPay Visa"
> "**ajouter** vos cartes BitPay Visa"
It would be nice to have that in the next update.
Keep up the good work for the V4 👍
=> Update French from Crowdin

src/js/controllers/preferencesPrivateKey.js
* only mobile (and also Request Fingerprint enabled)
=> Fixes: show xpriv key if touch-id enabled

src/pages/add/add.ts, src/pages/add/create-wallet/create-wallet.html, src/pages/add/create-wallet/create-wallet.ts, src/pages/add/import-wallet/import-wallet.ts, src/pages/home/home.html, src/pages/home/home.ts, src/providers/on-going-process/on-going-process.ts
- Create page improved: Creation of BCH wallets
- Home shows BCH wallets
- To do: Invitation view for shared wallets
=>  [V4] Feat: Create wallet

i18n/po/de.po, i18n/po/ja.po, i18n/po/pt.po
=> Fix translations (DE, JA). Updates PT

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json
* Fix translations
* Fix Payment Protocol URL for non-backwards-compatible requests
=> Bump v3.9.1

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, src/js/services/mercadoLibreService.js
=> Revert "Feat/meli enabled 01"

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, src/js/controllers/customAmount.js, src/js/controllers/tab-receive.js, src/js/services/walletService.js
Fixes https://github.com/bitpay/copay/issues/7855
=> fix qr case

src/app/app.module.ts, src/pages/integrations/coinbase/coinbase-settings/coinbase-settings.html, src/pages/integrations/coinbase/coinbase-settings/coinbase-settings.scss, src/pages/integrations/coinbase/coinbase-settings/coinbase-settings.ts, src/pages/integrations/glidera/glidera-settings/glidera-settings.html, src/pages/integrations/glidera/glidera-settings/glidera-settings.scss, src/pages/integrations/glidera/glidera-settings/glidera-settings.ts, src/pages/integrations/glidera/glidera.html, src/pages/integrations/glidera/glidera.scss, src/pages/settings/settings.html, src/pages/settings/settings.scss, src/pages/settings/settings.ts, src/providers/coinbase/coinbase.ts, src/providers/glidera/glidera.ts, src/providers/home-integrations/home-integrations.ts
* Also order by name the list of services
=> [v4] Settings Integrations (Glidera/Coinbase)

src/pages/home/activity/activity.html, src/pages/includes/txp/txp.scss
=> [v4] Fix: Styles for recent Txs

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, app-template/package-template.json, src/js/controllers/buyAmazon.js, src/js/controllers/buyMercadoLibre.js, src/js/controllers/modals/txpDetails.js, src/js/controllers/topup.js, src/js/services/incomingData.js, src/js/services/payproService.js, src/sass/views/includes/txp-details.scss, www/views/modals/txp-details.html
If the BitPay.com invoice has BCH turned on, this PR prevents to get an error while trying to top-up (with BTC).
=> [v3] Set transactionCurrency to create BitPay invoice

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, package-lock.json, package.json, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts
=> [v4] Fix send max on top-ups

README.md
=> Fix formatting of table in README

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, src/js/controllers/buyAmazon.js, src/js/controllers/buyMercadoLibre.js, src/js/controllers/confirm.js, src/js/controllers/topup.js, src/js/services/incomingData.js, src/js/services/walletService.js
* Also fixes required_fee_rate for BCH invoices
=> V3 - Remove tx if broadcast fail (Paypro requests)

src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-information/wallet-information.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-information/wallet-information.scss
Extended public key wrapped and index fixed when wallet is shared
=> FIX: extended public key wrapped

src/pages/includes/wallet-selector/wallet-selector.scss, src/pages/paypro/paypro.html, src/pages/paypro/paypro.scss, src/pages/paypro/paypro.ts, src/pages/send/confirm/confirm.ts
=> fix: cash addr format fixed on payment protocol info

src/pages/feedback/feedback-complete/feedback-complete.scss, src/pages/send/send.html, src/pages/send/send.scss, src/providers/wallet/wallet.ts
- Feedback UI
- Send input for android
- Address generation on receive
=> Fix: styles and behaviors

.gitignore, src/pages/add/create-wallet/create-wallet.html, src/pages/add/create-wallet/create-wallet.ts, src/pages/send/confirm/confirm.ts, src/pages/txp-details/txp-details.ts, src/providers/incoming-data/incoming-data.ts
- Add BCH testnet support
- This needs latest BWS (not yet installed): https://github.com/bitpay/bitcore-wallet-service/pull/772
=> Add testnet support to incomming data + create

src/app/app.scss, src/directives/copy-to-clipboard/copy-to-clipboard.ts, src/providers/touchid/touchid.ts
=> REF: Avoid toast to cover nav header

src/app/app.scss, src/pages/home/home.html, src/pages/home/home.scss, src/pages/includes/incoming-data-menu/incoming-data-menu.ts, src/pages/onboarding/backup-request/backup-request.html, src/pages/onboarding/backup-request/backup-request.scss, src/pages/onboarding/tour/tour.html, src/pages/onboarding/tour/tour.scss
Fix for:
- Home page: 
Solve the problem of the small white screen when trying to update the page, scrolling down
The color portion on the bottom of the components on certain occasions
The view when there are no wallets
- Onboarding for small devices
- Warnings
=> Fix: Home style bugs

.circleci/config.yml, .vscode/extensions.json, .vscode/settings.json, README.md, src/app/app.module.ts, src/app/app.scss, src/components/components.module.ts, src/components/expandable-header/expandable-header.scss, src/components/expandable-header/expandable-header.ts, src/directives/ios-scroll-bg-color/ios-scroll-bg-color.ts, src/directives/navbar-bg/navbar-bg.ts, src/pages/home/home.scss, src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.scss, src/providers/app/app.ts, src/providers/profile/profile.ts, src/providers/release/release.ts, src/providers/touchid/touchid.ts, src/providers/wallet/wallet.spec.ts, src/tsconfig.spec.json
=> Collapsible Wallet Balance

src/components/expandable-header/expandable-header.spec.ts, src/components/expandable-header/expandable-header.ts, src/directives/ios-scroll-bg-color/ios-scroll-bg-color.spec.ts, src/directives/ios-scroll-bg-color/ios-scroll-bg-color.ts, src/directives/navbar-bg/navbar-bg.spec.ts, src/directives/navbar-bg/navbar-bg.ts
Gets the following components and directives (added in https://github.com/bitpay/copay/pull/8457) up to 100% test coverage:
`ExpandableHeaderComponent`
`IosBgScrollColor`
`NavbarBg`
The directives, in particular, rely on ionic to generate elements in a very specific way to work properly, so these tests will immediately alert us if an ionic update breaks these directives.
=> Collapsible Wallet Balance Tests

app-template/package-template.json
This version has removed the logs.
=> Fix: QR scanner version for desktop is updated

src/pages/integrations/shapeshift/shapeshift.html, src/pages/tx-details/tx-details.html, src/pages/tx-details/tx-details.scss, src/pages/txp-details/txp-details.html, src/pages/txp-details/txp-details.scss
=> Fix: Timeline for tx details and txp details

src/pages/tx-details/tx-details.html, src/pages/tx-details/tx-details.ts
To do when possible get the fiat rate of bitcoin cash
=> Fix: Code to show fiat rate commented

src/app/app.component.ts, src/pages/tabs/tabs.html, src/pages/tabs/tabs.ts
Ensure scanner turns back on after scanning a QR code, then returning to the scan view.
=> Fix scan view after handling incoming data

src/app/app.scss, src/pages/home/home.html, src/pages/includes/txp/txp.html, src/pages/includes/wallet-activity/wallet-activity.html, src/pages/includes/wallet-selector/wallet-selector.html, src/pages/receive/receive.html, src/pages/send/send.html, src/pages/settings/settings.html, src/pages/settings/wallet-settings/wallet-settings-advanced/bitcoin-cash/bitcoin-cash.html, src/pages/wallet-details/wallet-details.html
=> FIX: ios 10.3.1 icons not aligned

src/pages/includes/txp/txp.html, src/pages/includes/txp/txp.scss, src/pages/includes/wallet-activity/wallet-activity.html, src/pages/includes/wallet-activity/wallet-activity.scss
=> Fixes for recent and txps transactions cards

src/pages/includes/txp/txp.html, src/pages/includes/txp/txp.scss, src/pages/includes/wallet-activity/wallet-activity.html, src/pages/includes/wallet-activity/wallet-activity.scss
=> Revert "Fixes for recent and txps transactions cards"

src/pages/includes/txp/txp.html, src/pages/includes/txp/txp.scss, src/pages/includes/wallet-activity/wallet-activity.html, src/pages/includes/wallet-activity/wallet-activity.scss
=> Fixes for recent transactions and transaction proposals card

src/pages/send/amount/amount.ts, src/providers/incoming-data/incoming-data.ts
=> FIX: handle URI with message and not amount

src/pages/includes/txp/txp.html, src/pages/includes/txp/txp.scss, src/pages/includes/wallet-activity/wallet-activity.html, src/pages/includes/wallet-activity/wallet-activity.scss, src/pages/integrations/bitpay-card/bitpay-settings/bitpay-settings.html, src/pages/integrations/bitpay-card/bitpay-settings/bitpay-settings.scss
=> Fix UI: BitPay Card Settings and Home (TX and TXP)

src/pages/includes/wallet-item/wallet-item.html, src/pages/includes/wallet-item/wallet-item.scss, src/pages/settings/about/about.html, src/pages/settings/wallet-settings/wallet-settings-advanced/bitcoin-cash/bitcoin-cash.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-addresses/wallet-addresses.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-delete/wallet-delete.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-export/wallet-export.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-information/wallet-extended-private-key/wallet-extended-private-key.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-information/wallet-extended-private-key/wallet-extended-private-key.scss, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-information/wallet-extended-private-key/wallet-extended-private-key.ts, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-information/wallet-information.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-service-url/wallet-service-url.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-settings-advanced.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-transaction-history/wallet-transaction-history.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-transaction-history/wallet-transaction-history.scss, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-transaction-history/wallet-transaction-history.ts, src/pages/settings/wallet-settings/wallet-settings.html
=> Ref wallet-settings 03

src/pages/home/home.html, src/pages/home/home.scss
=> Fix: Wallet ready card styles

src/pages/feedback/feedback-complete/feedback-complete.html, src/pages/feedback/send-feedback/send-feedback.html, src/pages/integrations/amazon/amazon-card-details/amazon-card-details.html, src/pages/integrations/bitpay-card/bitpay-card-intro/bitpay-card-intro.html, src/pages/integrations/coinbase/coinbase-tx-details/coinbase-tx-details.html, src/pages/integrations/glidera/glidera-tx-details/glidera-tx-details.html, src/pages/integrations/glidera/glidera.html, src/pages/integrations/mercado-libre/mercado-libre-card-details/mercado-libre-card-details.html, src/pages/integrations/shapeshift/shapeshift-details/shapeshift-details.html, src/pages/onboarding/tour/tour.html, src/pages/paypro/paypro.html, src/pages/pin/pin-modal/pin-modal.html, src/pages/receive/custom-amount/custom-amount.html, src/pages/receive/receive.html, src/pages/send/choose-fee-level/choose-fee-level.html, src/pages/settings/about/session-log/session-log.html, src/pages/settings/addressbook/addressbook.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-addresses/all-addresses/all-addresses.html, src/pages/txp-details/txp-details.html, src/pages/txp-details/txp-details.scss, src/pages/wallet-details/search-tx-modal/search-tx-modal.html, src/pages/wallet-details/wallet-details.html
=> REF: improve txp detail UI

src/pages/feedback/feedback-complete/feedback-complete.html, src/pages/feedback/feedback-complete/feedback-complete.ts
All apps are showed on Share Page. If one of them is not available, the app shows a message after tapping.
=> REF: Show all the apps for default on share page

src/pages/integrations/amazon/amazon-settings/amazon-settings.html, src/pages/integrations/amazon/amazon-settings/amazon-settings.ts, src/pages/integrations/amazon/buy-amazon/buy-amazon.ts, src/providers/amazon/amazon.ts, src/providers/persistence/persistence.ts
Feedback and wording suggestions are welcome.
=> New requirement for Amazon purchases: email address

src/pages/integrations/amazon/amazon-card-details/amazon-card-details.ts, src/pages/send/amount/amount.html
- Handle error 500 when canceling GC
- Amazon Japan: Disable next button if user enter decimal value
=> Fix: Amazon bugs

src/pages/add/copayers/copayers.html, src/pages/add/create-wallet/create-wallet.ts, src/pages/add/join-wallet/join-wallet.ts, src/pages/receive/receive.html, src/pages/receive/receive.ts
Also:
- Prevent double buttons to close
- Copayers header color
- Unnecessary code removed
=> Fix: Copayers view as a modal

src/components/info-sheet/info-sheet.html, src/pages/receive/custom-amount/custom-amount.html, src/pages/receive/custom-amount/custom-amount.scss, src/pages/receive/custom-amount/custom-amount.ts, src/pages/send/amount/amount.html, src/pages/send/amount/amount.ts, src/providers/action-sheet/action-sheet.ts
=> REF: request specific amount view

src/app/app.scss, src/components/info-sheet/info-sheet.html, src/pages/add/copayers/copayers.html, src/pages/add/copayers/copayers.scss, src/pages/add/copayers/copayers.ts, src/pages/receive/custom-amount/custom-amount.html, src/pages/receive/custom-amount/custom-amount.scss, src/pages/receive/receive.html, src/pages/receive/receive.scss, src/pages/wallet-details/wallet-details.scss, src/providers/action-sheet/action-sheet.ts
=> REF: copayers view

src/pages/integrations/shapeshift/shapeshift-confirm/shapeshift-confirm.html, src/pages/integrations/shapeshift/shapeshift-confirm/shapeshift-confirm.scss, src/pages/integrations/shapeshift/shapeshift-confirm/shapeshift-confirm.ts, src/pages/integrations/shapeshift/shapeshift-details/shapeshift-details.html, src/pages/integrations/shapeshift/shapeshift-details/shapeshift-details.scss, src/pages/integrations/shapeshift/shapeshift-details/shapeshift-details.ts, src/pages/integrations/shapeshift/shapeshift.html, src/pages/integrations/shapeshift/shapeshift.scss, src/providers/on-going-process/on-going-process.ts
* Check if send-max from Wallet exceeds maximum or it 's below minimum allowed by ShapeShift.
* User can cancel shift in last step (confirm view)
* Little refactor of UI to align to the new design
* Adds spinner while loading send-max values
=> Ref ShapeShift UI. Fix send max for minimum and maximum values

src/pages/send/confirm/confirm.html, src/pages/send/confirm/confirm.ts, src/pages/tx-details/tx-details.html, src/pages/tx-details/tx-details.ts, src/pages/txp-details/txp-details.html, src/pages/txp-details/txp-details.ts, src/providers/tx-format/tx-format.ts
Also, fixes for the sending image on tx-details
=> FIX: symbols for alternative coins removed

src/pages/send/confirm/confirm.scss, src/pages/send/send.html, src/pages/send/send.scss, src/pages/send/send.ts, src/pages/settings/addressbook/add/add.ts, src/providers/address/address.ts, src/theme/variables.scss, src/validators/address.ts
In this PR:
- Coin and Network validation in search input of send page to prevent user mistakes
- Refactor of address validation
- Now you can add a testnet Bitcoin Cash address as a contact
- Refactor of input process for searchs in send page
- Added search by wallet
- Fix for validators of add contact page
=> Feat: Coin and Network validation in search input of send page

src/providers/incoming-data/incoming-data.spec.ts, src/providers/incoming-data/incoming-data.ts
- Removed ionicAlert dependencies.
=> Refactor incoming-data. Split redirect function

src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.html, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.scss, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts
=> Feat: 'network cost' and 'miner fee' external links for card top up page

src/pages/home/home.html
=> FIX: Put new sentences/words on new line in Japanese translation

src/components/info-sheet/info-sheet.html, src/pages/send/send.ts, src/providers/action-sheet/action-sheet.ts, src/providers/incoming-data/incoming-data.ts
=> FEAT: show message when an user use a legacy BCH address

src/pages/integrations/amazon/amazon.ts
This issue only happened on mobile.
=> Fix(Amazon main view): Do open card after purchasing

src/providers/tx-format/tx-format.spec.ts, src/providers/tx-format/tx-format.ts
Also: Fix for amounts of 4 or more digits, when the onlyIntegeres option is used
=> test: Unit tests for tx-format provider

src/app/app.scss, src/components/clipboard-card/clipboard-card.html, src/components/clipboard-card/clipboard-card.scss, src/pages/home/home.spec.ts, src/pages/home/home.ts
1. Improves the styling of the clipboard card on iOS
2. Hides the clipboard card if the paypro request returns an error
3. Ignores raw btc/bch addresses for now (based on user feedback)
=> Clipboard Card Improvements

src/pages/send/amount/amount.html, src/pages/send/amount/amount.ts, src/pages/send/send.html, src/pages/send/send.ts
Now that the send tab no longer shows the amount page, we need to move the zero state on the amount page (shown when the user has no funds in their wallet) to the send page.
=> Fix: Send Page Zero State

src/app/app.scss, src/pages/home/home.html, src/pages/home/home.scss, src/pages/receive/receive.html
=> Home zero state

src/components/info-sheet/info-sheet.html, src/components/wallet-selector/wallet-selector.html, src/pages/home/home.html, src/pages/integrations/shapeshift/shapeshift-shift/shapeshift-shift.html, src/pages/receive/receive.html, src/pages/send/send.html, src/pages/settings/wallet-settings/wallet-settings.html, src/pages/wallet-details/wallet-details.ts, src/providers/action-sheet/action-sheet.ts
- replace "Paper Key Unverified" for "Needs Backup"
- replace "paper key" for "recovery phrase"
- replace "Paper/Master Key" option in settings for "Backup"
=> REF: use old strings related to the 12 words phrase

src/components/info-sheet/info-sheet.html, src/pages/receive/custom-amount/custom-amount.html, src/pages/receive/custom-amount/custom-amount.scss, src/pages/receive/custom-amount/custom-amount.ts, src/providers/action-sheet/action-sheet.ts
=> Ref: Custom Amount Page

src/pages/send/amount/amount.html, src/pages/send/amount/amount.scss
=> Fix: Style for the unit in Amount Page

src/pages/send/send.html, src/pages/send/send.scss
=> Disabled style for wallets that needs backup or are incomplete

src/pages/includes/feedback-card/feedback-card.html, src/pages/includes/feedback-card/feedback-card.scss
=> FIX: Changes in the style of the card to unify styles

src/pages/home/home.html, src/pages/home/home.scss, src/pages/home/home.ts
=> FEAT: animation to clipboard card

src/components/wallet-selector/wallet-selector.html, src/pages/add/create-wallet/create-wallet.ts, src/pages/home/home.html, src/pages/paper-wallet/paper-wallet.ts
=> Show wallet error in a new line

src/pages/backup/backup-game/backup-game.ts, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/integrations/glidera/sell-glidera/sell-glidera.ts, src/pages/settings/wallet-settings/wallet-settings-advanced/bitcoin-cash/bitcoin-cash.ts, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-export/wallet-export.ts, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-information/wallet-extended-private-key/wallet-extended-private-key.ts, src/providers/bwc-error/bwc-error.ts, src/providers/wallet/wallet.ts
- Keep selected wallet if the wrong encrypt password is entered
- Error handling refactored to encrypt password throughout the application
=> FIX: fixes for gift cards

src/app/app.component.ts, src/providers/app/app.spec.ts, src/providers/platform/platform.ts
(This information can be very useful for the support team)
=> FEAT: Device information added to logs

src/pages/settings/about/session-log/session-log.ts, src/providers/app/app.ts, src/providers/download/download.ts, src/providers/logger/logger.ts, src/providers/persistence/persistence.ts, src/providers/persistence/storage/file-storage.ts
- Call getLogs function once
- setLogs condition: all logs during 3 days
- Send logs as a .txt file on mobile
=> Ref: persistent logs

src/directives/copy-to-clipboard/copy-to-clipboard.ts, src/pages/send/confirm/confirm.html, src/theme/variables.scss
Also:  Unnecessary log deleted
=> Fix: small fixes for UI

src/pages/integrations/coinbase/buy-coinbase/buy-coinbase.ts, src/pages/integrations/coinbase/sell-coinbase/sell-coinbase.ts, src/providers/coinbase/coinbase.ts
* Also prepare (show error) if account doesn't have KYC
=> Fix(Coinbase-Integration): allow only USD and US bank accounts. Fix Sell

src/pages/scan/scan.ts, src/providers/persistence/persistence.ts, src/providers/profile/profile.ts, src/providers/scan/scan.ts
Removed unnecessary logs
Use a new thread to save logs
=> Fix: Persistent logs performance

src/pages/integrations/gift-cards/card-details/card-details.html, src/pages/integrations/gift-cards/purchased-cards/card-list-item/card-list-item.ts, src/providers/gift-card/gift-card.ts
Also, a correct handling of the different states that a gift card can have with their respective messages.
=> FIX: fixes for gift cards that failed for some reason

src/providers/tx-format/tx-format.ts
Allow copay to work with some missing fields in TX history.
=> small fixes to allow copay to run with Bitcore v8

CONTRIBUTING.md, src/pages/onboarding/backup-request/backup-request.ts, src/pages/settings/lock/lock.ts
Changing backup for back up when it refers to an action
=> fix: Fix misspelled word

src/app/app.component.ts, src/pages/integrations/shapeshift/shapeshift-confirm/shapeshift-confirm.ts, src/pages/integrations/shapeshift/shapeshift-settings/shapeshift-settings.html, src/pages/integrations/shapeshift/shapeshift-settings/shapeshift-settings.scss, src/pages/integrations/shapeshift/shapeshift-settings/shapeshift-settings.ts, src/pages/integrations/shapeshift/shapeshift.html, src/pages/integrations/shapeshift/shapeshift.scss, src/pages/integrations/shapeshift/shapeshift.ts, src/providers/home-integrations/home-integrations.ts, src/providers/incoming-data/incoming-data.ts, src/providers/persistence/persistence.ts, src/providers/shapeshift/shapeshift.ts
Authentication on ShapeShift will be a mandatory feature from November 1
Fixes for pop-up errors: [Object Object]
=> FEAT: shapeshift authentication

src/pages/send/send.spec.ts, src/pages/send/send.ts, src/providers/address/address.ts, src/providers/paypro/paypro.ts
Shows an error when scanning from a wallet if it does not match the network and/or currency
=> FEAT: show error when the wallet does not match the network and/or the coin

src/pages/integrations/shapeshift/shapeshift.html, src/pages/integrations/shapeshift/shapeshift.scss, src/pages/integrations/shapeshift/shapeshift.ts, src/providers/shapeshift/shapeshift.ts
- A link that explains the reason of authentication was added
- `let` changed for `const`
- Fix an error of getToken() function
=> FIX: Link that explains the reason of authentication and fixes

src/pages/send/send.ts
Avoid showing error message whenever something invalid is entered in Send Page input
=> Fix: control when showing error message in Send Page input

src/app/app.component.ts, src/pages/integrations/coinbase/buy-coinbase/buy-coinbase.ts, src/pages/integrations/coinbase/sell-coinbase/sell-coinbase.ts, src/pages/settings/about/session-log/session-log.ts, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-addresses/all-addresses/all-addresses.ts, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-export/wallet-export.ts, src/providers/app/app.ts, src/providers/logger/logger.ts, src/providers/persistence/persistence.spec.ts, src/providers/persistence/persistence.ts, src/providers/persistence/storage/file-storage.ts
=> Revert "Ref: persistent logs"

src/pages/send/confirm/confirm.spec.ts, src/pages/send/confirm/confirm.ts, src/pages/send/multi-send/multi-send.ts, src/pages/wallet-details/wallet-details.ts, src/providers/coinbase/coinbase.ts, src/providers/config/config.spec.ts, src/providers/config/config.ts
Correction of some errors and warnings that I could observe, by running the code under "strict mode".
=> Fix: errors/warnings related 'use strict' mode

src/pages/receive/receive.ts, src/pages/send/multi-send/multi-send.ts, src/pages/send/send.ts, src/pages/send/transfer-to/transfer-to.ts, src/providers/address/address.spec.ts, src/providers/address/address.ts
This PR Fixes: https://github.com/bitpay/copay/issues/9396
=> Ref: addressProvider to remove unnecessary validateAddress function

src/providers/gift-card/gift-card.ts
Cache cardConfig in memory for faster gift card page load times on iOS and android devices.
=> Improve load time of gift card views

src/pages/wallet-details/wallet-details.html, src/providers/wallet/wallet.ts
as per title.
also remove twoStep, since it is not longer used on BWC.
=> show available balance while refreshing

src/pages/wallet-details/wallet-details.html
* Also removes duplicated code
=> TX List: identify tx when sending to another wallet

src/providers/wallet/mocks/pending-txp.mock.ts, src/providers/wallet/mocks/wallet.mock.ts, src/providers/wallet/wallet.spec.ts, src/providers/wallet/wallet.ts
Unit tests coverage of wallet provider up to +80%
=> Unit tests for wallet provider

src/pages/add/copayers/copayers.ts, src/pages/add/import-wallet/import-wallet.ts, src/pages/add/join-wallet/join-wallet.ts, src/pages/home/proposals/proposals.ts, src/pages/integrations/gift-cards/card-details/card-details.ts, src/pages/integrations/shapeshift/shapeshift.ts, src/pages/receive/receive.ts, src/pages/scan/scan.ts, src/pages/send/amount/amount.ts, src/pages/send/multi-send/multi-send.ts, src/pages/send/send.spec.ts, src/pages/send/send.ts, src/pages/settings/addressbook/add/add.ts, src/pages/tx-details/tx-details.ts, src/pages/txp-details/txp-details.ts, src/pages/wallet-details/wallet-details.ts, src/pages/wallet-tabs/wallet-tabs.ts
The intention of this PR is to prevent a page from unsubscribing necessary events in other pages or providers of the app. In addition to avoid creating multiple unnecessary subscriptions to the same event
=> Ref: event handler functions

src/providers/tx-format/tx-format.ts
=> Fix(tx-format): display sat/bytes for unconfirmed tx

src/pages/txp-details/txp-details.ts, src/providers/bwc-error/bwc-error.ts, src/providers/paypro/paypro.ts
This is minor PR to handle better errors from Paypro. Tested with:
https://github.com/bitpay/bitcore/pull/2031
But it should not affect the current paypro error reporting.
=> better handling of paypro err messages

src/app/app.scss, src/pages/add/add.html, src/pages/add/add.scss, src/pages/add/add.ts, src/pages/add/create-wallet/create-wallet.html, src/pages/add/create-wallet/create-wallet.ts, src/pages/add/import-wallet/import-wallet.html, src/pages/add/import-wallet/import-wallet.ts, src/pages/add/join-wallet/join-wallet.html, src/pages/add/select-currency/select-currency.html, src/pages/add/select-currency/select-currency.scss, src/pages/add/select-currency/select-currency.ts, src/pages/includes/gravatar/gravatar.ts, src/pages/pages.ts, src/pages/templates/wide-header-page/wide-header-page.html
=> [REF] Improve wallet creation flow UI

package-lock.json, package.json
Before the fix:
```
found 19 vulnerabilities (3 low, 16 moderate)
``` 
After the fix:
```
found 4 vulnerabilities (3 low, 1 moderate)
```
=> Fix(npm): fix npm vulnerabilities

src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/providers/gift-card/gift-card.ts
Also ensures gift cards are properly displayed in offline mode.
=> Use case-insensitive sort for gift cards

src/pages/onboarding/disclaimer/disclaimer.html, src/pages/onboarding/disclaimer/disclaimer.scss
=> [REF] disclaimer Page

src/app/app.scss, src/pages/includes/multiple-outputs/multiple-outputs.html, src/pages/includes/multiple-outputs/multiple-outputs.scss, src/pages/send/confirm/confirm.html, src/pages/send/confirm/confirm.scss, src/pages/tx-details/tx-details.html, src/pages/tx-details/tx-details.scss, src/pages/tx-details/tx-details.ts, src/pages/txp-details/txp-details.html, src/pages/txp-details/txp-details.scss, src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.scss
article: https://support.bitpay.com/hc/en-us/articles/360025484512-Missing-transactions-Why-is-my-transaction-unconfirmed-
=> [FEAT] show info about unconfirmed transactions

src/pages/fingerprint/fingerprint.ts, src/pages/pin/pin-modal/pin-modal.ts
Fixes -> open the app from a push notification ( having any lock method set ) do not open the corresponding wallet
=> [FIX] close lock-modals correctly

package-lock.json, package.json, src/pages/add/create-wallet/create-wallet.spec.ts, src/pages/add/create-wallet/create-wallet.ts, src/pages/add/import-wallet/import-wallet.spec.ts, src/pages/add/import-wallet/import-wallet.ts, src/pages/add/join-wallet/join-wallet.ts, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/integrations/shapeshift/shapeshift-confirm/shapeshift-confirm.ts, src/pages/receive/custom-amount/custom-amount.ts, src/pages/send/confirm/confirm.ts, src/pages/settings/advanced/advanced.html, src/pages/settings/advanced/advanced.ts, src/pages/tx-details/tx-details.ts, src/pages/txp-details/txp-details.ts, src/providers/config/config.ts, src/providers/derivation-path-helper/derivation-path-helper.spec.ts, src/providers/derivation-path-helper/derivation-path-helper.ts, src/providers/profile/profile.ts, src/providers/tx-format/tx-format.spec.ts, src/providers/tx-format/tx-format.ts, src/providers/wallet/mocks/wallet.mock.ts, src/providers/wallet/wallet.spec.ts, src/providers/wallet/wallet.ts
Needs `npm i`
- Update to BWC v3.8.0
- Unnecessary translations for BCH addresses removed
- Unit tests fixed
- Refactor for some functions
=> Ref: update to BWC v3.8.0

src/components/amount-picker/amount-picker.html, src/pages/integrations/gift-cards/buy-card/buy-card.ts, src/pages/integrations/gift-cards/card-catalog/card-catalog.html, src/pages/integrations/gift-cards/card-catalog/card-catalog.ts, src/pages/integrations/gift-cards/card-details/printable-card/printable-card.ts, src/pages/integrations/gift-cards/home-gift-cards/home-gift-cards.html, src/providers/gift-card/gift-card.ts
1. Display featured gift cards at the top of the catalog
2. Fix non-deterministic behavior of fixed amount selector
3. Fix 404 in print preview component for gift cards without barcode images
4. Ensure brand names that start with a number appear at the bottom of the gift card catalog
=> Featured Gift Cards

src/components/amount-picker/amount-picker.html, src/pages/integrations/gift-cards/buy-card/buy-card.ts, src/pages/integrations/gift-cards/card-catalog/card-catalog.html, src/pages/integrations/gift-cards/card-catalog/card-catalog.ts, src/pages/integrations/gift-cards/card-details/printable-card/printable-card.ts, src/pages/integrations/gift-cards/home-gift-cards/home-gift-cards.html, src/providers/gift-card/gift-card.ts
=> Revert "Featured Gift Cards"

src/components/amount-picker/amount-picker.html, src/pages/integrations/gift-cards/buy-card/buy-card.ts, src/pages/integrations/gift-cards/card-catalog/card-catalog.html, src/pages/integrations/gift-cards/card-catalog/card-catalog.ts, src/pages/integrations/gift-cards/card-details/printable-card/printable-card.ts, src/pages/integrations/gift-cards/home-gift-cards/home-gift-cards.html, src/providers/gift-card/gift-card.ts
1. Display featured gift cards at the top of the catalog
2. Fix non-deterministic behavior of fixed amount selector
3. Fix 404 in print preview component for gift cards without barcode images
4. Ensure brand names that start with a number appear at the bottom of the gift card catalog
=> Gift card improvements and fixes

src/pages/send/multi-send/multi-send.html
=> Revert "Ref: multiple recipients in descending order"

src/pages/add/import-wallet/import-wallet.spec.ts, src/pages/add/import-wallet/import-wallet.ts
This PR fixes a bug in which the coin and certain parameters are not recognized when trying to import from the general scan
=> Fix: Import from scan

src/pages/receive/custom-amount/custom-amount.scss
=> Fix: qr-code card for payment request

src/pages/send/amount/amount.html, src/pages/send/amount/amount.ts, src/pages/send/multi-send/multi-send.html, src/pages/send/multi-send/multi-send.ts, src/pages/send/transfer-to-modal/transfer-to-modal.html, src/pages/send/transfer-to/transfer-to.ts
- Changes in the workflow to add recipients
- UI fixes
=> Ref: UI multi recipients

src/providers/profile/profile.spec.ts, src/providers/profile/profile.ts
Coverage current progress: 85%
=> Feat: unit tests for profile provider

src/pages/add/copayers/copayers.html, src/pages/add/copayers/copayers.scss
=> ref(join):little refactor for copayers-view

src/app/app.component.ts, src/providers/key/key.spec.ts, src/providers/key/key.ts
Also 'remove key' method implemented
=> Ref: key provider 

src/pages/home/home.html, src/pages/home/home.scss, src/pages/home/home.ts
* Also speedup startup. Additional checks loads after 2 secs.
=> fix(home): server message flash the card when opening

src/pages/home/home.html
=> UI fix for title of the cards at home

src/pages/integrations/coinbase/coinbase-settings/coinbase-settings.html, src/pages/integrations/coinbase/coinbase-settings/coinbase-settings.scss, src/pages/integrations/coinbase/coinbase-settings/coinbase-settings.ts, src/pages/integrations/shapeshift/shapeshift-settings/shapeshift-settings.html, src/pages/integrations/shapeshift/shapeshift-settings/shapeshift-settings.scss, src/pages/integrations/shapeshift/shapeshift-settings/shapeshift-settings.ts, src/providers/coinbase/coinbase.ts, src/providers/shapeshift/shapeshift.ts
* also ref some UI elements
* And show "linked" tag for Shapeshift in Settings screen
=> ref(external-services): fix show in home for coinbase/shapeshift

src/pages/integrations/gift-cards/buy-card/buy-card.scss, src/pages/integrations/gift-cards/home-gift-cards/home-gift-cards.html, src/providers/gift-card/gift-card.ts
Fix a few discount related styling issues:
1. Lighter card box shadow on buy card page
2. Remove small gap between gift card item and "buy gift card" button when there is no active discount
Also hides discounts for non iOS/Android builds
=> Discount fixes

src/components/components.ts, src/pages/send/transfer-to/transfer-to.html, src/pages/send/transfer-to/transfer-to.ts, src/pages/settings/addressbook/add/add.ts, src/pages/settings/addressbook/address-item-content.component.html, src/pages/settings/addressbook/address-item-content.component.scss, src/pages/settings/addressbook/address-item-content.component.ts, src/pages/settings/addressbook/addressbook.html, src/pages/settings/addressbook/addressbook.scss, src/pages/settings/addressbook/addressbook.ts, src/pages/settings/addressbook/view/view.ts, src/providers/address-book/address-book.ts, src/providers/persistence/persistence.ts
=> reorder address book contacts

src/pages/wallet-group-selector/wallet-group-selector.scss
=> Fix: App img in wallet group selector

src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.scss
=> [REF] wallet details warning msg

src/pages/add/copayers/copayers.html, src/pages/add/copayers/copayers.scss, src/pages/add/copayers/copayers.ts
=> Ref: Copayers view - new design

src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/integrations/invoice/confirm-invoice/confirm-invoice.ts, src/pages/integrations/shapeshift/shapeshift.ts, src/pages/send/amount/amount.ts, src/pages/send/confirm/confirm.ts, src/pages/settings/wallet-settings/wallet-settings.ts
* Also reuse variables for `isCordova` and `platformProvider`
=> fix(status-bar): set color on wallet-settings

src/pages/add/add.html, src/pages/add/add.ts, src/pages/add/import-wallet/import-wallet.html, src/pages/add/import-wallet/import-wallet.ts, src/pages/home/home.html, src/pages/home/home.scss, src/pages/settings/addressbook/addressbook.scss
Info message in profile view:
Dropdown at wallets level, move scanner to the top right, settings to top left. Replace order icon with edit button:
show add Wallet and reorder wallets when edit icon is clicked:
=> [REF] Home view

src/pages/home/home.html, src/pages/home/home.ts
=> Ref: Separate read only wallets in home page

src/pages/settings/wallet-group-settings/wallet-group-settings.html
Also fixes condition to show "Security" title
=> Fix: "Read only" warning message in wallet settings

src/pages/pages.ts, src/pages/settings/advanced/advanced.html, src/pages/settings/advanced/advanced.ts, src/pages/settings/advanced/wallet-recover-page/wallet-mnemonic-recover-page/wallet-mnemonic-recover-page.html, src/pages/settings/advanced/wallet-recover-page/wallet-mnemonic-recover-page/wallet-mnemonic-recover-page.ts, src/pages/settings/advanced/wallet-recover-page/wallet-mnemonic-recover-page/wallet-mnemonic-recover.scss, src/pages/settings/advanced/wallet-recover-page/wallet-recover-page.html, src/pages/settings/advanced/wallet-recover-page/wallet-recover-page.scss, src/pages/settings/advanced/wallet-recover-page/wallet-recover-page.ts, src/pages/settings/wallet-group-settings/wallet-group-delete/wallet-group-delete.ts, src/pages/settings/wallet-group-settings/wallet-group-settings.ts, src/providers/persistence/persistence.ts, src/providers/profile/profile.ts
PR allows users to recover old wallet mnemonic phrases after migration to single seed.
=> Mnemonic recover tool

src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.html, src/pages/integrations/gift-cards/gift-card-settings/gift-card-settings.html, src/pages/integrations/gift-cards/gift-cards-settings/gift-cards-settings.html, src/providers/gift-card/gift-card.ts
Also ensure active gift card data fetched from storage matches expected schema.
=> Fix gift card settings styles

src/pages/add/import-wallet/import-wallet.ts, src/pages/settings/wallet-group-settings/wallet-group-settings.ts, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-export/wallet-export.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-export/wallet-export.ts, src/pages/settings/wallet-settings/wallet-settings.html, src/pages/settings/wallet-settings/wallet-settings.ts, src/providers/backup/backup.ts, src/providers/profile/profile.ts
(except for read only wallets)
=> Fix: show advanced opts in wallet export for all wallets

src/pages/add/create-wallet/create-wallet.ts, src/pages/add/import-wallet/import-wallet.html, src/pages/add/import-wallet/import-wallet.ts, src/pages/add/join-wallet/join-wallet.ts, src/pages/backup/backup-key/backup-key.ts, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-duplicate/wallet-duplicate.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-duplicate/wallet-duplicate.ts, src/pages/settings/wallet-settings/wallet-settings.html, src/pages/settings/wallet-settings/wallet-settings.ts, src/providers/profile/profile.ts, src/providers/wallet/wallet.ts
Also:
- Fixes for Join, Create and Import Legacy wallets
- Enabled duplicate option for Legacy wallets
=> [REF] refactor of duplicate feature

package-lock.json, package.json, src/pages/includes/multiple-outputs/multiple-outputs.ts, src/providers/address/address.spec.ts, src/providers/wallet/wallet.ts
New BWC (v8.6.x) required.
TODO
* Test send to bech32 addr livenet: OK
* Test multisig same BWC version: OK
* Test multisig diff BWC version: Error: Non-base58 character
=> feat(bech32): add tests and show unparsed address if bc1

src/pages/add-wallet/add-wallet.html, src/pages/add-wallet/add-wallet.scss
=> REF: add wallet UI updated for joining wallet from scanner

i18n/template.pot, src/assets/i18n/de.po, src/assets/i18n/en.po, src/assets/i18n/es.po, src/assets/i18n/fr.po, src/assets/i18n/it.po, src/assets/i18n/ja.po, src/assets/i18n/ko.po, src/assets/i18n/nl.po, src/assets/i18n/pl.po, src/assets/i18n/pt.po, src/assets/i18n/ru.po, src/assets/i18n/zh.po, src/components/incoming-data-menu/incoming-data-menu.html, src/components/incoming-data-menu/incoming-data-menu.ts, src/pages/add/import-wallet/import-wallet.ts, src/pages/send/choose-fee-level/choose-fee-level.html, src/pages/send/choose-fee-level/choose-fee-level.ts, src/pages/send/confirm/confirm.ts, src/providers/incoming-data/incoming-data.ts
- added support for EIP 831 ethereum:address
- fix sendMax totalAmount being negative
- Added translations for `{coinName} Address` and `Enter custom fee in {feeUnit}`
- Added feeUnit to choose-fee-level.ts - dynamic sat/byte or Gwei based on coin.
Specification details can be found here:
https://eips.ethereum.org/EIPS/eip-831
=> Feature(EIP 831) - ethereum:address

app-template/config-template.xml, package.json
Compatible with the New Build System (XCode)
=> chore(cordova): upgrade cordova-ios 5.0.1

src/pages/send/choose-fee-level/choose-fee-level.ts
- Fix fee unit conversion and dynamically set fee unit based on Coin
Also depends on:
https://github.com/bitpay/bitcore/pull/2419
=> Fix custom fee bug ETH

src/pages/integrations/gift-cards/card-catalog/card-catalog.ts, src/pages/integrations/gift-cards/card-details/card-details.scss, src/pipes/format-currency.ts
Minor tweaks for a better gift card experience.
=> Gift card improvements

src/pages/send/confirm/confirm.ts, src/providers/wallet/wallet.ts
depends on https://github.com/bitpay/bitcore/pull/2424
=> changes for pushing ETH signatures

src/components/clipboard-card/clipboard-card.html, src/pages/home/home.ts, src/pages/receive/custom-amount/custom-amount.ts, src/pages/send/confirm/confirm.ts, src/pages/send/send.ts, src/providers/address/address.ts, src/providers/incoming-data/incoming-data.ts
```
request                 = erc831_part target_address [ "@" chain_id ] [ "/" function_name ] [ "?" parameters ]
erc831_part             = schema and optional prefix as defined in #831 - typically "ethereum" ":" [ "pay-" ] in this case
target_address          = ethereum_address
chain_id                = 1*DIGIT
function_name           = STRING
ethereum_address        = ( "0x" 40*40HEXDIG ) / ENS_NAME
parameters              = parameter *( "&" parameter )
parameter               = key "=" value
key                     = "value" / "gas" / "gasLimit" / "gasPrice" / TYPE
value                   = number / ethereum_address / STRING
number                  = [ "-" / "+" ] *DIGIT [ "." 1*DIGIT ] [ ( "e" / "E" ) [ 1*DIGIT ] [ "+" UNIT ]
```
- `value` = amount in wei
- `gasPrice` = gas price in …
=> Feature EIP-681: Payment request URL specification

src/pages/home/home.ts, src/pages/includes/multiple-outputs/multiple-outputs.html, src/pages/includes/multiple-outputs/multiple-outputs.scss, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.scss, src/pages/send/confirm/confirm.html, src/pages/send/confirm/confirm.scss, src/pages/send/multi-send/multi-send.html, src/pages/send/multi-send/multi-send.scss, src/pages/txp-details/txp-details.scss
Also removes unnecessary scss code
=> Fix: UI issues in address field "to"

src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts, src/providers/tx-format/tx-format.ts
- fix sendMax for `bitpay-card-topup.ts` `maxAmount` conversion.
- set `coin = 'eth'` if `currency = 'ETH'`
=> set coin if currency is ETH

src/pages/add/add.ts
* when multiple seed is activated
=> Fix: shared wallet from home page

src/pages/send/amount/amount.ts
Related: https://github.com/bitpay/copay/pull/10190
=> fix(send-max): for top-up bp cards

src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/integrations/invoice/confirm-invoice/confirm-invoice.ts, src/pages/send/amount/amount.ts, src/pages/send/confirm/confirm.ts
- Use getCoinAndNetwork to determine network
- Pass navParams.network from amount.ts
=> Fix(ETH:Testnet) Send Confirm Page network

src/providers/incoming-data/incoming-data.spec.ts, src/providers/incoming-data/incoming-data.ts
Also:
- Fix `handleEthereumAddress` call with redirParams
- Missing tests added to incomingDataProvider
=> Feat: unit tests for eth in incomingDataProvider

src/providers/profile/profile.spec.ts, src/providers/profile/profile.ts
Also fixes WalletGroups interface
=> Fix: Profile provider unit tests

src/components/info-sheet/info-sheet.html, src/pages/add/select-currency/select-currency.ts
=> Fix: Remove create both ETH and token wallets

package-lock.json, package.json, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-information/wallet-information.html, src/pages/settings/wallet-settings/wallet-settings-advanced/wallet-information/wallet-information.ts, src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.ts, src/providers/currency/currency.ts, src/providers/profile/profile.ts
=> add linked wallet name to wallet details and wallet info

src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.scss
=> Styles for eth wallet name in token details

src/pages/settings/share/share.ts
Add wallet firebase analytic firebase Share Events
=> Add share events

src/pages/settings/settings.ts
=> Help Analytics event /Firebase

src/pages/integrations/gift-cards/card-catalog/card-catalog.ts, src/pages/integrations/gift-cards/card-details/card-details.ts, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/providers/gift-card/gift-card.ts
Add Gift Card analytic firebase events
=> Gift Card analytics/ Firebase

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, package.json
=> Bump v8.0.2-beta

src/providers/profile/profile.ts
=> Fix profile walletName is undefined error on app load

src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.html, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.scss, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pipes/format-currency.ts
And improve Confirm Card Purchase page.
=> Support PHP and INR currency symbols

src/app/app.component.html, src/app/app.component.ts, src/app/services/data-services.service.ts
needs https://github.com/bitpay/bitcore/pull/2531 to work
=> FEAT: chart to show amount in USD

src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts
=> Fix(card) - ERC20 miner fee precision and totalAmountStr for card

src/pages/send/send.html
=> fix(send-view): fix icon size for small screen phones (iOS 10.3.1)

src/providers/incoming-data/incoming-data.ts
relies on:
https://github.com/bitpay/bitcore/pull/2625
=> Feature - Add staging.bitpay.com to valid bitpay invoice url intent

src/providers/bwc-error/bwc-error.spec.ts, src/providers/incoming-data/incoming-data.spec.ts
Fixes:
address.spec.ts
incoming-data.spec.ts
relies on:
https://github.com/bitpay/bitcore/pull/2627
=> Fix Copay tests

src/providers/profile/profile.ts
- Get correct token Wallet using token walletId to update walletName
=> Fix token walletName automatically updates

src/components/info-sheet/info-sheet.html
Remove single ETH wallet case in addTokenWallet sheet
=> Remove single ETH wallet condition in addTokenWallet

src/pages/home/proposals/proposals.html, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.html, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts, src/pages/integrations/coinbase/buy-coinbase/buy-coinbase.html, src/pages/integrations/coinbase/buy-coinbase/buy-coinbase.ts, src/pages/integrations/coinbase/sell-coinbase/sell-coinbase.html, src/pages/integrations/coinbase/sell-coinbase/sell-coinbase.ts, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.html, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/integrations/shapeshift/shapeshift-confirm/shapeshift-confirm.html, src/pages/integrations/shapeshift/shapeshift-confirm/shapeshift-confirm.ts, src/pages/receive/custom-amount/custom-amount.ts, src/pages/send/confirm/confirm.ts, src/pages/slide-to-accept/slide-to-accept.html, src/pages/slide-to-accept/slide-to-accept.scss, src/pages/slide-to-accept/slide-to-accept.ts, src/pages/txp-details/txp-details.html, src/pages/txp-details/txp-details.ts
* Adds animation when slider show
* Removes `hideSlideButton` for unnecessary views. It's only needed when mobile keyboard appears
=> ref(slide-button): adds animation. removes unused hideSlider

src/pages/home/home.html, src/pages/home/home.ts, src/pages/integrations/simplex/simplex-buy/simplex-buy.html, src/pages/integrations/simplex/simplex-settings/simplex-settings.html, src/pages/integrations/simplex/simplex-settings/simplex-settings.scss, src/pages/integrations/simplex/simplex-settings/simplex-settings.ts, src/pages/integrations/simplex/simplex.html, src/pages/integrations/simplex/simplex.scss, src/pages/integrations/simplex/simplex.ts, src/providers/simplex/simplex.ts
Changes the home button to 'Buy Crypto "
Removes the Simplex landing -> Go directly to Buy page
Resizes images
=> Ref: Simplex flow, images and home button

src/pages/settings/alt-currency/alt-currency.ts, src/providers/wallet/wallet.spec.ts, src/providers/wallet/wallet.ts
* Save current preferences into BWS: language and email for notifications
* Reload page after update fiat currency
* Do not save remote (BWS) alt-currency
* Filter crypto-currencies on list of alternative currency view.
=> fix(remote-prefs): save prefs into BWS and small UI issues

src/pages/home/home.ts
fixes - new design home page -> advertisement cards -> bitpay card and amazon card -> call to action does not work.
=> Fix(bug) - goTo in home.ts

src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/providers/rate/rate.ts, src/providers/tx-format/tx-format.spec.ts, src/providers/tx-format/tx-format.ts
=> Fix gift card purchases with erc20 (v8.2)

src/pages/includes/multiple-outputs/multiple-outputs.scss, src/pages/send/confirm/confirm.scss
=> [FIX] "sending to" label for bp topups

src/providers/clipboard/clipboard.ts
Just to make it easier to test the clipboard card feature
=> [REF] get clipboard data on browser

package.json, src/app/app.module.ts, src/assets/img/plus-gray.svg, src/components/action-card-v4/action-card-v4.scss, src/components/add-button/add-button.html, src/components/add-button/add-button.scss, src/components/add-button/add-button.ts, src/components/components.ts, src/components/email-component/email-component.html, src/pages/cards/cards.scss, src/pages/integrations/bitpay-card/bitpay-card-home/bitpay-card-home.html, src/pages/integrations/bitpay-card/bitpay-card-home/bitpay-card-home.scss, src/pages/integrations/gift-cards/card-catalog/card-catalog.scss, src/pages/integrations/gift-cards/card-details/card-details.html, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.html, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/integrations/gift-cards/home-gift-cards/gift-card-item/gift-card-item.html, src/pages/integrations/gift-cards/home-gift-cards/gift-card-item/gift-card-item.ts, src/pages/integrations/gift-cards/home-gift-cards/home-gift-cards.html
Updates the Cards tab to the new design.
=> Improved gift card management UI

src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.scss
=> Ref: Send and Receive buttons moved to the bottom

src/components/options-sheet/options-sheet.html, src/pages/send/amount/amount.html, src/pages/send/amount/amount.scss, src/pages/send/multi-send/multi-send.html, src/pages/send/multi-send/multi-send.scss, src/pages/send/send.html, src/pages/send/send.scss, src/pages/send/send.ts, src/pages/send/transfer-to-modal/transfer-to-modal.html, src/pages/send/transfer-to-modal/transfer-to-modal.scss, src/pages/send/transfer-to/transfer-to.html, src/providers/action-sheet/action-sheet.ts
Tap on "..."  to open the option-sheet
=> ref(multi-send): fix search box and improves flow to send to multi-recipients

package.json, src/providers/push-notifications/push-notifications.ts
need https://github.com/bitpay/bitcore/pull/2693
=> [FEAT] handle erc20 push notifications

package.json, src/providers/push-notifications/push-notifications.ts
=> Revert "[FEAT] handle erc20 push notifications"

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, package-lock.json, package.json
=> Revert "Bump v9.0.2 BETA"

src/pages/send/amount/amount.html, src/pages/send/amount/amount.scss
I removed the wide header on this page. It was unnecessary since it doesn't even have a title
=> Fix: amount view

src/pages/wallet-details/wallet-details.ts
=> Fix: error when redirectionParam is undef

src/app/app.scss, src/assets/img/icon-bpcard.svg, src/assets/img/icon-merch-dir.svg, src/assets/img/merch-dir.svg, src/pages/cards/cards.html, src/pages/home/home.html, src/pages/home/home.scss, src/pages/home/home.ts, src/pages/integrations/bitpay-card/bitpay-card-home/bitpay-card-home.html, src/pages/integrations/gift-cards/home-gift-cards/home-gift-cards.html, src/pages/settings/settings.html, src/pages/wallet-details/wallet-details.scss, src/pages/wallets/wallets.html, src/theme/variables.scss
=> Feat: Design updates

src/pages/cards/cards.scss, src/pages/wallet-details/wallet-details.ts
- updated card scss 
- fixed redirection param
=> Card Beta 

src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.html
=> Fix css for gift card total

src/components/exchange-rates/exchange-rates.html, src/components/exchange-rates/exchange-rates.ts
depends on 
https://github.com/bitpay/bitcore/pull/2732
=> XRP uses 1.4-4 digits exchange rate

package-lock.json, package.json
codecov: https://github.com/bitpay/copay/network/alert/package-lock.json/codecov/open
=> Updated: codecov and package-lock

src/app/app.scss, src/components/search-bar/search-bar.scss, src/pages/send/multi-send/multi-send.scss, src/pages/send/send.scss, src/pages/settings/alt-currency/alt-currency.html, src/pages/settings/alt-currency/alt-currency.scss
- Removes border from all searchbar inputs
- Changes border-radius from ~~6px~~ to 8px
=> Update alt-currency UI

src/pages/home/home.html, src/pages/home/home.scss
=> Change CSS for date label 1D

src/components/email-component/email-component.html, src/components/email-component/email-component.scss, src/components/email-component/email-component.ts
=> Fix UI for email-component

src/components/wallet-receive/wallet-receive.scss
=> Fix margin on wallet-receive component

src/pages/integrations/shapeshift/shapeshift-confirm/shapeshift-confirm.ts, src/pages/integrations/shapeshift/shapeshift-details/shapeshift-details.html, src/pages/integrations/shapeshift/shapeshift-details/shapeshift-details.ts, src/pages/integrations/shapeshift/shapeshift-shift/shapeshift-shift.html, src/pages/integrations/shapeshift/shapeshift-shift/shapeshift-shift.ts, src/pages/integrations/shapeshift/shapeshift.html, src/pages/integrations/shapeshift/shapeshift.scss, src/pages/integrations/shapeshift/shapeshift.ts, src/pages/send/amount/amount.ts, src/providers/shapeshift/shapeshift.ts
* Almost all cases covered. Also if error occurs.
* Use priority fee.
* Get info from orderId
=> ref(shapeshift): add all supported coins

src/components/wallet-receive/wallet-receive.html, src/components/wallet-receive/wallet-receive.ts, src/pages/add/copayers/copayers.html, src/pages/add/copayers/copayers.ts, src/pages/receive/custom-amount/custom-amount.html, src/pages/receive/custom-amount/custom-amount.ts, src/pages/settings/settings.html, src/pages/settings/settings.ts, src/providers/config/config.ts, src/providers/currency/coin.ts, src/providers/currency/currency.ts
=> [FIX] remove legacy qr-code option - use default black for qr-codes

src/app/app.scss, src/pages/add/copayers/copayers.ts, src/pages/home/home.html, src/pages/home/home.ts, src/pages/settings/settings.html, src/pages/settings/settings.ts, src/pages/tabs/tabs.html, src/pages/tabs/tabs.ts, src/pages/wallets/wallets.ts, src/providers/config/config.ts, src/providers/persistence/persistence.ts, src/providers/profile/profile.ts, src/theme/variables.scss
* Adds tab badge (number of pending proposals)
* Fix tab bar (normalize css)
* Fix last day rate
* Fix BitPay Card slider (add it if there are linked cards)
* Moves fetchWallet to tabs controller and includes tab provider
* Removes tab provider from home
* Set events to update total balance and badge
=> ref(home): pre-load wallets, balance and proposals from tabs

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, package-lock.json, package.json
* [FEAT] new release msg (#10713) 
* [FEAT] reorder keys (#10714)
* refactored to allow for implicit pairings (#10728)
* ref(home): pre-load wallets, balance and proposals from tabs (#10721)
=> Bump v9.1.2-beta

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, package-lock.json, package.json
* fix(wallet): stop loading spinner if wallets is empty. Hide wallet instead remove if incomplete (#10731)
* fix(config): saved values were overwritten by default values if it wa…  (#10732)
* making card use a dynamic network (#10736)
* add AU (#10735)
* Feat/update waiting list (#10734)
* Clear encrypt password option (#10696)
=> Bump v9.2.0

src/app/app.scss, src/components/balance-to-show/balance-to-show.html, src/components/balance-to-show/balance-to-show.scss, src/components/balance-to-show/balance-to-show.ts, src/components/components.ts, src/pages/includes/multiple-outputs/multiple-outputs.html, src/pages/send/confirm/confirm.html, src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.scss, src/pipes/shortened-address.ts
- Fix pipe typo (shortenedAddress)
- Fix design and balance overlapping in wallet details (If the amount is very large, resize the font)
- Fix tab badge font family
Bug fixed
:
=> Fix: balance overlapping in wallet details

src/pages/home/home.ts, src/pages/integrations/coinbase/coinbase-account/coinbase-account.html, src/pages/integrations/coinbase/coinbase-account/coinbase-account.scss, src/pages/integrations/coinbase/coinbase-account/coinbase-account.ts, src/pages/integrations/coinbase/coinbase-settings/coinbase-settings.html, src/pages/integrations/coinbase/coinbase-settings/coinbase-settings.ts, src/pages/settings/settings.html, src/pages/wallets/wallets.html, src/pages/wallets/wallets.ts, src/providers/coinbase/coinbase.ts, src/providers/home-integrations/home-integrations.ts
* fix(coinbase): fixed deposit xrp and bch. Adds destinationTag
* Shows email in main settings (from linked account)
* Fix UI Account-balance: alignment of the header
* Add native-currency rates for all supported crypto currencies
* Adds more information into settings
* Banner shorten to keep 2 lines
=> feat(coinbase): show email in main settings, add native-currency rates for all supported crypto

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, package-lock.json, package.json
=> Bump v9.3.2-beta

src/components/balance-to-show/balance-to-show.html, src/components/balance-to-show/balance-to-show.scss, src/pages/wallet-details/wallet-details.scss
=> Fix: balance coin for desktop

src/pages/cards/cards.html, src/pages/cards/cards.scss, src/pages/cards/cards.ts, src/pages/home/home.ts, src/pages/integrations/bitpay-card/bitpay-card-home/bitpay-card-home.html, src/pages/integrations/bitpay-card/bitpay-card-home/bitpay-card-home.ts, src/pages/integrations/bitpay-card/bitpay-card-intro/bitpay-card-intro.html, src/pages/integrations/bitpay-card/bitpay-card-intro/bitpay-card-intro.scss, src/pages/integrations/bitpay-card/bitpay-card-phases/phase-one/phase-one-intro-page/phase-one-intro-page.html, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.html, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts, src/pages/integrations/bitpay-card/bitpay-settings/bitpay-settings.html, src/pages/integrations/bitpay-card/bitpay-settings/bitpay-settings.scss, src/pages/integrations/bitpay-card/bitpay-settings/bitpay-settings.ts
- moves fv card pairing to settings
- copy changes
- fixes render timing of add card button
- adds walletId to invoice creation
=> Copy changes

src/pages/onboarding/disclaimer/disclaimer.html, src/pages/onboarding/disclaimer/disclaimer.scss
=> Revert "[FIX] Onboarding UI fixed for small screens"

src/app/app.scss, src/pages/integrations/bitpay-card/bitpay-card-intro/bitpay-card-intro.scss, src/pages/integrations/bitpay-card/bitpay-card.html, src/pages/integrations/bitpay-card/bitpay-card.ts, src/pages/settings/about/session-log/session-log.scss, src/theme/dark.scss
- session log
- alerts
- BitPay card refresher background
- BitPay card intro
- gift cards discounts
=> [FIX]: Dark mode fixes

src/components/info-sheet/info-sheet.html, src/pages/txp-details/txp-details.html, src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.scss, src/pages/wallet-details/wallet-details.ts, src/providers/action-sheet/action-sheet.ts, src/providers/wallet/wallet.ts, src/theme/dark.scss
=> [FEAT] check for unconfirm inputs and rbf

src/app/app.component.ts, src/pages/cards/cards.html, src/pages/cards/cards.ts, src/pages/integrations/bitpay-card/bitpay-card-home/bitpay-card-home.ts, src/pages/integrations/bitpay-card/bitpay-card-intro/bitpay-card-intro.ts, src/pages/settings/settings.ts, src/providers/in-app-browser/card.ts, src/providers/incoming-data/incoming-data.ts
- adds handler for showing and hiding cards from the IAB settings
- adds balance update from the IAB to better keep things in sync
- fixes race condition issues
- refactor of card.ts
=> [FEAT] settings hide and show cards

package.json
fixes payments with segwit TX's by setting the appropiate weightedSize
=> updates BWC

package-lock.json, package.json
https://github.com/electron/electron/pull/22299
=> chore(electron-app): upgrade to 7.1.14. Fix app store rejected

src/pages/integrations/coinbase/coinbase-settings/coinbase-settings.html
Also if the account is linked.
=> fix(coinbase): show switch to show in wallets tab

src/providers/incoming-data/incoming-data.ts
=> Revert "fix(bitpay-card): url link card"

src/pages/fingerprint/fingerprint.scss
=> [FIX]: Scan again button

src/pages/settings/about/about.html, src/pages/settings/about/about.spec.ts, src/pages/settings/about/about.ts, src/pages/settings/settings.html, src/pages/settings/settings.scss, src/pages/settings/settings.ts, src/theme/dark.scss
- ionic icons size and color fixed
- Privacy Policy & Terms of use moved from about to settings
=> [FIX]: Settings page fixes

src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/providers/merchant/merchant.ts
Update recently purchased gift cards list immediately after each new gift card purchase.
=> Fix recently purchased gift card updates

src/pages/home/home.html, src/pages/home/home.scss, src/pages/home/home.ts
=> Add scan button to home page

app-template/config-template.xml, package.json
* Adds support to receiving push notifications from Firebase Console (without click_action "FCM_PLUGIN_ACTIVITY").
=> chore(fcm): updates plugin for push notifications

src/pages/home/home.html, src/pages/home/home.scss, src/pages/home/home.ts
=> Revert "Add scan button to home page"

src/pages/integrations/bitpay-card/bitpay-card-phases/phase-one/phase-one-intro-page/phase-one-into-page.scss, src/pages/integrations/bitpay-card/bitpay-card-phases/phase-one/phase-one-intro-page/phase-one-intro-page.html, src/providers/card-phases/card-phases.ts
- updates the waiting list gdpr copy
- posting 'OtherCard' cardType to marketo if country Australia, Mexico or Canada
=> [FEAT] update gdpr copy

src/components/info-sheet/info-sheet.html
=> [REF] improve encrypt info

src/components/info-sheet/info-sheet.html, src/pages/add/import-wallet/import-wallet.html, src/pages/add/import-wallet/import-wallet.spec.ts, src/pages/add/import-wallet/import-wallet.ts, src/providers/action-sheet/action-sheet.ts
=> [REF] improve import info

src/pages/settings/about/about.html, src/pages/settings/about/about.ts, src/providers/config/config.ts
=> fix(config): set default config if error occurs 

src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/send/confirm/confirm.ts, src/providers/profile/profile.ts
=> Add minPendingAmount check and error messaging

src/theme/dark.scss, src/theme/light.scss, src/theme/lists.scss
Also fixes styles for list labels
=> Fix: theme transitions

src/pages/send/confirm/confirm.ts
needs https://github.com/bitpay/bitcore/pull/2934
=> [FIX] eth multisig instantiation request

src/assets/img/tab-icons/tab-scan-dm.svg, src/assets/img/tab-icons/tab-scan.svg
- Scan icon should appear more clear with better colors
=> Update scan icons

src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/send/confirm/confirm.ts, src/pages/txp-details/txp-details.ts, src/providers/incoming-data/incoming-data.spec.ts, src/providers/incoming-data/incoming-data.ts, src/providers/paypro/paypro.spec.ts, src/providers/paypro/paypro.ts
=> Revert "Feat(PayPro) - Add address param to getPaymentDetails"

src/app/app.component.ts, src/pages/home/home.html, src/pages/home/home.ts, src/pages/tabs/tabs.ts, src/providers/app/app.ts, src/providers/wallet/wallet.ts
* Pre-load total balance from localStorage (Home)
* Display "Network error" in Home
* Show cached balance for all wallets
=> fix(connection): smooth app loading if server is down

src/pages/buy-crypto/crypto-offers/crypto-offers.html, src/pages/buy-crypto/crypto-offers/crypto-offers.ts, src/providers/wyre/wyre.ts
(Limits and fees were updated in Wyre's docs.)
Also prevents cards from expanding if there is no price loaded
=> Fix: Wyre limits and fees

src/pages/send/confirm/confirm.html, src/pages/send/confirm/confirm.scss, src/pages/send/multi-send/multi-send.html, src/pages/send/select-inputs/select-inputs.html
- Redesign of buttons and texts in Multiple recipients page
- Fix for long addresses in confirm page for multisend details
- Fix for disabled Continue button
- Consistent UI for select inputs page
=> Multisend improvements

src/components/info-sheet/info-sheet.html, src/pages/buy-crypto/country-selector/country-selector.ts, src/pages/buy-crypto/crypto-offers/crypto-offers.html, src/pages/buy-crypto/crypto-offers/crypto-offers.ts, src/pages/buy-crypto/crypto-order-summary/crypto-order-summary.ts, src/pages/buy-crypto/crypto-payment-method/crypto-payment-method.ts, src/providers/buy-crypto/buy-crypto.ts
This new payment method is accepted by Simplex, only for countries belonging to the EU.
=> Feat: SEPA bank transfer payment method added

src/app/app.scss
=> fix(tabbar): icons alignment for small screen

config/uglify.config.js, config/webpack.config.js, package.json
Uses npm package webpack-obfuscator to obfuscate copay source code.
=> [FEAT] Scramble copay

src/theme/dark.scss
=> fix(theme): text color on Coinbase withdraw confirm view

src/pages/send/confirm/confirm.ts
needs https://github.com/bitpay/bitcore/pull/3000
=> [FIX] erc20 & eth multisig paypro when linked wallet has no funds

app-template/config-template.xml, package.json
See https://github.com/cmgustavo/cordova-apple-wallet
=> fix(apple-wallet): use custom plugin to force encryption scheme

src/pages/pin/pin-modal/pin-modal.spec.ts, src/pages/pin/pin-modal/pin-modal.ts
=> fix(lock app): reset timer if it failed on resume the event

package.json, src/pages/backup/backup-game/backup-game.ts, src/providers/key/key.spec.ts, src/providers/key/key.ts, src/providers/profile/profile.spec.ts, src/providers/profile/profile.ts, src/providers/wallet/wallet.spec.ts
fix lint
fix tests
fix tests
lint
update bws && fix tests
.
fix typo
.
=> use new BWC api

src/components/info-sheet/info-sheet.html, src/providers/action-sheet/action-sheet.ts, src/providers/bitpay-id/bitpay-id.ts, src/providers/in-app-browser/card.ts, src/providers/incoming-data/incoming-data.ts
This PR allows for unlocking/claiming of invoices with the bitpay Id userShopper token. To test use the following format for the intent:
`bitpay://unlock?r=https://<host>/i/<invoiceId>`
=> [FEAT] bitpay Id unlock shopper

src/providers/key/key.ts, src/providers/profile/profile.spec.ts, src/providers/profile/profile.ts
Reverts bitpay/copay#11273
It breaks the app:
=> Revert "[FIX]: Update backup flag when create new keys"

config/webpack.config.js
Only for env.DEV on browsers:
* Refresh data on browser after code has changed
=> ref(webpack): no obfuscate function for dev env

src/providers/theme/theme.ts, src/theme/dark.scss, src/theme/light.scss
=> fix(ui): improves dark/light mode on some user actions

src/components/encrypt-password/encrypt-password.html, src/components/info-sheet/info-sheet.html, src/pages/add/select-currency/select-currency.html, src/pages/backup/backup-game/backup-game.ts, src/pages/onboarding/disclaimer/disclaimer.html, src/pages/onboarding/disclaimer/disclaimer.scss, src/pages/onboarding/feature-education/feature-education.html, src/pages/onboarding/feature-education/feature-education.scss, src/pages/onboarding/lock-method/lock-method.ts, src/pages/onboarding/recovery-key/recovery-key.html, src/pages/onboarding/recovery-key/recovery-key.scss, src/providers/action-sheet/action-sheet.ts, src/theme/dark.scss
- Labels Updated
- New breakpoints for smaller screens
- Successfull screens for lock method and backup game
=> [Ref]: New onboarding

src/app/app.component.ts, src/providers/dynamic-links/dynamic-links.ts, src/providers/incoming-data/incoming-data.ts
Still having issue if app is closed. It works on background: https://github.com/chemerisuk/cordova-plugin-firebase-dynamiclinks/issues/85
=> fix(dynamic-links): adds handler to redirect any valid view

src/pages/integrations/bitpay-card/bitpay-card-intro/bitpay-card-intro.ts
=> fix(bp-card-intro): ask camera permission when open bp card intro view

src/providers/buy-crypto/buy-crypto.ts
=> Revert "Disable SEPA bank transfer payment method"

i18n/template.pot, src/components/encrypt-password/encrypt-password.html, src/pages/add/create-wallet/create-wallet.html, src/pages/buy-crypto/crypto-offers/crypto-offers.ts, src/pages/integrations/wallet-connect/wallet-connect.html, src/pages/settings/key-settings/key-onboarding/key-onboarding.html
=> New translations

src/pages/includes/multiple-outputs/multiple-outputs.html, src/pages/includes/multiple-outputs/multiple-outputs.scss, src/pages/includes/multiple-outputs/multiple-outputs.ts, src/pages/tx-details/tx-details.html
Depends on https://github.com/bitpay/bitcore/pull/3019
Add handle of misunderstood outputs
- show message after "Sending to" in transaction details screen
- when click the message redirect to blockchain
=> Improve: tx history

app-template/config-template.xml, package.json, src/app/app.component.ts, src/providers/dynamic-links/dynamic-links.ts
Uses latest version of FCM plugin: https://github.com/cmgustavo/cordova-plugin-fcm/releases/tag/v8.2.0
=> fix(dynamic-links): open deepLink on Android if App is non-installed, closed or in background

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, package-lock.json, package.json
* Updated translations
* Fix sending multiple recipients to contacts in address book
=> Bump v11.2.11

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, package-lock.json, package.json
=> v11.2.12-beta

src/components/info-sheet/info-sheet.html, src/pages/add/add.html, src/pages/add/select-currency/select-currency.html, src/pages/add/select-currency/select-currency.ts, src/pages/buy-crypto/crypto-order-summary/crypto-order-summary.ts, src/pages/onboarding/feature-education/feature-education.html
- Can create new keys by joining a wallet
- Fixed error when trying to create an ETH wallet in some cases (It was shown disabled as if it were a multisig)
- Create wallets from "Buy crypto", now difference between singleseed and multiseeds
- Fix: strings with missing translations
=> Fix: creation of wallets

src/providers/profile/profile.spec.ts, src/providers/profile/profile.ts, src/providers/push-notifications/push-notifications.ts
Needs https://github.com/bitpay/bitcore/pull/3012
=> [FEAT]: handling data messages

src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.ts
=> [FEAT] view history on blockchain explorer (ETH XRP)

src/pages/exchange-crypto/exchange-checkout/exchange-checkout.html, src/pages/exchange-crypto/exchange-checkout/exchange-checkout.ts, src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.ts
Also in this PR:
- Fix for BCH addresses
- Fix for selected wallet when we go to buy crypto from a specific wallet
=> Fix: exchange crypto Txs from ERC20

src/pages/home/home.ts, src/pages/new-feature/new-feature.html, src/pages/new-feature/new-feature.scss, src/pages/new-feature/new-feature.ts, src/pages/pages.ts, src/pages/settings/settings.html, src/pages/settings/settings.ts, src/providers/index.ts, src/providers/new-feature-data/new-feature-data.ts, src/providers/persistence/persistence.ts, src/providers/providers.module.ts
Add New Features slides for new app version.
How to use:
- open "_new-feature-data.ts_"
- add **FeatureList** to **feature_list**
- don't forget to input the right _version_ 
E.g.
```
{
version: '12.0.2',
dummy: this.translate.instant('dummy'),
features: [{
title: this.translate.instant('Some title'),
details: this.translate.instant('Details of the new feature'),
image: 'assets/img/new-feature/example.jpg', // optional
tryit: { name: 'NewPage' } // optional
}]
}
```
=> Feat/New Features Slides

src/app/app.component.ts, src/pages/cards/cards.ts, src/pages/home/home.ts, src/pages/integrations/bitpay-card/bitpay-card-intro/bitpay-card-intro.ts, src/pages/settings/bitpay-id/bitpay-id.ts, src/pages/settings/local-theme/local-theme.ts, src/pages/settings/settings.ts, src/pages/tabs/tabs.ts, src/providers/bitpay-id/bitpay-id.ts, src/providers/gift-card/gift-card.ts, src/providers/in-app-browser/card.ts, src/providers/invoice/invoice.ts, src/providers/on-going-process/on-going-process.ts
- refactored IAB ping method to postMessage from its success callback
- synced theme change with app
- added loading wrapper to prevent flashing of initial theme load
- refactored and synced card advertisements with card initial fetch, connecting/disconnecting bitpay id events
=> [FEAT] optimize IAB init

src/pages/send/send.spec.ts, src/pages/send/send.ts
- Move events subscribers to ionViewWillEnter
- Fix this.search assignment
- Move **_setDataFromClipboard_** to async method
=> Minor fix - sendPage

src/pages/wallets/wallets.html, src/providers/coinbase/coinbase.ts
* Speedup Wallets tab. Show Coinbase section until coinbaseData is available
=> fix(coinbase): Ignore coin without exchange rate

src/providers/external-link/external-link.ts
See: https://github.com/apache/cordova-plugin-inappbrowser/pull/600
=> APP-84 Fix window.open

src/pages/send/send.spec.ts, src/pages/send/send.ts
=> Revert "Minor fix - sendPage"

src/pages/integrations/gift-cards/card-details/card-details.html, src/pages/integrations/gift-cards/card-details/card-details.ts
"Claim code not yet available. Please check back later. If this issue persists for more than 2 hours, please contact BitPay Support."
=> Better claim code fetch error message

src/pages/home/home.ts, src/pages/new-feature/new-feature.html, src/pages/new-feature/new-feature.scss, src/pages/new-feature/new-feature.ts, src/pages/settings/settings.ts
- Dismiss if "Try It" is in the last slide
- Change "done" with "got it" or "dismiss"
- Increase bold to slides title
=> APP-101 v12.1 New Feature Slides feedback

src/pages/buy-crypto/crypto-coin-selector/crypto-coin-selector.ts, src/pages/buy-crypto/crypto-offers/crypto-offers.ts, src/pages/buy-crypto/crypto-order-summary/crypto-order-summary.ts, src/pages/buy-crypto/crypto-payment-method/crypto-payment-method.ts, src/pages/send/amount/amount.ts, src/providers/buy-crypto/buy-crypto.ts
This PR needs: https://github.com/bitpay/bitcore/pull/3070
Removes Wyre option from EU Countries and Canada.
Sets Credit card as default option
=> Ref: remove Wyre for EU countries and Canada if promotion is active

app-template/index-template.html
=> APP-92 ref(index-template): removed unused domain

package-lock.json, package.json
Ref: #11480 
https://github.com/electron/electron/releases/tag/v9.4.2
=> APP-81 Bump electron from 9.3.5 to 9.4.2

app-template/config-template.xml, package.json
Reference to latest changes on the plugin:
https://github.com/cmgustavo/cordova-plugin-fcm/commit/e81fc981a0e625674b0a04f89c69e1e4d07cc7af
=> APP-51 Fix Dynamic Link on iOS

src/pages/tabs/tabs.ts
- Remove the blocking flag "foundMessage"
- Fix the event topic to **Local/ServerMessages**
=> Fix ServerMessage event

README.md
=> [REF] Update README

README.md
=> Revert "[REF] Update README"

src/pages/send/send.html, src/pages/send/send.spec.ts, src/pages/send/send.ts, src/pages/send/transfer-to/transfer-to.html, src/pages/send/transfer-to/transfer-to.scss, src/pages/send/transfer-to/transfer-to.ts
- Remove old things
- Move to async
- Move to ionViewDidEnter
- Avoid multi-tap contacts to send
=> APP-61 Improve/Fix SendPage

src/app/app.component.ts, src/pages/home/home.html, src/pages/home/home.ts, src/pages/tabs/tabs.ts, src/providers/new-feature-data/new-feature-data.ts, src/providers/persistence/persistence.ts
- tapping on 'Home' toggles between networks
- tied feature-data provider and tab component to globally set network
- fixed the card advertisement not being set on init
=> [FEAT] dynamic network setting

src/app/app.component.ts
Deep link format: `https://<domain>/?view=ExchangeCryptoPage`
=> APP-121 feat(link): adds ExchangeCryptoPage to DynLink

src/app/app.scss, src/components/coin-icon/coin-icon.scss, src/pages/exchange-crypto/exchange-checkout/exchange-checkout.html, src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.html, src/pages/integrations/coinbase/coinbase-withdraw/coinbase-withdraw.html, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.html, src/pages/paper-wallet/paper-wallet.html, src/pages/send/confirm/confirm.html, src/pages/slide-to-accept/slide-to-accept.html, src/pages/slide-to-accept/slide-to-accept.scss, src/pages/slide-to-accept/slide-to-accept.ts, src/pages/txp-details/txp-details.html, src/providers/currency/coin.ts, src/theme/lists.scss
=> Feat: dogecoin theme for slide to pay

src/components/exchange-rates/exchange-rates.ts, src/pages/home/price-page/price-page.ts
waiting for decimals to be added here https://bitpay.com/api/rates/doge
=> [FIX]: more decimals for doge

codecov.yml
=> Adds codecov.yml

src/pages/send/confirm/confirm.html, src/pages/send/confirm/confirm.ts
- Change fee percentage calculation over the amount (not amount+fee)
- Remove possible confuse message on UI
=> APP-62 Adjust feeRate calculation and UI message

src/pages/home/home.ts, src/pages/tabs/tabs.ts, src/providers/profile/profile.spec.ts, src/providers/rate/rate.spec.ts, src/providers/rate/rate.ts
It needs https://github.com/bitpay/bitcore/pull/3060
=> [REF]: check alt currency

src/pages/scan/scan.html, src/pages/scan/scan.scss, src/pages/scan/scan.ts, src/providers/scan/scan.ts
This PR also:
- Improves the click area to open the scanner
- Removes unnecessary code
=> APP-154 Fix: scanner permissions - black screen

src/app/app.component.ts, src/pages/cards/cards.scss, src/pages/home/home.ts, src/pages/integrations/gift-cards/phone/phone.ts, src/pages/integrations/gift-cards/purchased-cards/purchased-cards.spec.ts, src/pages/tabs/tabs.ts, src/providers/gift-card/gift-card.ts, src/providers/location/location.ts, src/providers/tab/tab.ts
* Removed unused css classes
* Use Cached country instead to call same request
=> ref(location): optimize http request (using cache)

src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/send/amount/amount.ts, src/pages/send/confirm/confirm.ts, src/pages/send/multi-send/multi-send.ts, src/pages/send/select-inputs/select-inputs.ts, src/providers/filter/filter.spec.ts, src/providers/filter/filter.ts, src/providers/tx-format/tx-format.spec.ts, src/providers/tx-format/tx-format.ts
This PR is to prevent functions that sometimes return numbers and sometimes return strings.
Improves types and unit tests
=> Ref: format Amount

src/components/info-sheet/info-sheet.html, src/components/wallet-receive/wallet-receive.html, src/components/wallet-receive/wallet-receive.ts, src/providers/action-sheet/action-sheet.ts
=> [FEAT] warning message when generating address

src/components/info-sheet/info-sheet.html, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.html, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/send/confirm/confirm.ts
Add complete insufficient funds message when buy giftcard
- MIner fee
- Network fee
And show both in UI.
=> APP-198 Reuse handleError with insufficient funds message improved

src/components/info-sheet/info-sheet.html, src/components/info-sheet/info-sheet.ts, src/pages/buy-crypto/crypto-order-summary/crypto-order-summary.ts, src/pages/exchange-crypto/exchange-crypto.ts, src/providers/action-sheet/action-sheet.ts, src/providers/wyre/wyre.ts
=> Feat: buy/exchange crypto improvements

src/providers/coinbase/coinbase.ts, src/theme/dark.scss
=> Fix(Coinbase): pay invoices and refresh token if it has expired

src/app/app.component.ts
incremented card and settings globalTab.select index to account for transact being added
=> [FIX] globalTab indexes for card and settings

src/pages/home/home.html, src/pages/home/home.ts, src/pages/integrations/wallet-connect/wallet-connect-settings/wallet-connect-settings.html, src/pages/integrations/wallet-connect/wallet-connect-settings/wallet-connect-settings.scss, src/pages/integrations/wallet-connect/wallet-connect-settings/wallet-connect-settings.ts, src/pages/integrations/wallet-connect/wallet-connect.html, src/pages/integrations/wallet-connect/wallet-connect.scss, src/pages/integrations/wallet-connect/wallet-connect.ts, src/pages/pages.ts, src/pages/settings/settings.ts, src/providers/config/config.ts
=> [APP-149] Fix WalletConnect UI. Adds to Home tab (optional)

src/pages/send/confirm/confirm.html, src/pages/send/confirm/confirm.ts, src/pages/tx-details/tx-details.html, src/pages/wallet-details/wallet-details.ts, src/providers/wallet/wallet.ts
It needs https://github.com/bitpay/bitcore/pull/3126
=> [FEAT]: speed up eth tx

src/components/footer-menu/footer-menu.html, src/components/footer-menu/footer-menu.scss, src/pages/home/home.html, src/pages/home/home.scss, src/pages/home/home.ts, src/pages/settings/bitpay-id/bitpay-id.html, src/pages/settings/bitpay-id/bitpay-id.scss, src/pages/settings/bitpay-id/bitpay-id.ts, src/pages/settings/settings.html, src/pages/settings/settings.scss, src/pages/settings/settings.ts
* Fix login icon alignment (from Home, Settings and BitPayId views)
* Do not apply background when pressing "Scan" button (Active)
* Adds margin bottom to the "Close" button
=> Fix APP-232: bp icon login, scan button and close button

src/pages/add/create-wallet/create-wallet.ts, src/providers/currency/coin.ts, src/providers/derivation-path-helper/derivation-path-helper.ts
It needs https://github.com/bitpay/bitcore/pull/3155
=> APP-222: Doge multisig

src/components/footer-menu/footer-menu.html, src/components/footer-menu/footer-menu.scss, src/components/footer-menu/footer-menu.ts, src/pages/tabs/tabs.html, src/pages/tabs/tabs.ts, src/providers/action-sheet/action-sheet.ts, src/providers/clipboard/clipboard.ts
This option will mainly allow users to pay BitPay invoices with a Coinbase account on the desktop version.
=> APP-258: Clipboard added to transact menu (desktop only)

app-template/config-template.xml, build-extras.gradle, copy-build-extras-gradle.js
* Target SDK version: 30 (Android 11)
=> APP-250 Set android-targetSdkVersion 30

src/providers/coinbase/coinbase.ts
Changes in Coinbase account is required.
=> APP-190: Increase send limit amount

src/pages/settings/fee-policy/fee-policy.scss, src/theme/dark.scss
=> APP-291: Network fee policy dark mode

app-template/config-template.xml, build-extras.gradle, copy-build-extras-gradle.js
=> Revert "APP-250 Set android-targetSdkVersion 30"

src/pages/add/create-wallet/create-wallet.html, src/pages/add/create-wallet/create-wallet.ts, src/providers/profile/profile.ts
needs https://github.com/bitpay/bitcore/pull/3210
=> [FEAT] LTC segwit

src/components/coin-icon/coin-icon.ts
=> [FIX] Coin icon component when coin changes

src/components/info-sheet/info-sheet.html, src/components/wallet-receive/wallet-receive.ts, src/pages/add/create-wallet/create-wallet.html, src/pages/wallet-details/wallet-details.html, src/providers/action-sheet/action-sheet.ts
=> [REF] warning testnet messages

src/components/info-sheet/info-sheet.html, src/pages/send/confirm/confirm.ts, src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.scss, src/pages/wallet-details/wallet-details.ts, src/providers/action-sheet/action-sheet.ts, src/providers/persistence/persistence.ts
=> [REF] save multisig creation data if it not confirms

src/pages/add/create-wallet/create-wallet.ts, src/pages/add/join-wallet/join-wallet.ts, src/providers/derivation-path-helper/derivation-path-helper.ts
needs https://github.com/bitpay/bitcore/pull/3232
=> [FEAT] LTC multisig

src/pages/add/import-wallet/import-wallet.ts, src/providers/profile/profile.ts
* Do not remove previous wallets every time it imports a new one
* Removed async functions
=> APP-310: Fix import wallet

src/components/info-sheet/info-sheet.html, src/pages/add/join-wallet/join-wallet.ts, src/providers/action-sheet/action-sheet.ts
=> [FEAT] Join warning message

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, package-lock.json, package.json
* [APP-313] Multisig creation waits for a confirmation. Better to save a flag and listing for changes on that transaction to get the created contract address
* [APP-189] Custom ERC20 Tokens
=> Bump v12.8.0-beta1

src/pages/integrations/wallet-connect/wallet-connect-request-details/wallet-connect-request-details.html, src/pages/integrations/wallet-connect/wallet-connect-request-details/wallet-connect-request-details.ts, src/providers/wallet-connect/wallet-connect.ts
- support for 'eth_sign' method
- do not allow approval of unsupported methods
=> APP-326: WalletConnect 'eth_sign' method

app-template/bitpay/appConfig.json, app-template/copay/appConfig.json, i18n/template.pot, package-lock.json, package.json, src/assets/i18n/de.po, src/assets/i18n/en.po, src/assets/i18n/es.po, src/assets/i18n/fr.po, src/assets/i18n/it.po, src/assets/i18n/ja.po, src/assets/i18n/ko.po, src/assets/i18n/nl.po, src/assets/i18n/pl.po, src/assets/i18n/pt.po, src/assets/i18n/ru.po, src/assets/i18n/zh.po, src/pages/exchange-crypto/exchange-crypto.ts
=> Bump v12.8.2-beta

src/components/info-sheet/info-sheet.html, src/pages/exchange-crypto/exchange-crypto.ts, src/pages/token-swap/token-swap-approve/token-swap-approve.html, src/pages/token-swap/token-swap-approve/token-swap-approve.ts, src/pages/token-swap/token-swap-checkout/token-swap-checkout.html, src/pages/token-swap/token-swap-checkout/token-swap-checkout.ts, src/providers/action-sheet/action-sheet.ts
This PR Also:
Removes unused code
Adds approximate amount in fiat for the fees
GasPrice is expressed in Gwei
=> Fix: Swap crypto texts

src/components/label-tip/label-tip.ts, src/pages/exchange-crypto/exchange-crypto.html, src/pages/exchange-crypto/exchange-crypto.ts, src/pages/token-swap/token-swap-approve/token-swap-approve.ts
- removed "Transaction Sent" screen
- added async mode to label tip
- adjusted copy
=> [FEAT] adjust approve flow

src/pages/home/home.ts, src/providers/app/app.ts, src/providers/new-feature-data/new-feature-data.ts
Ignores patches and solely checks that current major minor version === dismiss flag major minor
=> [FIX] feature slide 

src/providers/currency/currency.ts, src/providers/profile/profile.ts
needs https://github.com/bitpay/bitcore/pull/3252
=> [FIX] Server assisted import for custom tokens

src/pages/add/custom-token/custom-token.html, src/pages/add/custom-token/custom-token.scss, src/pages/add/custom-token/custom-token.ts, src/pages/coin-and-wallet-selector/coin-and-wallet-selector.html, src/pages/coin-and-wallet-selector/coin-and-wallet-selector.ts, src/pages/exchange-crypto/exchange-crypto.html, src/theme/dark.scss
The exact search result will be placed at the top of the results
Correction of errors in the styles of some icons
Fixed icons not showing (like EURT)
Some fixes in general
=> Ref: Tokens search

package.json, src/pages/integrations/wallet-connect/wallet-connect-request-details/wallet-connect-request-details.html, src/pages/integrations/wallet-connect/wallet-connect-request-details/wallet-connect-request-details.ts, src/pages/integrations/wallet-connect/wallet-connect.html, src/providers/abi-decoder/abi-decoder.ts, src/providers/abi-decoder/abi-erc20.ts, src/providers/abi-decoder/abi-invoice.ts, src/providers/index.ts, src/providers/providers.module.ts, src/providers/wallet-connect/wallet-connect.ts
=> [FEAT] improve approve wc

src/providers/coinbase/coinbase.ts
* Do not list duplicated accounts
* Filter custom ERC-20 tokens
* Get ordered accounts from Coinbase API
=> Fix: Coinbase integration

src/pages/integrations/wallet-connect/wallet-connect-request-details/wallet-connect-request-details.html, src/pages/integrations/wallet-connect/wallet-connect-request-details/wallet-connect-request-details.ts, src/pages/integrations/wallet-connect/wallet-connect.html, src/pages/integrations/wallet-connect/wallet-connect.scss
=> [REF] show spender and use correct icons

src/pages/integrations/wallet-connect/wallet-connect-request-details/wallet-connect-request-details.html, src/pages/integrations/wallet-connect/wallet-connect-request-details/wallet-connect-request-details.scss, src/pages/integrations/wallet-connect/wallet-connect-request-details/wallet-connect-request-details.ts
=> [REF] improve wc approve token view

src/pages/scan/scan.ts, src/providers/incoming-data/incoming-data.ts
Invoice url's are not being opened from all scan points. This PR adds the check at the top of the handler.
=> [FIX] invoice url scan

src/components/coin-icon/coin-icon.scss, src/pages/wallets/wallets.scss
=> Fix: coin icons in contacts from addressbook

src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts, src/pages/integrations/gift-cards/confirm-card-purchase/confirm-card-purchase.ts, src/pages/send/confirm/confirm.ts, src/providers/profile/profile.ts
=> [REF] avoid eth multisig paypro payments

package.json, src/pages/send/confirm/confirm.html, src/pages/send/confirm/confirm.ts, src/pages/send/select-inputs/select-inputs.html, src/pages/settings/advanced/advanced.html, src/pages/settings/advanced/advanced.ts, src/pages/tx-details/tx-details.html, src/pages/tx-details/tx-details.ts, src/pages/wallet-details/wallet-details.html, src/pages/wallet-details/wallet-details.scss, src/pages/wallet-details/wallet-details.ts, src/providers/config/config.ts, src/providers/wallet/wallet.ts, src/theme/dark.scss
=> [FEAT] RBF

src/pages/exchange-crypto/exchange-crypto.ts, src/pages/integrations/one-inch/one-inch.ts, src/pages/wallet-details/wallet-details.ts, src/providers/exchange-crypto/exchange-crypto.ts
This PR needs: https://github.com/bitpay/bitcore/pull/3278
=> Ref: temporarily remove service

src/providers/push-notifications/push-notifications.ts
=> Revert "Do not register token for push notification on iOS"

src/pages/buy-crypto/crypto-order-summary/crypto-order-summary.html, src/providers/changelly/changelly.ts, src/providers/simplex/simplex.ts
Also fixes icon in "buy crypto" and "Swap" button in wallet details
=> Feat: shib support for Simplex

src/pages/exchange-crypto/exchange-crypto.ts, src/providers/changelly/changelly.ts, src/providers/simplex/simplex.ts
=> Revert "Feat: enable XRP for buy and swap crypto"

src/pages/integrations/bitpay-card/bitpay-card-topup/bitpay-card-topup.ts, src/providers/coinbase/coinbase.ts
Coinbase Account + BitPay Invoices
=> Improves error handler for paying invoices
